<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.vidocq.mansart</groupId>
        <artifactId>mansart-jakarta-persistence</artifactId>
        <version>0.3.0-SNAPSHOT</version>
    </parent>

    <artifactId>mansart-persistence-spi</artifactId>
    <name>Mansart :: Persistence :: SPI</name>
    <description>Service Provider Interface for Mansart Persistence implementation.</description>

    <dependencies>
        <dependency>
            <groupId>io.vidocq.mansart</groupId>
            <artifactId>mansart-persistence-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.mansart</groupId>
            <artifactId>mansart-data-dialect-spi</artifactId>
        </dependency>
    </dependencies>
</project>
