/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.data.tck;

import io.vidocq.mansart.data.cdi.MansartDataExtension;
import io.vidocq.mansart.data.cdi.MansartRuntimeProducer;
import io.vidocq.mansart.data.core.RepositoryRuntime;
import io.vidocq.mansart.data.tests.Author;
import io.vidocq.mansart.data.tests.AuthorRepository;
import io.vidocq.vauban.core.container.VaubanContainer;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;
import static org.testng.Assert.assertTrue;

/**
 * M6.1 smoke — bootstraps Vauban with the Mansart CDI BCE on the classpath, then verifies that
 * an {@code AuthorRepository} (declared in {@code mansart-data-tests}) is injectable through the
 * container and that CRUD round-trips through {@link RepositoryRuntime} (which is itself a
 * synthetic bean wired by {@code MansartDataExtension} via {@code DefaultRepositoryRuntimeCreator}).
 */
public class MansartCdiBootstrapSmokeTest {

    private VaubanContainer container;
    private AuthorRepository authors;
    private DataSource dataSource;

    @BeforeClass
    public void boot() {
        container = VaubanContainer.builder()
                .addBeanClass(MansartDataExtension.class)   // Mansart BCE — registered explicitly
                .addBeanClass(MansartRuntimeProducer.class) // CDI producer for RepositoryRuntime
                .addBeanClass(H2DataSourceProducer.class)   // user-supplied DataSource bean
                // The APT-generated *RepositoryImpl is a managed @Singleton bean: it must be in the
                // container for the BCE to honour it (the @Synthesis phase intentionally defers to a
                // managed impl rather than registering a duplicate synthetic bean). The entity is its
                // mapped type. Mirrors what MansartArquillianSmokeTest adds via its package sweep.
                .addBeanClass(io.vidocq.mansart.data.tests.Author.class)
                .addBeanClass(io.vidocq.mansart.data.tests.AuthorRepository.class)
                .addBeanClass(io.vidocq.mansart.data.tests.AuthorRepositoryImpl.class)
                .build();
        authors    = container.select(AuthorRepository.class);
        dataSource = container.select(DataSource.class);
    }

    @AfterClass(alwaysRun = true)
    public void shutdown() {
        if (container != null) container.close();
    }

    @BeforeMethod
    public void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
    }

    @Test
    public void runtimeIsResolved() {
        RepositoryRuntime rt = container.select(RepositoryRuntime.class);
        assertNotNull(rt, "RepositoryRuntime should be a synthetic bean wired by MansartDataExtension");
        assertEquals(rt.dialect().name(), "H2");
    }

    @Test
    public void authorRepositoryInjectedAndFunctional() {
        Author hugo = new Author();
        hugo.setName("Victor Hugo");
        Author saved = authors.save(hugo);

        assertNotNull(saved.getId());
        assertTrue(saved.getId() > 0);
        assertEquals(authors.findById(saved.getId()).orElseThrow().getName(), "Victor Hugo");
        assertEquals(authors.count(), 1L);
    }

    @Test
    public void derivedQueryThroughBce() {
        for (String name : new String[] { "Alpha", "Beta", "Gamma" }) {
            Author a = new Author(); a.setName(name); authors.save(a);
        }
        var hits = authors.findByNameLike("A%");
        assertEquals(hits.size(), 1);
        assertEquals(hits.get(0).getName(), "Alpha");
    }
}
