package io.vidocq.mansart.data.tck;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.testng.SkipException;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

/**
 * Smoke test executed before any TCK suite — verifies the Mansart provider can be bootstrapped
 * end-to-end and reaches the database.
 *
 * <p>Once {@code mansart-data-cdi} ships its {@code BuildCompatibleExtension} (M6.1), this class
 * will be replaced by an Arquillian deployment that wires Mansart into a Weld-embedded container
 * the same way the official TCK does it. For now it merely guards against breakage of the
 * standalone bootstrap path.
 */
public class MansartCdiBootstrapSmokeTest {

    private DataSource dataSource;
    private MansartData mansartData;

    @BeforeClass
    public void setUp() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:tck-smoke;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        try (Connection c = ds.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"smoke\"");
            s.execute("CREATE TABLE \"smoke\" (\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)");
        }
        this.dataSource = ds;
        this.mansartData = MansartData.builder().dataSource(ds).build();
    }

    @Test
    public void bootstrapResolvesH2Dialect() {
        if (!"H2".equals(mansartData.dialect().name())) {
            throw new AssertionError("Expected H2 dialect, got: " + mansartData.dialect().name());
        }
    }

    @Test
    public void cdiBceWiringNotYetImplemented() {
        // Placeholder marker — flips green only once mansart-data-cdi exposes
        // a working BuildCompatibleExtension.
        throw new SkipException("M6.1 — CDI BuildCompatibleExtension wiring still pending");
    }
}
