package io.vidocq.mansart.data.tck;

import io.vidocq.mansart.data.cdi.MansartDataExtension;
import io.vidocq.mansart.data.core.RepositoryRuntime;
import io.vidocq.mansart.data.dialect.h2.H2DialectFactory;
import io.vidocq.mansart.data.tests.Author;
import io.vidocq.mansart.data.tests.AuthorRepository;
import jakarta.inject.Inject;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.testng.Arquillian;
import org.jboss.shrinkwrap.api.Archive;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.StringAsset;
import org.jboss.shrinkwrap.api.spec.JavaArchive;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;
import static org.testng.Assert.assertTrue;

/**
 * M6.2 — Arquillian-driven smoke test using the Vauban deployable container ported into this
 * module. Mirrors {@link MansartCdiBootstrapSmokeTest} but goes through Arquillian's deploy +
 * enrich lifecycle, which is what the official Jakarta Data TCK suite does. Once the TCK jar is
 * installed in the local M2 (see README.md), the same harness runs the official suite via
 * {@code -Ptck-run}.
 */
public class MansartArquillianSmokeTest extends Arquillian {

    @Deployment
    public static Archive<?> deployment() {
        return ShrinkWrap.create(JavaArchive.class, "mansart-arquillian-smoke.jar")
                // Mansart implementation modules (impl + dialect + CDI BCE wiring)
                // M7-29: mansart-data-api retired — no longer added.
                .addPackages(true, "io.vidocq.mansart.data.dialect")
                .addPackages(true, "io.vidocq.mansart.data.core")
                .addPackages(true, "io.vidocq.mansart.data.cdi")
                .addPackages(true, "io.vidocq.mansart.data.dialect.h2")
                // Mansart-data-tests entity + repository + generated impl + metamodel
                .addPackages(true, "io.vidocq.mansart.data.tests")
                // Test-side producer of the H2 DataSource — addPackages ensures the .class
                // is read from the test classloader (ShrinkWrap addClass on its own occasionally
                // missed it depending on the surefire fork classpath layout).
                .addClasses(H2DataSourceProducer.class, MansartArquillianSmokeTest.class)
                // META-INF/mansart-repositories.list (consumed by the BCE)
                .addAsResource(new StringAsset(
                        "io.vidocq.mansart.data.tests.AuthorRepository=io.vidocq.mansart.data.tests.AuthorRepositoryImpl\n"
                      + "io.vidocq.mansart.data.tests.ArticleRepository=io.vidocq.mansart.data.tests.ArticleRepositoryImpl\n"),
                        "META-INF/mansart-repositories.list")
                // ServiceLoader registrations (BCE + Dialect)
                .addAsResource(new StringAsset(MansartDataExtension.class.getName() + "\n"),
                        "META-INF/services/jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension")
                .addAsResource(new StringAsset(H2DialectFactory.class.getName() + "\n"),
                        "META-INF/services/io.vidocq.mansart.data.dialect.DialectFactory");
    }

    @Inject
    AuthorRepository authors;

    @Inject
    DataSource dataSource;

    @Inject
    RepositoryRuntime runtime;

    @BeforeMethod
    public void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
    }

    @Test
    public void runtimeIsInjectedViaArquillian() {
        assertNotNull(runtime, "RepositoryRuntime should be injected by VaubanTestEnricher");
        assertEquals(runtime.dialect().name(), "H2");
    }

    @Test
    public void authorRepositoryRoundTripsThroughDeployment() {
        Author a = new Author();
        a.setName("Émile Zola");
        Author saved = authors.save(a);

        assertNotNull(saved.getId());
        assertTrue(saved.getId() > 0);
        assertEquals(authors.findById(saved.getId()).orElseThrow().getName(), "Émile Zola");
    }

    @AfterMethod
    public void cleanup() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
        }
    }
}
