package io.vidocq.mansart.data.tck;

import io.vidocq.mansart.data.cdi.MansartDataExtension;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import io.vidocq.mansart.data.dialect.h2.H2DialectFactory;
import jakarta.data.repository.BasicRepository;
import jakarta.data.repository.Repository;
import jakarta.inject.Inject;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.testng.Arquillian;
import org.jboss.shrinkwrap.api.Archive;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.StringAsset;
import org.jboss.shrinkwrap.api.spec.JavaArchive;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotNull;

/**
 * M7-4 diagnostic — proves the BCE @Enhancement runtime-discovery + Proxy injection path works
 * end-to-end through Vauban + Arquillian, on a deployment that has NO compile-time
 * {@code mansart-repositories.list}. If this passes, any remaining TCK failures are about
 * dialect/feature gaps, not BCE wiring.
 */
public class RuntimeRepoArquillianTest extends Arquillian {

    @Entity
    @jakarta.persistence.Table(name = "widgets")
    public static class Widget {
        @Id @GeneratedValue private Long id;
        private String label;
        public Long getId() { return id; }
        public void setId(Long id) { this.id = id; }
        public String getLabel() { return label; }
        public void setLabel(String label) { this.label = label; }
    }

    @Repository
    public interface WidgetRepository extends BasicRepository<Widget, Long> {}

    @Deployment
    public static Archive<?> deployment() {
        // NO mansart-repositories.list — the BCE @Enhancement must be the only path that
        // makes WidgetRepository injectable.
        return ShrinkWrap.create(JavaArchive.class, "runtime-repo-arquillian.jar")
                // M7-29: mansart-data-api retired — no longer added.
                .addPackages(true, "io.vidocq.mansart.data.dialect")
                .addPackages(true, "io.vidocq.mansart.data.core")
                .addPackages(true, "io.vidocq.mansart.data.cdi")
                .addPackages(true, "io.vidocq.mansart.data.dialect.h2")
                .addClasses(RuntimeRepoArquillianTest.class,
                            Widget.class,
                            WidgetRepository.class)
                .addAsResource(new StringAsset(MansartDataExtension.class.getName() + "\n"),
                        "META-INF/services/jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension")
                .addAsResource(new StringAsset(H2DialectFactory.class.getName() + "\n"),
                        "META-INF/services/io.vidocq.mansart.data.dialect.DialectFactory");
    }

    @Inject
    WidgetRepository widgets;

    @Inject
    DataSource dataSource;

    @BeforeMethod
    public void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"widgets\"");
            s.execute("CREATE TABLE \"widgets\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"label\" VARCHAR(200) NOT NULL"
                    + ")");
        }
    }

    @Test
    public void widgetRepositoryInjectedAndFunctional() {
        assertNotNull(widgets, "WidgetRepository should be injected via runtime BCE path");
        Widget w = new Widget();
        w.setLabel("hello");
        Widget saved = widgets.save(w);
        assertNotNull(saved.getId());
        assertEquals(widgets.findById(saved.getId()).orElseThrow().getLabel(), "hello");
    }
}
