<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.vidocq.mansart</groupId>
        <artifactId>mansart-jakarta-persistence</artifactId>
        <version>0.3.0-SNAPSHOT</version>
    </parent>

    <artifactId>mansart-persistence-cdi</artifactId>
    <packaging>jar</packaging>

    <name>Mansart :: Persistence :: CDI</name>
    <description>CDI 4.1 integration for Mansart Jakarta Persistence 3.2 - Build Compatible Extension (BCE) for Vauban.</description>

    <dependencies>
        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.mansart</groupId>
            <artifactId>mansart-persistence-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
        </dependency>
    </dependencies>
</project>
