/*
 * Copyright (c) ${year} Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */

package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * M7-28 — exercises the compile-time {@code RepositoryWriter} on the comparators that were
 * runtime-only before this jalon: {@code Contains}, {@code StartsWith}, {@code EndsWith},
 * {@code IgnoreCase} (combined with Equals, Like, Not, Contains).
 *
 * <p>Goes through {@link MansartData#repository(Class)} (NOT {@code runtimeRepository}) so the
 * generated {@code AuthorRepositoryImpl} is the one under test. Validates parity with the
 * runtime path tested in {@link IgnoreCaseTest}.
 */
class CompiletimeComparatorsTest {

    private static DataSource dataSource;
    private static AuthorRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-compiletime;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        repo = MansartData.builder().dataSource(ds).build().repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        repo.save(named("Victor Hugo"));
        repo.save(named("VICTOR HUGO"));
        repo.save(named("victor hugo"));
        repo.save(named("Émile Zola"));
        repo.save(named("Honoré de Balzac"));
    }

    @Test
    void findByNameContainsMaterialisesPercentWildcards() {
        // 'Émile' is unique enough that LIKE-case-sensitivity quirks across DBs don't matter.
        List<Author> hits = repo.findByNameContains("mile");
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Émile Zola");
    }

    @Test
    void findByNameStartsWithMaterialisesTrailingPercent() {
        List<Author> hits = repo.findByNameStartsWith("Honoré");
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Honoré de Balzac");
    }

    @Test
    void findByNameEndsWithMaterialisesLeadingPercent() {
        List<Author> hits = repo.findByNameEndsWith("Balzac");
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Honoré de Balzac");
    }

    @Test
    void findByNameIgnoreCaseMatchesAllCasings() {
        List<Author> hits = repo.findByNameIgnoreCase("victor hugo");
        assertThat(hits).hasSize(3)
                .extracting(Author::getName)
                .containsExactlyInAnyOrder("Victor Hugo", "VICTOR HUGO", "victor hugo");
    }

    @Test
    void findByNameLikeIgnoreCaseMatchesPattern() {
        List<Author> hits = repo.findByNameLikeIgnoreCase("vic%");
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Victor Hugo", "VICTOR HUGO", "victor hugo");
    }

    @Test
    void findByNameNotIgnoreCaseExcludesAllCasings() {
        List<Author> hits = repo.findByNameNotIgnoreCase("victor hugo");
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Émile Zola", "Honoré de Balzac");
    }

    @Test
    void countByNameIgnoreCaseCountsAllCasings() {
        assertThat(repo.countByNameIgnoreCase("VICTOR HUGO")).isEqualTo(3L);
    }

    @Test
    void deleteByNameIgnoreCaseRemovesAllCasings() {
        long removed = repo.deleteByNameIgnoreCase("Victor Hugo");
        assertThat(removed).isEqualTo(3L);
        assertThat(repo.findByNameIgnoreCase("victor hugo")).isEmpty();
    }

    @Test
    void findByNameContainsIgnoreCaseCombinesBoth() {
        List<Author> hits = repo.findByNameContainsIgnoreCase("ICTOR");
        assertThat(hits).hasSize(3)
                .extracting(Author::getName)
                .containsExactlyInAnyOrder("Victor Hugo", "VICTOR HUGO", "victor hugo");
    }

    private static Author named(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
