/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * End-to-end CRUD test on H2 in-memory: builds a {@link MansartData} bootstrap, asks for a
 * generated {@link AuthorRepository}, and exercises save / findById / findAll / count / deleteById.
 */
class CrudIntegrationTest {

    private static DataSource dataSource;
    private static MansartData mansartData;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-crud;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
    }

    @Test
    void dialectIsH2() {
        assertThat(mansartData.dialect().name()).isEqualTo("H2");
    }

    @Test
    void saveAssignsGeneratedIdThenFindByIdReturnsEntity() {
        AuthorRepository repo = mansartData.repository(AuthorRepository.class);

        Author hugo = new Author();
        hugo.setName("Victor Hugo");

        Author saved = repo.save(hugo);

        assertThat(saved.getId()).isNotNull().isPositive();

        Optional<Author> found = repo.findById(saved.getId());
        assertThat(found).isPresent();
        assertThat(found.orElseThrow().getName()).isEqualTo("Victor Hugo");
    }

    @Test
    void findAllReturnsAllRows() {
        AuthorRepository repo = mansartData.repository(AuthorRepository.class);

        Author a = newAuthor("Alexandre Dumas");
        Author b = newAuthor("Émile Zola");
        repo.save(a);
        repo.save(b);

        List<Author> all = repo.findAll().toList();
        assertThat(all).hasSize(2)
                .extracting(Author::getName)
                .containsExactlyInAnyOrder("Alexandre Dumas", "Émile Zola");
    }

    @Test
    void countReflectsRowCount() {
        AuthorRepository repo = mansartData.repository(AuthorRepository.class);
        assertThat(repo.count()).isZero();

        repo.save(newAuthor("Marcel Proust"));
        repo.save(newAuthor("Marguerite Duras"));
        repo.save(newAuthor("Annie Ernaux"));

        assertThat(repo.count()).isEqualTo(3L);
    }

    @Test
    void existsByIdReportsPresence() {
        AuthorRepository repo = mansartData.repository(AuthorRepository.class);
        Author saved = repo.save(newAuthor("Albert Camus"));

        assertThat(repo.existsById(saved.getId())).isTrue();
        assertThat(repo.existsById(9_999_999L)).isFalse();
    }

    @Test
    void deleteByIdRemovesRow() {
        AuthorRepository repo = mansartData.repository(AuthorRepository.class);
        Author saved = repo.save(newAuthor("Simone de Beauvoir"));

        repo.deleteById(saved.getId());

        assertThat(repo.findById(saved.getId())).isEmpty();
        assertThat(repo.count()).isZero();
    }

    @Test
    void saveWithExistingIdUpsertsViaMerge() {
        AuthorRepository repo = mansartData.repository(AuthorRepository.class);

        Author saved = repo.save(newAuthor("First name"));
        Long id = saved.getId();

        saved.setName("Updated name");
        Author resaved = repo.save(saved);

        assertThat(resaved.getId()).isEqualTo(id);
        assertThat(repo.findById(id).orElseThrow().getName()).isEqualTo("Updated name");
        assertThat(repo.count()).isEqualTo(1L);
    }

    @Test
    void deleteRemovesByEntity() {
        AuthorRepository repo = mansartData.repository(AuthorRepository.class);
        Author saved = repo.save(newAuthor("Patrick Modiano"));

        repo.delete(saved);

        assertThat(repo.count()).isZero();
    }

    private static Author newAuthor(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
