/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import jakarta.data.page.CursoredPage;
import jakarta.data.page.PageRequest;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/** Validates single-attribute cursor (keyset) pagination on H2. */
class CursorPaginationTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-cursor;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        for (int i = 1; i <= 25; i++) repo.save(named("Author " + String.format("%02d", i)));
    }

    @Test
    void firstCursorPageWithoutCursorReturnsTopByOrder() {
        CursoredPage<Author> first = repo.findByNameLikeOrderByIdAsc("Author%", PageRequest.ofSize(10));
        assertThat(first.numberOfElements()).isEqualTo(10);
        assertThat(first.content()).first().extracting(Author::getName).isEqualTo("Author 01");
        assertThat(first.content()).last() .extracting(Author::getName).isEqualTo("Author 10");
        assertThat(first.hasNext()).isTrue();
    }

    @Test
    void afterCursorPagesForward() {
        CursoredPage<Author> first = repo.findByNameLikeOrderByIdAsc("Author%", PageRequest.ofSize(10));
        CursoredPage<Author> second = repo.findByNameLikeOrderByIdAsc("Author%", first.nextPageRequest());

        assertThat(second.numberOfElements()).isEqualTo(10);
        assertThat(second.content()).first().extracting(Author::getName).isEqualTo("Author 11");
        assertThat(second.content()).last() .extracting(Author::getName).isEqualTo("Author 20");

        CursoredPage<Author> third = repo.findByNameLikeOrderByIdAsc("Author%", second.nextPageRequest());
        assertThat(third.numberOfElements()).isEqualTo(5);
        assertThat(third.content()).first().extracting(Author::getName).isEqualTo("Author 21");
        assertThat(third.content()).last() .extracting(Author::getName).isEqualTo("Author 25");
        assertThat(third.hasNext()).isFalse();
    }

    @Test
    void beforeCursorPagesBackward() {
        CursoredPage<Author> first  = repo.findByNameLikeOrderByIdAsc("Author%", PageRequest.ofSize(10));
        CursoredPage<Author> second = repo.findByNameLikeOrderByIdAsc("Author%", first.nextPageRequest());

        // Now page backward from `second` to recover `first`
        CursoredPage<Author> back = repo.findByNameLikeOrderByIdAsc("Author%", second.previousPageRequest());

        assertThat(back.numberOfElements()).isEqualTo(10);
        assertThat(back.content()).first().extracting(Author::getName).isEqualTo("Author 01");
        assertThat(back.content()).last() .extracting(Author::getName).isEqualTo("Author 10");
    }

    @Test
    void emptyInShortCircuits() {
        // Empty list — should return empty without hitting the DB.
        List<Author> none = repo.findByNameIn(List.of());
        assertThat(none).isEmpty();
    }

    @Test
    void findByNameInWithMatches() {
        List<Author> matches = repo.findByNameIn(List.of("Author 03", "Author 07", "Author 12"));
        assertThat(matches).extracting(Author::getName)
                .containsExactlyInAnyOrder("Author 03", "Author 07", "Author 12");
    }

    private static Author named(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
