/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/** Exercises the M3b derived-query body generator on the {@link AuthorRepository}. */
class DerivedQueryTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-derived;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        repo.save(authorNamed("Victor Hugo"));
        repo.save(authorNamed("Victor Segalen"));
        repo.save(authorNamed("Émile Zola"));
    }

    @Test
    void findByNameReturnsExactMatches() {
        List<Author> list = repo.findByName("Victor Hugo");
        assertThat(list).hasSize(1)
                .extracting(Author::getName).containsExactly("Victor Hugo");
    }

    @Test
    void findOneByNameUnwrapsSingleResult() {
        assertThat(repo.findOneByName("Émile Zola"))
                .isPresent()
                .get().extracting(Author::getName).isEqualTo("Émile Zola");

        assertThat(repo.findOneByName("Nobody")).isEmpty();
    }

    @Test
    void findByNameLikeUsesSqlLike() {
        List<Author> victors = repo.findByNameLike("Victor%");
        assertThat(victors).hasSize(2)
                .extracting(Author::getName)
                .containsExactlyInAnyOrder("Victor Hugo", "Victor Segalen");
    }

    @Test
    void countByName() {
        assertThat(repo.countByName("Victor Hugo")).isEqualTo(1L);
        assertThat(repo.countByName("Nobody")).isZero();
    }

    @Test
    void existsByName() {
        assertThat(repo.existsByName("Émile Zola")).isTrue();
        assertThat(repo.existsByName("Nobody")).isFalse();
    }

    @Test
    void deleteByNameRemovesAndReportsCount() {
        long deleted = repo.deleteByName("Victor Hugo");
        assertThat(deleted).isEqualTo(1L);
        assertThat(repo.count()).isEqualTo(2L);
        assertThat(repo.findByName("Victor Hugo")).isEmpty();
    }

    @Test
    void orderByNameAsc() {
        List<Author> ordered = repo.findAllByOrderByNameAsc();
        assertThat(ordered).extracting(Author::getName)
                .containsExactly("Victor Hugo", "Victor Segalen", "Émile Zola");
    }

    private static Author authorNamed(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
