/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import io.vidocq.mansart.data.core.RuntimeEntityModelBuilder;
import io.vidocq.mansart.data.dialect.attribute.EnumAttribute;
import io.vidocq.mansart.data.dialect.attribute.EnumStorage;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/** {@code @Enumerated} decides how an enum is stored; no annotation stores the name (MANSART-003). */
class EnumStorageTest {

    private static DataSource dataSource;
    private static MansartData mansartData;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-enum-storage;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"enum_tickets\"");
            s.execute("CREATE TABLE \"enum_tickets\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"rank\" INTEGER, \"label\" VARCHAR(16), \"plain\" VARCHAR(16))");
        }
    }

    @Test
    void theProcessorReadsEnumerated() {
        assertThat(((EnumAttribute<?, ?>) _EnumTicket.rank).storage()).isEqualTo(EnumStorage.ORDINAL);
        assertThat(((EnumAttribute<?, ?>) _EnumTicket.label).storage()).isEqualTo(EnumStorage.STRING);
        assertThat(((EnumAttribute<?, ?>) _EnumTicket.plain).storage()).isEqualTo(EnumStorage.STRING);
    }

    @Test
    void theRuntimeBuilderReadsEnumerated() {
        var model = RuntimeEntityModelBuilder.build(EnumTicket.class);
        assertThat(storageOf(model, "rank")).isEqualTo(EnumStorage.ORDINAL);
        assertThat(storageOf(model, "label")).isEqualTo(EnumStorage.STRING);
        assertThat(storageOf(model, "plain")).isEqualTo(EnumStorage.STRING);
    }

    @Test
    void eachColumnHoldsWhatItsStorageSays() throws Exception {
        var repo = mansartData.repository(EnumTicketRepository.class);
        var ticket = new EnumTicket();
        ticket.setRank(Priority.HIGH);
        ticket.setLabel(Priority.MEDIUM);
        ticket.setPlain(Priority.LOW);
        var saved = repo.save(ticket);

        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement();
             ResultSet rs = s.executeQuery("SELECT \"rank\", \"label\", \"plain\" FROM \"enum_tickets\"")) {
            assertThat(rs.next()).isTrue();
            assertThat(rs.getInt(1)).isEqualTo(Priority.HIGH.ordinal());
            assertThat(rs.getString(2)).isEqualTo("MEDIUM");
            assertThat(rs.getString(3)).isEqualTo("LOW");
        }

        var found = repo.findById(saved.getId()).orElseThrow();
        assertThat(found.getRank()).isEqualTo(Priority.HIGH);
        assertThat(found.getLabel()).isEqualTo(Priority.MEDIUM);
        assertThat(found.getPlain()).isEqualTo(Priority.LOW);
    }

    @Test
    void aQueryOnAnOrdinalColumnBindsTheIndex() {
        var repo = mansartData.repository(EnumTicketRepository.class);
        var ticket = new EnumTicket();
        ticket.setRank(Priority.MEDIUM);
        ticket.setLabel(Priority.HIGH);
        repo.save(ticket);

        assertThat(repo.findByRank(Priority.MEDIUM)).hasSize(1);
        assertThat(repo.findByRank(Priority.LOW)).isEmpty();
        assertThat(repo.findByLabel(Priority.HIGH)).hasSize(1);
    }

    private static EnumStorage storageOf(io.vidocq.mansart.data.dialect.EntityModel<?> model, String name) {
        return model.attributes().stream().filter(a -> a.name().equals(name))
                .map(a -> ((EnumAttribute<?, ?>) a).storage()).findFirst().orElseThrow();
    }
}
