package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import jakarta.data.repository.BasicRepository;
import jakarta.data.repository.Repository;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * M7-27 — exercises {@code IgnoreCase} derived-query semantics. Validates that the dialect
 * emits {@code LOWER(col) <op> LOWER(?)} (database-side case-folding, locale-aware) instead
 * of the previous client-side {@code String.toLowerCase(ROOT)} hack which broke on data with
 * mixed casing in the database.
 *
 * <p>Goes through the runtime path because the compile-time {@link
 * io.vidocq.mansart.data.processor.RepositoryWriter} doesn't yet emit IgnoreCase comparators —
 * the runtime path is the only one that supports them today.
 */
class IgnoreCaseTest {

    @Repository
    public interface IcAuthorRepo extends BasicRepository<Author, Long> {
        List<Author>     findByNameIgnoreCase(String name);
        List<Author>     findByNameLikeIgnoreCase(String pattern);
        List<Author>     findByNameNotIgnoreCase(String name);
        long             countByNameIgnoreCase(String name);
        long             deleteByNameIgnoreCase(String name);
    }

    private static DataSource dataSource;
    private static IcAuthorRepo repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-ignorecase;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        repo = MansartData.builder().dataSource(ds).build().runtimeRepository(IcAuthorRepo.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        // Seed mixed-case data — the previous toLowerCase-on-args hack would NEVER match
        // these rows because the rows themselves are NOT lowercase.
        repo.save(named("Victor Hugo"));
        repo.save(named("VICTOR HUGO"));
        repo.save(named("victor hugo"));
        repo.save(named("Émile Zola"));
        repo.save(named("Honoré de Balzac"));
    }

    @Test
    void equalsIgnoreCaseMatchesAllCasings() {
        List<Author> hits = repo.findByNameIgnoreCase("victor hugo");
        assertThat(hits).hasSize(3)
                .extracting(Author::getName)
                .containsExactlyInAnyOrder("Victor Hugo", "VICTOR HUGO", "victor hugo");
    }

    @Test
    void likeIgnoreCaseMatchesPattern() {
        List<Author> hits = repo.findByNameLikeIgnoreCase("vic%");
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Victor Hugo", "VICTOR HUGO", "victor hugo");
    }

    @Test
    void notIgnoreCaseExcludesAllCasings() {
        List<Author> hits = repo.findByNameNotIgnoreCase("victor hugo");
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Émile Zola", "Honoré de Balzac");
    }

    @Test
    void countIgnoreCaseAggregates() {
        assertThat(repo.countByNameIgnoreCase("VICTOR HUGO")).isEqualTo(3L);
        assertThat(repo.countByNameIgnoreCase("nobody")).isZero();
    }

    @Test
    void deleteIgnoreCaseRemovesAllCasings() {
        long removed = repo.deleteByNameIgnoreCase("Victor Hugo");
        assertThat(removed).isEqualTo(3L);
        assertThat(repo.findByNameIgnoreCase("victor hugo")).isEmpty();
    }

    private static Author named(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
