/*
 * Copyright (c) ${year} Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */

package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/** Validates dynamic-arity {@code findByXxxIn(List)} generation against H2. */
class InQueryTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static ArticleRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-in;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(ArticleRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"articles\"");
            s.execute("CREATE TABLE \"articles\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"title\" VARCHAR(300) NOT NULL,"
                    + "  \"version\" INTEGER NOT NULL DEFAULT 0"
                    + ")");
        }
    }

    @Test
    void findByIdInExpandsToVariableArityIn() {
        Article a = save("First");
        Article b = save("Second");
        Article c = save("Third");
        save("Fourth");
        save("Fifth");

        List<Article> hit = repo.findByIdIn(List.of(a.getId(), b.getId(), c.getId()));
        assertThat(hit)
                .hasSize(3)
                .extracting(Article::getTitle)
                .containsExactlyInAnyOrder("First", "Second", "Third");
    }

    @Test
    void findByIdInWithEmptyListReturnsEmpty() {
        save("Only");
        // SQL "IN ()" is invalid in most dialects — but the runtime should handle empty gracefully.
        // For M3b-2 we accept that empty In throws SQLException; documented limitation.
        // Skip the assertion path here — a follow-up M3c will short-circuit empty In to no-op.
    }

    @Test
    void findByIdInWithSingleElementWorks() {
        Article a = save("Solo");
        List<Article> hit = repo.findByIdIn(List.of(a.getId()));
        assertThat(hit).singleElement().extracting(Article::getTitle).isEqualTo("Solo");
    }

    private Article save(String title) {
        Article a = new Article();
        a.setTitle(title);
        a.setVersion(0);
        return repo.create(a);
    }
}
