/*
 * Copyright (c) ${year} Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */

package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * M8-1 — JDQL scalar functions: {@code UPPER}, {@code LOWER}, {@code LENGTH}, {@code ABS}, {@code CONCAT}.
 *
 * <p>Covers WHERE LHS (Eq/NotEq/Lt/Lte/Gt/Gte/Like/Between/In/IsNull) and SET RHS (UPDATE).
 */
class JdqlScalarFunctionsTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-jdql-fn;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        repo.save(named("Victor Hugo"));        // length 11
        repo.save(named("Émile Zola"));         // length 10
        repo.save(named("Honoré de Balzac"));   // length 16
        repo.save(named("Stendhal"));           // length 8
    }

    @Test
    void upperEqMatchesCaseInsensitively() {
        List<Author> hits = repo.jdqlUpperEq("VICTOR HUGO");
        assertThat(hits).extracting(Author::getName).containsExactly("Victor Hugo");
    }

    @Test
    void lowerLikeMatchesCaseInsensitively() {
        List<Author> hits = repo.jdqlLowerLike("%hugo%");
        assertThat(hits).extracting(Author::getName).containsExactly("Victor Hugo");
    }

    @Test
    void lengthGtFiltersByCharCount() {
        List<Author> hits = repo.jdqlLengthGt(10);
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Victor Hugo", "Honoré de Balzac");
    }

    @Test
    void lengthBetweenIsInclusive() {
        List<Author> hits = repo.jdqlLengthBetween(8, 11);
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Stendhal", "Émile Zola", "Victor Hugo");
    }

    @Test
    void absIdLteMatchesNumericRange() {
        List<Author> all = repo.jdqlAbsIdLte(Long.MAX_VALUE);
        assertThat(all).hasSize(4);
    }

    @Test
    void lowerInMatchesAnyArg() {
        List<Author> hits = repo.jdqlLowerIn("victor hugo", "stendhal");
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Victor Hugo", "Stendhal");
    }

    @Test
    void upperIsNotNullCountsAll() {
        long n = repo.jdqlUpperIsNotNullCount();
        assertThat(n).isEqualTo(4L);
    }

    @Test
    void setUpperUppercasesTheRow() {
        Author stendhal = repo.findOneByName("Stendhal").orElseThrow();
        long affected = repo.jdqlSetUpper(stendhal.getId());
        assertThat(affected).isEqualTo(1L);
        assertThat(repo.findOneByName("STENDHAL")).isPresent();
        assertThat(repo.findOneByName("Stendhal")).isEmpty();
    }

    @Test
    void setConcatSuffixAppendsString() {
        Author stendhal = repo.findOneByName("Stendhal").orElseThrow();
        long affected = repo.jdqlSetConcatSuffix(stendhal.getId(), " (1783)");
        assertThat(affected).isEqualTo(1L);
        assertThat(repo.findOneByName("Stendhal (1783)")).isPresent();
    }

    private static Author named(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
