package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * M5-3 — JDQL with OR/NOT around IN, plus multi-element IN literal {@code IN (a, b, c)}.
 */
class JdqlOrNotInTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-jdql3;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        repo.save(named("Alpha"));
        repo.save(named("Beta"));
        repo.save(named("Gamma"));
        repo.save(named("Delta"));
    }

    @Test
    void orWithInCollection() {
        List<Long> firstTwoIds = repo.findAllByOrderByNameAsc().stream()
                .limit(2).map(Author::getId).toList();
        // name = "Delta" OR id IN [first two] → Alpha, Beta, Delta
        List<Author> hits = repo.jdqlNameOrIdIn("Delta", firstTwoIds);
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Alpha", "Beta", "Delta");
    }

    @Test
    void orWithEmptyInCollectionDegradesToNameMatch() {
        // Empty IN inside OR → ALWAYS_FALSE for that disjunct → only the name match remains
        List<Author> hits = repo.jdqlNameOrIdIn("Gamma", List.of());
        assertThat(hits).extracting(Author::getName).containsExactly("Gamma");
    }

    @Test
    void notWithInCollection() {
        List<Long> firstTwoIds = repo.findAllByOrderByNameAsc().stream()
                .limit(2).map(Author::getId).toList();
        // NOT (id IN [first two]) → Gamma, Delta
        List<Author> hits = repo.jdqlNotIdIn(firstTwoIds);
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Gamma", "Delta");
    }

    @Test
    void notWithEmptyInIsTrueForAll() {
        // NOT (id IN []) → NOT FALSE → TRUE → all rows
        List<Author> hits = repo.jdqlNotIdIn(List.of());
        assertThat(hits).hasSize(4);
    }

    @Test
    void multiElementInLiteral() {
        List<Author> hits = repo.jdqlNameInLiteral("Alpha", "Gamma", "ZZZ");
        assertThat(hits).extracting(Author::getName)
                .containsExactlyInAnyOrder("Alpha", "Gamma");
    }

    private static Author named(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
