/*
 * Copyright (c) ${year} Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */

package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/** M5-4 — aggregates (MAX/MIN/SUM) and column projections. */
class JdqlAggregateAndProjectionTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-jdql4;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        repo.save(named("Alpha"));
        repo.save(named("Beta"));
        repo.save(named("Gamma"));
        repo.save(named("Delta"));
    }

    @Test
    void maxAggregate() {
        List<Long> ids = repo.findAllByOrderByNameAsc().stream().map(Author::getId).toList();
        Long maxId = repo.jdqlMaxId();
        assertThat(maxId).isEqualTo(ids.stream().mapToLong(Long::longValue).max().orElseThrow());
    }

    @Test
    void minAggregateWithFilter() {
        long minId = repo.jdqlMinIdByPattern("Alpha");
        Long alphaId = repo.findOneByName("Alpha").orElseThrow().getId();
        assertThat(minId).isEqualTo(alphaId.longValue());
    }

    @Test
    void sumAggregateOverEmptyMatchReturnsNull() {
        Long sum = repo.jdqlSumIdByPattern("__nope__");
        assertThat(sum).isNull();
    }

    @Test
    void projectionListAllNames() {
        List<String> names = repo.jdqlAllNames();
        assertThat(names).containsExactly("Alpha", "Beta", "Delta", "Gamma");
    }

    @Test
    void projectionOptionalSingleName() {
        Long alphaId = repo.findOneByName("Alpha").orElseThrow().getId();
        Optional<String> name = repo.jdqlNameById(alphaId);
        assertThat(name).contains("Alpha");

        Optional<String> none = repo.jdqlNameById(9_999_999L);
        assertThat(none).isEmpty();
    }

    private static Author named(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
