/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/** M5-2 — IN(:list), SELECT COUNT(*), UPDATE, DELETE statements. */
class JdqlExtensionsTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-jdql2;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        repo.save(named("Alpha"));
        repo.save(named("Beta"));
        repo.save(named("Gamma"));
        repo.save(named("Delta"));
    }

    @Test
    void inWithCollectionParam() {
        List<Long> firstThree = repo.findAllByOrderByNameAsc().stream()
                .limit(3)
                .map(Author::getId)
                .toList();
        List<Author> hits = repo.jdqlByIdIn(firstThree);
        assertThat(hits).hasSize(3);
    }

    @Test
    void inWithEmptyCollectionShortCircuits() {
        List<Author> none = repo.jdqlByIdIn(List.of());
        assertThat(none).isEmpty();
    }

    @Test
    void selectCountStarProjection() {
        long n = repo.jdqlSelectCountByNameLike("%a%"); // matches Alpha, Beta, Gamma, Delta (all)
        assertThat(n).isEqualTo(4L);

        long g = repo.jdqlSelectCountByNameLike("Gamma");
        assertThat(g).isEqualTo(1L);
    }

    @Test
    void updateStatementChangesMatchingRows() {
        long affected = repo.jdqlRename("Alpha", "Alpha (renamed)");
        assertThat(affected).isEqualTo(1L);
        assertThat(repo.findOneByName("Alpha")).isEmpty();
        assertThat(repo.findOneByName("Alpha (renamed)")).isPresent();
    }

    @Test
    void deleteStatementRemovesMatchingRows() {
        long affected = repo.jdqlDeleteByNameLike("%a%"); // matches all 4
        assertThat(affected).isEqualTo(4L);
        assertThat(repo.count()).isZero();
    }

    private static Author named(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
