package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * M8-2 — Multi-column projection: {@code SELECT a, b FROM ...} returning {@code Object[]} or
 * record DTOs.
 */
class JdqlMultiProjectionTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-jdql-multiproj;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        repo.save(named("Alpha"));
        repo.save(named("Beta"));
        repo.save(named("Gamma"));
    }

    @Test
    void listOfObjectArrays() {
        List<Object[]> rows = repo.jdqlIdNamePairs();
        assertThat(rows).hasSize(3);
        assertThat(rows.get(0)).hasSize(2);
        assertThat(rows.get(0)[1]).isEqualTo("Alpha");
        assertThat(rows.get(1)[1]).isEqualTo("Beta");
        assertThat(rows.get(2)[1]).isEqualTo("Gamma");
    }

    @Test
    void streamOfObjectArrays() {
        try (Stream<Object[]> stream = repo.jdqlIdNameStream("%a%")) {
            List<Object[]> collected = stream.toList();
            assertThat(collected).hasSize(3);
            assertThat(collected).allMatch(row -> row.length == 2 && row[1] instanceof String);
        }
    }

    @Test
    void optionalOfObjectArray() {
        Optional<Object[]> hit = repo.jdqlIdNameOptional("Beta");
        assertThat(hit).isPresent();
        assertThat(hit.get()[1]).isEqualTo("Beta");

        Optional<Object[]> miss = repo.jdqlIdNameOptional("Zeta");
        assertThat(miss).isEmpty();
    }

    @Test
    void listOfRecordDtos() {
        List<AuthorRepository.AuthorView> views = repo.jdqlAuthorViews();
        assertThat(views).hasSize(3);
        assertThat(views.get(0).name()).isEqualTo("Alpha");
        assertThat(views.get(1).name()).isEqualTo("Beta");
        assertThat(views.get(2).name()).isEqualTo("Gamma");
        assertThat(views.get(0).id()).isNotNull();
    }

    @Test
    void singleRecordDto() {
        long id = repo.findOneByName("Beta").orElseThrow().getId();
        AuthorRepository.AuthorView view = repo.jdqlAuthorViewById(id);
        assertThat(view.id()).isEqualTo(id);
        assertThat(view.name()).isEqualTo("Beta");
    }

    private static Author named(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
