package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/** M5 — validates the JDQL parser + body generator end-to-end on H2. */
class JdqlQueryTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-jdql;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        repo.save(named("Victor Hugo"));
        repo.save(named("Victor Segalen"));
        repo.save(named("Émile Zola"));
        repo.save(named("Marcel Proust"));
    }

    @Test
    void namedParamEqualityFiltersByExactMatch() {
        List<Author> hits = repo.jdqlByName("Victor Hugo");
        assertThat(hits).hasSize(1)
                .extracting(Author::getName).containsExactly("Victor Hugo");
    }

    @Test
    void likeWithOrderByDesc() {
        List<Author> hits = repo.jdqlNameLikeDesc("Victor%");
        assertThat(hits).extracting(Author::getName)
                .containsExactly("Victor Segalen", "Victor Hugo");
    }

    @Test
    void positionalParameter() {
        Author hugo = repo.jdqlByName("Victor Hugo").get(0);
        assertThat(repo.jdqlById(hugo.getId()))
                .isPresent()
                .get().extracting(Author::getName).isEqualTo("Victor Hugo");

        assertThat(repo.jdqlById(9_999L)).isEmpty();
    }

    @Test
    void andCombination() {
        Author first = repo.jdqlByName("Victor Hugo").get(0);
        // Anyone with name like "%" AND id strictly greater than the first author
        List<Author> hits = repo.jdqlNameLikeAndIdGt("%", first.getId());
        assertThat(hits).hasSize(3); // 3 of 4
        assertThat(hits).extracting(Author::getName)
                .doesNotContain("Victor Hugo");
    }

    @Test
    void isNotNullCount() {
        long n = repo.jdqlCountNonNull();
        assertThat(n).isEqualTo(4L);
    }

    private static Author named(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
