/*
 * Copyright (c) ${year} Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */

package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import jakarta.data.exceptions.OptimisticLockingFailureException;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Validates {@code @Insert} / {@code @Update} / {@code @Delete} lifecycle annotations and the
 * {@code @Version} optimistic locking semantics of the strict mutators.
 */
class LifecycleAndVersionTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static ArticleRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-lifecycle;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(ArticleRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"articles\"");
            s.execute("CREATE TABLE \"articles\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"title\" VARCHAR(300) NOT NULL,"
                    + "  \"version\" INTEGER NOT NULL DEFAULT 0"
                    + ")");
        }
    }

    @Test
    void insertAssignsIdAndZeroVersion() {
        Article a = newArticle("Hello");
        a.setVersion(0);
        Article saved = repo.create(a);

        assertThat(saved.getId()).isNotNull().isPositive();
        assertThat(saved.getVersion()).isZero();
        assertThat(repo.findById(saved.getId())).isPresent();
    }

    @Test
    void updateBumpsVersionOnSuccess() {
        Article a = newArticle("Initial title");
        a.setVersion(0);
        repo.create(a);

        a.setTitle("Updated title");
        Article updated = repo.modify(a);

        assertThat(updated.getVersion()).isEqualTo(1);
        assertThat(repo.findById(a.getId()).orElseThrow().getTitle()).isEqualTo("Updated title");

        // Second modify increments again
        a.setTitle("Twice");
        repo.modify(a);
        assertThat(a.getVersion()).isEqualTo(2);
    }

    @Test
    void updateWithStaleVersionThrowsOptimisticLock() {
        Article a = newArticle("Race");
        a.setVersion(0);
        repo.create(a);

        // Simulate two concurrent readers holding version 0
        Article readerOne = repo.findById(a.getId()).orElseThrow();
        Article readerTwo = repo.findById(a.getId()).orElseThrow();

        readerOne.setTitle("First wins");
        repo.modify(readerOne);  // version 0 → 1

        readerTwo.setTitle("Second is stale");
        assertThatThrownBy(() -> repo.modify(readerTwo))
                .isInstanceOf(OptimisticLockingFailureException.class)
                .hasMessageContaining("version=0");

        assertThat(repo.findById(a.getId()).orElseThrow().getTitle()).isEqualTo("First wins");
    }

    @Test
    void deleteStrictRemovesAndRefusesSecondCall() {
        Article a = newArticle("To remove");
        a.setVersion(0);
        repo.create(a);

        repo.remove(a);
        assertThat(repo.count()).isZero();

        assertThatThrownBy(() -> repo.remove(a))
                .isInstanceOf(OptimisticLockingFailureException.class);
    }

    @Test
    void deleteWithStaleVersionThrows() {
        Article a = newArticle("Concurrent delete");
        a.setVersion(0);
        repo.create(a);

        Article fresh = repo.findById(a.getId()).orElseThrow();
        fresh.setTitle("Bumped");
        repo.modify(fresh);   // version becomes 1, in-DB

        // a still holds version 0 — strict delete should fail
        assertThatThrownBy(() -> repo.remove(a))
                .isInstanceOf(OptimisticLockingFailureException.class);

        assertThat(repo.findById(a.getId())).isPresent();
    }

    private static Article newArticle(String title) {
        Article a = new Article();
        a.setTitle(title);
        return a;
    }
}
