package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import io.vidocq.mansart.pool.PoolConfig;
import io.vidocq.mansart.pool.PoolMetrics;
import io.vidocq.mansart.pool.core.MansartDataSource;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * MP-C-2 — proves {@link MansartDataSource} is a drop-in {@link javax.sql.DataSource} for the
 * mansart-data runtime: full CRUD via {@code AuthorRepository}, derived queries, JDQL @Query,
 * and snapshot of pool counters at the end show that borrows actually went through the pool.
 *
 * <p>Lives in mansart-data-tests on purpose — mansart-pool is a peer reactor that does not depend
 * on mansart-data. Putting the integration check here verifies the consumer side.
 */
class MansartPoolInteropTest {

    private static MansartDataSource    pool;
    private static MansartData          mansartData;
    private static AuthorRepository     authors;

    @BeforeAll
    static void initStack() {
        pool = MansartDataSource.of(PoolConfig.builder()
                .jdbcUrl("jdbc:h2:mem:mansart-pool-interop-" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1")
                .username("sa")
                .maxSize(4)
                .build());
        mansartData = MansartData.builder().dataSource(pool).build();
        authors     = mansartData.repository(AuthorRepository.class);
    }

    @AfterAll
    static void teardown() {
        if (pool != null) pool.close();
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = pool.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
    }

    @Test
    void crudThroughPooledDataSource() {
        Author a = new Author();
        a.setName("Émile Zola");
        Author saved = authors.save(a);
        assertThat(saved.getId()).isPositive();

        assertThat(authors.findById(saved.getId())).hasValueSatisfying(found ->
                assertThat(found.getName()).isEqualTo("Émile Zola"));

        assertThat(authors.count()).isEqualTo(1L);
    }

    @Test
    void derivedQueriesThroughPooledDataSource() {
        save("Honoré de Balzac");
        save("Victor Hugo");
        save("Émile Zola");

        List<Author> z = authors.findByNameLike("%Zola%");
        assertThat(z).hasSize(1);
        assertThat(z.get(0).getName()).isEqualTo("Émile Zola");

        assertThat(authors.countByName("Victor Hugo")).isEqualTo(1L);
        assertThat(authors.existsByName("Inconnu")).isFalse();
    }

    @Test
    void jdqlQueryThroughPooledDataSource() {
        save("Stendhal");
        save("Flaubert");
        long n = authors.jdqlCountNonNull();
        assertThat(n).isEqualTo(2L);
    }

    @Test
    void poolCountersAdvanceWithRepositoryCalls() {
        long before = pool.snapshot().totalBorrows();
        save("Maupassant");
        authors.findByName("Maupassant");
        authors.count();
        PoolMetrics after = pool.snapshot();
        assertThat(after.totalBorrows()).isGreaterThan(before);
        assertThat(after.totalLeaks()).isZero();
    }

    private static Author save(String name) {
        Author a = new Author();
        a.setName(name);
        return authors.save(a);
    }
}
