/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * M8-3i — query-by-method-name with path navigation through {@code @ManyToOne} relations:
 * {@code findByAuthorName} → {@code WHERE author.name = ?}.
 *
 * <p>The compile-time {@code RepositoryWriter} consults the cross-entity {@link
 * io.vidocq.mansart.data.processor.EntityRegistry} (populated during the same APT round) to
 * split CamelCase chunks like {@code AuthorName} into the dotted path {@code "author.name"}.
 * The generated impl emits {@code PathResolver.resolve(_Book.$MODEL, "author.name")}, which
 * returns a {@code JoinedAttribute}, and the dialect renders the appropriate INNER JOIN.
 */
class MethodNamePathTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository authors;
    private static BookRepository books;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-mn-paths;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        authors = mansartData.repository(AuthorRepository.class);
        books = mansartData.repository(BookRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"books\"");
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
            s.execute("CREATE TABLE \"books\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"title\" VARCHAR(300) NOT NULL,"
                    + "  \"author_id\" BIGINT NOT NULL,"
                    + "  \"published_on\" DATE,"
                    + "  \"version\" INT,"
                    + "  CONSTRAINT fk_books_author FOREIGN KEY (\"author_id\") REFERENCES \"authors\"(\"id\")"
                    + ")");
        }
        Author hugo = saveAuthor("Victor Hugo");
        Author zola = saveAuthor("Émile Zola");
        Author balzac = saveAuthor("Honoré de Balzac");
        try (Connection c = dataSource.getConnection();
             var ps = c.prepareStatement(
                     "INSERT INTO \"books\"(\"title\", \"author_id\", \"version\") VALUES (?, ?, 1)")) {
            insertBook(ps, "Les Misérables", hugo.getId());
            insertBook(ps, "Notre-Dame de Paris", hugo.getId());
            insertBook(ps, "Germinal", zola.getId());
            insertBook(ps, "L'Assommoir", zola.getId());
            insertBook(ps, "Le Père Goriot", balzac.getId());
        }
    }

    @Test
    void findByAuthorName_eq() {
        List<Book> hits = books.findByAuthorName("Victor Hugo");
        assertThat(hits).extracting(Book::getTitle)
                .containsExactlyInAnyOrder("Les Misérables", "Notre-Dame de Paris");
    }

    @Test
    void findByAuthorNameLike_pattern() {
        List<Book> hits = books.findByAuthorNameLike("%Zola%");
        assertThat(hits).extracting(Book::getTitle)
                .containsExactlyInAnyOrder("Germinal", "L'Assommoir");
    }

    @Test
    void findByAuthorNameIgnoreCase_lowerSqlSide() {
        List<Book> hits = books.findByAuthorNameIgnoreCase("victor hugo");
        assertThat(hits).hasSize(2);
    }

    @Test
    void findByTitleAndAuthorName_combinesFlatAndPath() {
        List<Book> hits = books.findByTitleAndAuthorName("Les Misérables", "Victor Hugo");
        assertThat(hits).hasSize(1);
        assertThat(hits.get(0).getTitle()).isEqualTo("Les Misérables");
    }

    @Test
    void findByAuthorNameOrderByTitleAsc() {
        List<Book> hits = books.findByAuthorNameOrderByTitleAsc("Victor Hugo");
        assertThat(hits).extracting(Book::getTitle)
                .containsExactly("Les Misérables", "Notre-Dame de Paris");
    }

    @Test
    void countByAuthorName() {
        long n = books.countByAuthorName("Émile Zola");
        assertThat(n).isEqualTo(2L);
    }

    @Test
    void existsByAuthorName() {
        assertThat(books.existsByAuthorName("Honoré de Balzac")).isTrue();
        assertThat(books.existsByAuthorName("Inconnu")).isFalse();
    }

    @Test
    void findOneByAuthorNameAndTitle() {
        Optional<Book> hit = books.findOneByAuthorNameAndTitle("Honoré de Balzac", "Le Père Goriot");
        assertThat(hit).isPresent();
        assertThat(hit.get().getTitle()).isEqualTo("Le Père Goriot");
    }

    private Author saveAuthor(String name) {
        Author a = new Author();
        a.setName(name);
        return authors.save(a);
    }

    private static void insertBook(java.sql.PreparedStatement ps, String title, long authorId) throws Exception {
        ps.setString(1, title);
        ps.setLong(2, authorId);
        ps.executeUpdate();
    }
}
