/*
 * Copyright (c) ${year} Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */

package io.vidocq.mansart.data.tests;

import io.vidocq.vauban.core.container.VaubanContainer;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * MANSART-005 regression — a {@code @Repository(dataStore = "auditds")} repository must route to
 * the {@code @Named("auditds")} DataSource even when its APT-generated {@code *Impl} is a managed
 * bean in the archive. Before the fix, the managed impl shadowed the synthetic routing bean and
 * every operation silently hit the {@code @Default} database.
 *
 * <p>Both databases get the {@code routed_notes} table, so a mis-routed write would succeed —
 * the test asserts on WHERE the row lands, not on an exception.
 */
class MultiDataStoreRoutingTest {

    private static VaubanContainer container;
    private static RoutedNoteRepository routedNotes;
    private static AuthorRepository authors;

    @BeforeAll
    static void boot() throws Exception {
        createSchemas();
        container = VaubanContainer.builder()
                .addBeanClass(io.vidocq.mansart.data.cdi.MansartDataExtension.class)
                .addBeanClass(io.vidocq.mansart.data.cdi.MansartRuntimeProducer.class)
                .addBeanClass(RoutingDataSources.class)
                // Managed APT impls in the archive — the exact configuration that used to shadow
                // the dataStore routing (MANSART-005).
                .addBeanClass(RoutedNote.class)
                .addBeanClass(RoutedNoteRepository.class)
                .addBeanClass(RoutedNoteRepositoryImpl.class)
                .addBeanClass(Author.class)
                .addBeanClass(AuthorRepository.class)
                .addBeanClass(AuthorRepositoryImpl.class)
                .build();
        routedNotes = container.select(RoutedNoteRepository.class);
        authors     = container.select(AuthorRepository.class);
    }

    @AfterAll
    static void shutdown() {
        if (container != null) container.close();
    }

    @BeforeEach
    void resetRows() throws Exception {
        for (String url : new String[]{RoutingDataSources.DEFAULT_URL, RoutingDataSources.AUDIT_URL}) {
            try (Connection c = RoutingDataSources.h2(url).getConnection(); Statement s = c.createStatement()) {
                s.execute("DELETE FROM \"routed_notes\"");
            }
        }
        try (Connection c = RoutingDataSources.h2(RoutingDataSources.DEFAULT_URL).getConnection();
             Statement s = c.createStatement()) {
            s.execute("DELETE FROM \"authors\"");
        }
    }

    private static void createSchemas() throws Exception {
        // routed_notes exists in BOTH databases: a mis-routed write must not fail, it must land
        // in the wrong place — that is what the assertions below detect.
        for (String url : new String[]{RoutingDataSources.DEFAULT_URL, RoutingDataSources.AUDIT_URL}) {
            try (Connection c = RoutingDataSources.h2(url).getConnection(); Statement s = c.createStatement()) {
                s.execute("CREATE TABLE IF NOT EXISTS \"routed_notes\" ("
                        + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "  \"text\" VARCHAR(200) NOT NULL"
                        + ")");
            }
        }
        try (Connection c = RoutingDataSources.h2(RoutingDataSources.DEFAULT_URL).getConnection();
             Statement s = c.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
    }

    private static int countRows(String url, String table) throws Exception {
        try (Connection c = RoutingDataSources.h2(url).getConnection();
             Statement s = c.createStatement();
             ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM \"" + table + "\"")) {
            rs.next();
            return rs.getInt(1);
        }
    }

    @Test
    void routedRepositoryWritesToNamedDataSource() throws Exception {
        RoutedNote note = new RoutedNote();
        note.setText("belongs to the audit DB");
        RoutedNote saved = routedNotes.save(note);

        assertThat(saved.getId()).isNotNull();
        assertThat(countRows(RoutingDataSources.AUDIT_URL, "routed_notes"))
                .as("@Repository(dataStore=\"auditds\") must write to the @Named(\"auditds\") database")
                .isEqualTo(1);
        assertThat(countRows(RoutingDataSources.DEFAULT_URL, "routed_notes"))
                .as("the @Default database must NOT receive the routed repository's rows")
                .isZero();
    }

    @Test
    void routedRepositoryReadsFromNamedDataSource() throws Exception {
        try (Connection c = RoutingDataSources.h2(RoutingDataSources.AUDIT_URL).getConnection();
             Statement s = c.createStatement()) {
            s.execute("INSERT INTO \"routed_notes\"(\"text\") VALUES ('pre-seeded in audit DB')");
        }

        var all = routedNotes.findAll().toList();
        assertThat(all).hasSize(1);
        assertThat(all.getFirst().getText()).isEqualTo("pre-seeded in audit DB");
    }

    @Test
    void defaultStoreRepositoryStillUsesDefaultDataSource() throws Exception {
        Author author = new Author();
        author.setName("Victor Hugo");
        Author saved = authors.save(author);

        assertThat(saved.getId()).isNotNull();
        assertThat(countRows(RoutingDataSources.DEFAULT_URL, "authors")).isEqualTo(1);
    }
}
