/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import jakarta.data.page.CursoredPage;
import jakarta.data.page.PageRequest;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * M3c-3 — multi-attribute lexicographic cursor pagination + mixed predicates with
 * {@code In(Collection)} dynamic arity.
 */
class MultiAttributeCursorAndMixedInTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-multi;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        // Two groups sharing the same name to exercise the secondary cursor key.
        for (int i = 1; i <= 6; i++) repo.save(named("Alpha"));
        for (int i = 1; i <= 6; i++) repo.save(named("Beta"));
        for (int i = 1; i <= 6; i++) repo.save(named("Gamma"));
    }

    @Test
    void multiAttributeCursorForwardWalksAllPages() {
        CursoredPage<Author> p1 = repo.findByNameLikeOrderByNameAscIdAsc("%", PageRequest.ofSize(5));
        assertThat(p1.numberOfElements()).isEqualTo(5);
        // 5 first rows by (name asc, id asc) = 5 first Alpha rows
        assertThat(p1.content()).extracting(Author::getName).containsOnly("Alpha");

        CursoredPage<Author> p2 = repo.findByNameLikeOrderByNameAscIdAsc("%", p1.nextPageRequest());
        assertThat(p2.numberOfElements()).isEqualTo(5);
        // The 6th row is the last Alpha; the next 4 are first Beta rows.
        assertThat(p2.content()).extracting(Author::getName)
                .containsExactly("Alpha", "Beta", "Beta", "Beta", "Beta");

        CursoredPage<Author> p3 = repo.findByNameLikeOrderByNameAscIdAsc("%", p2.nextPageRequest());
        assertThat(p3.numberOfElements()).isEqualTo(5);
        // Last 2 Beta + first 3 Gamma
        assertThat(p3.content()).extracting(Author::getName)
                .containsExactly("Beta", "Beta", "Gamma", "Gamma", "Gamma");

        CursoredPage<Author> p4 = repo.findByNameLikeOrderByNameAscIdAsc("%", p3.nextPageRequest());
        assertThat(p4.numberOfElements()).isEqualTo(3);
        assertThat(p4.content()).extracting(Author::getName).containsOnly("Gamma");
        assertThat(p4.hasNext()).isFalse();
    }

    @Test
    void multiAttributeCursorBackwardRecoversPreviousPage() {
        CursoredPage<Author> p1 = repo.findByNameLikeOrderByNameAscIdAsc("%", PageRequest.ofSize(5));
        CursoredPage<Author> p2 = repo.findByNameLikeOrderByNameAscIdAsc("%", p1.nextPageRequest());
        CursoredPage<Author> back = repo.findByNameLikeOrderByNameAscIdAsc("%", p2.previousPageRequest());

        assertThat(back.numberOfElements()).isEqualTo(5);
        assertThat(back.content()).extracting(Author::getId)
                .containsExactlyElementsOf(p1.content().stream().map(Author::getId).toList());
    }

    @Test
    void mixedInWithEqPredicate() {
        // Save extras under the Alpha name + capture three of them
        Author extra = repo.save(named("Extra"));
        // Pull all Alpha ids
        List<Long> alphaIds = repo.findByName("Alpha").stream().map(Author::getId).toList();
        List<Long> idsSubset = alphaIds.subList(0, 3);
        idsSubset = new java.util.ArrayList<>(idsSubset);
        idsSubset.add(extra.getId()); // an id whose name is NOT Alpha — should be filtered out

        List<Author> hits = repo.findByNameLikeAndIdIn("Alpha", idsSubset);
        assertThat(hits).hasSize(3);
        assertThat(hits).allSatisfy(a -> assertThat(a.getName()).isEqualTo("Alpha"));
        assertThat(hits).extracting(Author::getId)
                .containsExactlyInAnyOrderElementsOf(idsSubset.subList(0, 3));
    }

    @Test
    void mixedInWithEmptyCollectionShortCircuits() {
        List<Author> hits = repo.findByNameLikeAndIdIn("Alpha", List.of());
        assertThat(hits).isEmpty();
    }

    private static Author named(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
