/*
 * Copyright (c) ${year} Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */

package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * MANSART-002 regression: a derived query with a long {@code And} chain (3+ conditions) must parse
 * into one predicate per condition. The parser used to split on only the FIRST valid {@code And},
 * bundling the remaining conditions into an unresolvable token, which made the whole method fall
 * through to a silent {@code UnsupportedOperationException} stub (build green, runtime failure).
 */
class NaryDerivedQueryTest {

    private static DataSource dataSource;
    private static LabSeatRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-nary;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        repo = MansartData.builder().dataSource(ds).build().repository(LabSeatRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"lab_seats\"");
            s.execute("CREATE TABLE \"lab_seats\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"room_id\" VARCHAR(36) NOT NULL,"
                    + "  \"seat_row\" INTEGER NOT NULL,"
                    + "  \"seat_block_index\" INTEGER NOT NULL,"
                    + "  \"released\" BOOLEAN NOT NULL"
                    + ")");
        }
        repo.save(seat("room-1", 0, 0, false)); // target
        repo.save(seat("room-1", 0, 0, true));  // same coords but released
        repo.save(seat("room-1", 1, 0, false)); // different row
        repo.save(seat("room-2", 0, 0, false)); // different room
    }

    @Test
    void fourConditionAndChainResolvesEveryPredicate() {
        List<LabSeat> found =
                repo.findByRoomIdAndSeatRowAndSeatBlockIndexAndReleased("room-1", 0, 0, false);
        assertThat(found).hasSize(1);
        LabSeat s = found.get(0);
        assertThat(s.getRoomId()).isEqualTo("room-1");
        assertThat(s.getSeatRow()).isZero();
        assertThat(s.getSeatBlockIndex()).isZero();
        assertThat(s.isReleased()).isFalse();
    }

    @Test
    void twoConditionControlStillWorks() {
        assertThat(repo.findByRoomIdAndReleased("room-1", false)).hasSize(2);
        assertThat(repo.findByRoomIdAndReleased("room-2", false)).hasSize(1);
    }

    private static LabSeat seat(String roomId, int row, int block, boolean released) {
        LabSeat s = new LabSeat();
        s.setRoomId(roomId);
        s.setSeatRow(row);
        s.setSeatBlockIndex(block);
        s.setReleased(released);
        return s;
    }
}
