package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import jakarta.data.Order;
import jakarta.data.Sort;
import jakarta.data.page.Page;
import jakarta.data.page.PageRequest;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/** Validates offset pagination ({@link PageRequest} → {@link Page}) on H2. */
class PaginationTest {

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository repo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-page;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        for (int i = 1; i <= 25; i++) repo.save(named(String.format("Author %02d", i)));
    }

    @Test
    void inheritedFindAllPageRequestOrder() {
        Page<Author> p = repo.findAll(
                PageRequest.ofPage(1, 10, true),
                Order.by(Sort.asc("name")));

        assertThat(p.numberOfElements()).isEqualTo(10);
        assertThat(p.totalElements()).isEqualTo(25L);
        assertThat(p.totalPages()).isEqualTo(3L);
        assertThat(p.hasNext()).isTrue();
        assertThat(p.hasPrevious()).isFalse();
        assertThat(p.content()).first().extracting(Author::getName).isEqualTo("Author 01");
        assertThat(p.content()).last() .extracting(Author::getName).isEqualTo("Author 10");
    }

    @Test
    void secondPageIsCorrect() {
        Page<Author> p = repo.findAll(
                PageRequest.ofPage(2, 10, true),
                Order.by(Sort.asc("name")));

        assertThat(p.numberOfElements()).isEqualTo(10);
        assertThat(p.hasPrevious()).isTrue();
        assertThat(p.hasNext()).isTrue();
        assertThat(p.content()).first().extracting(Author::getName).isEqualTo("Author 11");
        assertThat(p.content()).last() .extracting(Author::getName).isEqualTo("Author 20");
    }

    @Test
    void lastPageReportsExhausted() {
        Page<Author> p = repo.findAll(
                PageRequest.ofPage(3, 10, true),
                Order.by(Sort.asc("name")));

        assertThat(p.numberOfElements()).isEqualTo(5);
        assertThat(p.hasNext()).isFalse();
        assertThat(p.hasPrevious()).isTrue();
        assertThat(p.content()).first().extracting(Author::getName).isEqualTo("Author 21");
        assertThat(p.content()).last() .extracting(Author::getName).isEqualTo("Author 25");
    }

    @Test
    void derivedPaginatedQuery() {
        Page<Author> p = repo.findByNameLikeOrderByNameAsc(
                "Author%",
                PageRequest.ofPage(2, 7, true));

        assertThat(p.numberOfElements()).isEqualTo(7);
        assertThat(p.totalElements()).isEqualTo(25L);
        assertThat(p.totalPages()).isEqualTo(4L); // ceil(25/7)
        assertThat(p.content()).first().extracting(Author::getName).isEqualTo("Author 08");
        assertThat(p.content()).last() .extracting(Author::getName).isEqualTo("Author 14");
    }

    @Test
    void withoutTotalSkipsCountQuery() {
        Page<Author> p = repo.findAll(
                PageRequest.ofPage(1, 10, false),
                Order.by(Sort.asc("name")));

        assertThat(p.numberOfElements()).isEqualTo(10);
        assertThat(p.hasTotals()).isFalse();
        assertThat(p.totalElements()).isEqualTo(-1L);
        assertThat(p.hasPrevious()).isFalse();
        // hasNext when no totals: true if page is full (size == numberOfElements)
        assertThat(p.hasNext()).isTrue();
    }

    private static Author named(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
