/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import jakarta.data.exceptions.OptimisticLockingFailureException;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.postgresql.ds.PGSimpleDataSource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * End-to-end CRUD + lifecycle + version tests against a real PostgreSQL container.
 *
 * <p>Excluded from the default run via the {@code pg-it} JUnit tag. Enable with:
 * <pre>mvn -ntp -Ppg-it -pl mansart-data-tests test</pre>
 * Requires Docker on the local machine.
 */
@Tag("pg-it")
@Testcontainers
class PostgresqlCrudIntegrationTest {

    @Container
    private static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:17-alpine")
            .withDatabaseName("mansart")
            .withUsername("mansart")
            .withPassword("mansart");

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository authors;
    private static ArticleRepository articles;
    private static EventRepository events;

    @BeforeAll
    static void initStack() {
        PGSimpleDataSource ds = new PGSimpleDataSource();
        ds.setUrl(POSTGRES.getJdbcUrl());
        ds.setUser(POSTGRES.getUsername());
        ds.setPassword(POSTGRES.getPassword());
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        authors  = mansartData.repository(AuthorRepository.class);
        articles = mansartData.repository(ArticleRepository.class);
        events   = mansartData.repository(EventRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("DROP TABLE IF EXISTS \"articles\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
            s.execute("CREATE TABLE \"articles\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"title\" VARCHAR(300) NOT NULL,"
                    + "  \"version\" INTEGER NOT NULL DEFAULT 0"
                    + ")");
            s.execute("DROP TABLE IF EXISTS \"events\"");
            s.execute("CREATE TABLE \"events\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"occurred_at\" TIMESTAMPTZ NOT NULL"
                    + ")");
        }
    }

    @Test
    void instantFieldRoundTripsThroughTimestamptz() {
        // MANSART-002: the PG driver rejects setObject(Instant, TIMESTAMP_WITH_TIMEZONE); the dialect
        // must bind an OffsetDateTime. This round-trip would throw "cannot convert Instant" without the fix.
        Event event = new Event();
        java.time.Instant when = java.time.Instant.parse("2026-05-31T12:34:56Z");
        event.setOccurredAt(when);

        Event saved = events.save(event);
        assertThat(saved.getId()).isNotNull();

        Event found = events.findById(saved.getId()).orElseThrow();
        assertThat(found.getOccurredAt()).isEqualTo(when);
    }

    @Test
    void dialectIsPostgresql() {
        assertThat(mansartData.dialect().name()).isEqualTo("PostgreSQL");
    }

    @Test
    void crudRoundTrip() {
        Author hugo = newAuthor("Victor Hugo");
        Author saved = authors.save(hugo);

        assertThat(saved.getId()).isNotNull().isPositive();
        assertThat(authors.findById(saved.getId())).isPresent()
                .get().extracting(Author::getName).isEqualTo("Victor Hugo");
        assertThat(authors.count()).isEqualTo(1L);

        saved.setName("Victor Hugo (renamed)");
        authors.save(saved);  // upsert via ON CONFLICT
        assertThat(authors.findById(saved.getId()).orElseThrow().getName())
                .isEqualTo("Victor Hugo (renamed)");
        assertThat(authors.count()).isEqualTo(1L);

        authors.deleteById(saved.getId());
        assertThat(authors.count()).isZero();
    }

    @Test
    void derivedQueriesAndPagination() {
        for (int i = 1; i <= 12; i++) authors.save(newAuthor(String.format("Author %02d", i)));

        List<Author> hits = authors.findByNameLike("Author 0%");
        assertThat(hits).hasSize(9);

        var page = authors.findByNameLikeOrderByNameAsc("Author%",
                jakarta.data.page.PageRequest.ofPage(2, 5, true));
        assertThat(page.numberOfElements()).isEqualTo(5);
        assertThat(page.totalElements()).isEqualTo(12L);
        assertThat(page.content()).first().extracting(Author::getName).isEqualTo("Author 06");
    }

    @Test
    void mixedInWithEqPredicate() {
        Author a = authors.save(newAuthor("Alpha"));
        Author b = authors.save(newAuthor("Alpha"));
        Author c = authors.save(newAuthor("Alpha"));
        Author d = authors.save(newAuthor("Beta"));

        List<Author> hits = authors.findByNameLikeAndIdIn("Alpha",
                List.of(a.getId(), b.getId(), d.getId()));
        assertThat(hits).hasSize(2)
                .extracting(Author::getId)
                .containsExactlyInAnyOrder(a.getId(), b.getId());
    }

    @Test
    void optimisticLockingThrowsOnStaleVersion() {
        Article art = new Article();
        art.setTitle("Concurrent");
        art.setVersion(0);
        articles.create(art);

        Article reader1 = articles.findById(art.getId()).orElseThrow();
        Article reader2 = articles.findById(art.getId()).orElseThrow();

        reader1.setTitle("first");
        articles.modify(reader1);

        reader2.setTitle("stale");
        assertThatThrownBy(() -> articles.modify(reader2))
                .isInstanceOf(OptimisticLockingFailureException.class);
    }

    @Test
    void cursorPaginationForwardWalk() {
        for (int i = 1; i <= 7; i++) authors.save(newAuthor("Cursor " + String.format("%02d", i)));

        var p1 = authors.findByNameLikeOrderByIdAsc("Cursor%",
                jakarta.data.page.PageRequest.ofSize(3));
        assertThat(p1.numberOfElements()).isEqualTo(3);
        assertThat(p1.content()).first().extracting(Author::getName).isEqualTo("Cursor 01");

        var p2 = authors.findByNameLikeOrderByIdAsc("Cursor%", p1.nextPageRequest());
        assertThat(p2.numberOfElements()).isEqualTo(3);
        assertThat(p2.content()).first().extracting(Author::getName).isEqualTo("Cursor 04");

        var p3 = authors.findByNameLikeOrderByIdAsc("Cursor%", p2.nextPageRequest());
        assertThat(p3.numberOfElements()).isEqualTo(1);
        assertThat(p3.hasNext()).isFalse();
    }

    private static Author newAuthor(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
