package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import jakarta.data.repository.BasicRepository;
import jakarta.data.repository.Repository;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * M7-1 — validates the runtime fallback path ({@link MansartData#runtimeRepository(Class)})
 * works for {@code BasicRepository} methods on an entity that's only reflection-described,
 * without any compile-time {@code _Author} metamodel or {@code AuthorImpl} class.
 *
 * <p>Reuses the existing {@link Author} entity (which DOES have a compile-time metamodel for
 * other tests, but the runtime path doesn't look at it — it builds its own EntityModel via
 * reflection on Author's annotations).
 */
class RuntimeRepositoryTest {

    /**
     * Repository interface declared inline so APT generates an Impl for it too — but the test
     * deliberately calls {@link MansartData#runtimeRepository} which IGNORES the generated Impl
     * and goes through the Proxy path, validating that the runtime engine produces the same
     * functional behaviour as the compile-time path for {@code BasicRepository} methods.
     */
    @Repository
    public interface RuntimeAuthorRepository extends BasicRepository<Author, Long> {
    }

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static RuntimeAuthorRepository runtimeRepo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-runtime;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        runtimeRepo = mansartData.runtimeRepository(RuntimeAuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
    }

    @Test
    void saveAssignsGeneratedId() {
        Author a = new Author();
        a.setName("Runtime Saved");
        Author saved = runtimeRepo.save(a);
        assertThat(saved.getId()).isNotNull().isPositive();
    }

    @Test
    void findByIdReturnsRoundTrip() {
        Author a = newAuthor("Runtime Found");
        Author saved = runtimeRepo.save(a);
        assertThat(runtimeRepo.findById(saved.getId()))
                .isPresent()
                .get().extracting(Author::getName).isEqualTo("Runtime Found");
    }

    @Test
    void findAllReturnsStream() {
        runtimeRepo.save(newAuthor("R1"));
        runtimeRepo.save(newAuthor("R2"));
        runtimeRepo.save(newAuthor("R3"));
        var names = runtimeRepo.findAll().map(Author::getName).toList();
        assertThat(names).hasSize(3).containsExactlyInAnyOrder("R1", "R2", "R3");
    }

    @Test
    void deleteByIdRemoves() {
        Author saved = runtimeRepo.save(newAuthor("To delete"));
        runtimeRepo.deleteById(saved.getId());
        assertThat(runtimeRepo.findById(saved.getId())).isEmpty();
    }

    @Test
    void deleteByEntityRemoves() {
        Author saved = runtimeRepo.save(newAuthor("Delete by entity"));
        runtimeRepo.delete(saved);
        assertThat(runtimeRepo.findById(saved.getId())).isEmpty();
    }

    private static Author newAuthor(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
