package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import jakarta.data.repository.BasicRepository;
import jakarta.data.repository.Repository;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * M7-1 — validates the runtime fallback path ({@link MansartData#runtimeRepository(Class)})
 * works for {@code BasicRepository} methods on an entity that's only reflection-described,
 * without any compile-time {@code _Author} metamodel or {@code AuthorImpl} class.
 *
 * <p>Reuses the existing {@link Author} entity (which DOES have a compile-time metamodel for
 * other tests, but the runtime path doesn't look at it — it builds its own EntityModel via
 * reflection on Author's annotations).
 */
class RuntimeRepositoryTest {

    /**
     * Repository interface declared inline so APT generates an Impl for it too — but the test
     * deliberately calls {@link MansartData#runtimeRepository} which IGNORES the generated Impl
     * and goes through the Proxy path, validating that the runtime engine produces the same
     * functional behaviour as the compile-time path for {@code BasicRepository} methods.
     */
    @Repository
    public interface RuntimeAuthorRepository extends BasicRepository<Author, Long> {

        long count();
        boolean existsById(Long id);

        // M7-2 — derived queries on the runtime path
        java.util.List<Author>     findByName(String name);
        java.util.List<Author>     findByNameLike(String pattern);
        java.util.Optional<Author> findOneByName(String name);
        long                       countByName(String name);
        boolean                    existsByName(String name);
        long                       deleteByName(String name);
        java.util.List<Author>     findByNameIn(java.util.List<String> names);
        java.util.List<Author>     findAllByOrderByNameAsc();

        // M7-3 — @Query JDQL on the runtime path. Uses ?N positional params because the
        // -parameters flag isn't reliably honoured by maven-compiler-plugin 4.0.0-beta-4 yet.
        @jakarta.data.repository.Query("FROM Author WHERE name = ?1")
        java.util.List<Author> jdqlByName(String name);

        @jakarta.data.repository.Query("SELECT COUNT(*) FROM Author WHERE name LIKE ?1")
        long jdqlCountLike(String pattern);

        @jakarta.data.repository.Query("UPDATE Author SET name = ?2 WHERE name = ?1")
        long jdqlRename(String oldName, String newName);

        @jakarta.data.repository.Query("DELETE FROM Author WHERE name LIKE ?1")
        long jdqlDeleteLike(String pattern);
    }

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static RuntimeAuthorRepository runtimeRepo;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-runtime;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        runtimeRepo = mansartData.runtimeRepository(RuntimeAuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
    }

    @Test
    void saveAssignsGeneratedId() {
        Author a = new Author();
        a.setName("Runtime Saved");
        Author saved = runtimeRepo.save(a);
        assertThat(saved.getId()).isNotNull().isPositive();
    }

    @Test
    void findByIdReturnsRoundTrip() {
        Author a = newAuthor("Runtime Found");
        Author saved = runtimeRepo.save(a);
        assertThat(runtimeRepo.findById(saved.getId()))
                .isPresent()
                .get().extracting(Author::getName).isEqualTo("Runtime Found");
    }

    @Test
    void findAllReturnsStream() {
        runtimeRepo.save(newAuthor("R1"));
        runtimeRepo.save(newAuthor("R2"));
        runtimeRepo.save(newAuthor("R3"));
        var names = runtimeRepo.findAll().map(Author::getName).toList();
        assertThat(names).hasSize(3).containsExactlyInAnyOrder("R1", "R2", "R3");
    }

    @Test
    void deleteByIdRemoves() {
        Author saved = runtimeRepo.save(newAuthor("To delete"));
        runtimeRepo.deleteById(saved.getId());
        assertThat(runtimeRepo.findById(saved.getId())).isEmpty();
    }

    @Test
    void deleteByEntityRemoves() {
        Author saved = runtimeRepo.save(newAuthor("Delete by entity"));
        runtimeRepo.delete(saved);
        assertThat(runtimeRepo.findById(saved.getId())).isEmpty();
    }

    /* ---- M7-2 derived query dispatchers via runtime proxy ---- */

    @Test
    void derivedFindByName() {
        runtimeRepo.save(newAuthor("Alpha"));
        runtimeRepo.save(newAuthor("Beta"));
        var hits = runtimeRepo.findByName("Beta");
        assertThat(hits).extracting(Author::getName).containsExactly("Beta");
    }

    @Test
    void derivedFindByNameLikeWithOrderBy() {
        runtimeRepo.save(newAuthor("Carl"));
        runtimeRepo.save(newAuthor("Charlie"));
        runtimeRepo.save(newAuthor("Dan"));
        var ordered = runtimeRepo.findAllByOrderByNameAsc();
        assertThat(ordered).extracting(Author::getName).containsExactly("Carl", "Charlie", "Dan");
    }

    @Test
    void derivedCountAndExistsAndDelete() {
        runtimeRepo.save(newAuthor("Eve"));
        runtimeRepo.save(newAuthor("Eve"));
        assertThat(runtimeRepo.countByName("Eve")).isEqualTo(2L);
        assertThat(runtimeRepo.existsByName("Eve")).isTrue();
        long deleted = runtimeRepo.deleteByName("Eve");
        assertThat(deleted).isEqualTo(2L);
        assertThat(runtimeRepo.existsByName("Eve")).isFalse();
    }

    @Test
    void derivedInWithCollectionAndEmpty() {
        runtimeRepo.save(newAuthor("Fred"));
        runtimeRepo.save(newAuthor("Greta"));
        runtimeRepo.save(newAuthor("Helen"));
        var hits = runtimeRepo.findByNameIn(java.util.List.of("Fred", "Helen"));
        assertThat(hits).extracting(Author::getName).containsExactlyInAnyOrder("Fred", "Helen");

        var empty = runtimeRepo.findByNameIn(java.util.List.of());
        assertThat(empty).isEmpty();
    }

    @Test
    void derivedFindOneOptional() {
        runtimeRepo.save(newAuthor("Iris"));
        assertThat(runtimeRepo.findOneByName("Iris"))
                .isPresent().get().extracting(Author::getName).isEqualTo("Iris");
        assertThat(runtimeRepo.findOneByName("Nope")).isEmpty();
    }

    /* ---- M7-3 @Query JDQL via runtime proxy ---- */

    @Test
    void jdqlSelectByName() {
        runtimeRepo.save(newAuthor("Jules"));
        runtimeRepo.save(newAuthor("Karl"));
        var hits = runtimeRepo.jdqlByName("Jules");
        assertThat(hits).extracting(Author::getName).containsExactly("Jules");
    }

    @Test
    void jdqlSelectCountLike() {
        runtimeRepo.save(newAuthor("L1"));
        runtimeRepo.save(newAuthor("L2"));
        runtimeRepo.save(newAuthor("M1"));
        assertThat(runtimeRepo.jdqlCountLike("L%")).isEqualTo(2L);
    }

    @Test
    void jdqlUpdateAndDelete() {
        runtimeRepo.save(newAuthor("Pre"));
        runtimeRepo.save(newAuthor("Pre"));
        long renamed = runtimeRepo.jdqlRename("Pre", "Post");
        assertThat(renamed).isEqualTo(2L);
        long deleted = runtimeRepo.jdqlDeleteLike("Pos%");
        assertThat(deleted).isEqualTo(2L);
        assertThat(runtimeRepo.count()).isZero();
    }

    private static Author newAuthor(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
