/*
 * Copyright (c) ${year} Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */

package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.ConnectionScope;
import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * MP-D — exercises {@link ConnectionScope#inTransaction(DataSource, ConnectionScope.TxAction)}
 * end-to-end through the runtime. Two operations enrolled in the same {@code inTransaction}
 * must share the same physical connection: an exception thrown inside the body must roll back
 * <i>both</i>, not leave the first save persisted.
 */
class TransactionScopeTest {

    private static DataSource           dataSource;
    private static MansartData          mansartData;
    private static AuthorRepository     authors;

    @BeforeAll
    static void initStack() {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-tx-scope;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource  = ds;
        mansartData = MansartData.builder().dataSource(ds).build();
        authors     = mansartData.repository(AuthorRepository.class);
    }

    @BeforeEach
    void resetSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
    }

    @Test
    void rollbackOnExceptionUndoesEarlierSavesInSameScope() {
        assertThatThrownBy(() -> ConnectionScope.inTransaction(dataSource, () -> {
            saveNew("Émile Zola");
            saveNew("Victor Hugo");
            throw new IllegalStateException("boom");
        })).isInstanceOf(IllegalStateException.class)
           .hasMessage("boom");

        assertThat(authors.count())
                .as("rollback must have undone BOTH saves enrolled in the failing transaction")
                .isZero();
    }

    @Test
    void commitOnNormalReturnPersistsAllSavesInScope() {
        ConnectionScope.inTransaction(dataSource, () -> {
            saveNew("Stendhal");
            saveNew("Flaubert");
        });
        assertThat(authors.count()).isEqualTo(2L);
    }

    @Test
    void implicitAutoCommitWhenNoTransactionWraps() {
        // No inTransaction wrap → each save commits immediately on its own auto-commit.
        // Chain a save then a deliberate failure: the first save MUST remain persisted
        // because there is no enclosing transaction to roll back.
        saveNew("Maupassant");
        assertThatThrownBy(() -> { throw new IllegalStateException("post-save failure"); })
                .isInstanceOf(IllegalStateException.class);
        assertThat(authors.count()).isEqualTo(1L);
    }

    @Test
    void nestedInTransactionJoinsOuter() {
        // Inner inTransaction must join the outer; failure inside the inner rolls back the outer too.
        assertThatThrownBy(() -> ConnectionScope.inTransaction(dataSource, () -> {
            saveNew("Outer-1");
            ConnectionScope.inTransaction(dataSource, () -> {
                saveNew("Inner-1");
                throw new IllegalStateException("inner boom");
            });
        })).isInstanceOf(IllegalStateException.class);

        assertThat(authors.count())
                .as("inner failure must roll back the joined outer transaction")
                .isZero();
    }

    @Test
    void inTransactionReturningValue() {
        long count = ConnectionScope.inTransaction(dataSource, () -> {
            saveNew("Beckett");
            return authors.count();
        });
        assertThat(count).isEqualTo(1L);
        // Persisted after commit:
        assertThat(authors.count()).isEqualTo(1L);
    }

    private static void saveNew(String name) {
        Author a = new Author();
        a.setName(name);
        authors.save(a);
    }
}
