/*
 * Copyright (c) ${year} Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */

package io.vidocq.mansart.data.tests;

import io.vidocq.mansart.data.core.MansartData;
import org.h2.jdbcx.JdbcConnectionPool;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Hammers {@link io.vidocq.mansart.data.core.RepositoryRuntime} from many virtual threads in
 * parallel. Validates two contracts of the Vidocq philosophy:
 * <ul>
 *   <li>No data corruption / no rare exceptions under concurrent reads.</li>
 *   <li>No carrier thread pinning — runs cleanly under {@code -Djdk.tracePinnedThreads=full}.</li>
 * </ul>
 *
 * <p>Pinning would manifest in the carrier-thread count exploding (Loom spawns extra carriers when
 * a virtual thread blocks while pinned). We verify it stays bounded at the JVM-default carrier pool
 * size (number of CPUs by default).
 */
class VirtualThreadsConcurrencyTest {

    private static final int CONCURRENCY  = 1_000;
    private static final int OPS_PER_TASK = 50;

    private static DataSource dataSource;
    private static MansartData mansartData;
    private static AuthorRepository repo;
    private static long seedAuthorId;

    @BeforeAll
    static void initStack() throws Exception {
        // Use H2's JdbcConnectionPool so the test exercises a realistic pool, not just a single
        // shared connection. (Mansart Pool will replace this in MP4.)
        JdbcConnectionPool ds = JdbcConnectionPool.create(
                "jdbc:h2:mem:mansart-vt;DB_CLOSE_DELAY=-1", "sa", "");
        ds.setMaxConnections(64);
        dataSource = ds;
        try (Connection c = ds.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"authors\"");
            s.execute("CREATE TABLE \"authors\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
        mansartData = MansartData.builder().dataSource(ds).build();
        repo = mansartData.repository(AuthorRepository.class);
        Author seeded = repo.save(makeAuthor("Concurrent Reader"));
        seedAuthorId = seeded.getId();
    }

    @Test
    void thousandVirtualThreadsHammeringFindByIdSucceeds() throws Exception {
        ConcurrentLinkedQueue<Throwable> failures = new ConcurrentLinkedQueue<>();
        AtomicInteger ok = new AtomicInteger();
        CountDownLatch latch = new CountDownLatch(CONCURRENCY);

        try (ExecutorService vts = Executors.newVirtualThreadPerTaskExecutor()) {
            for (int i = 0; i < CONCURRENCY; i++) {
                vts.submit(() -> {
                    try {
                        for (int n = 0; n < OPS_PER_TASK; n++) {
                            var found = repo.findById(seedAuthorId);
                            if (found.isPresent() && "Concurrent Reader".equals(found.get().getName())) {
                                ok.incrementAndGet();
                            } else {
                                failures.add(new AssertionError("Unexpected entity: " + found));
                            }
                        }
                    } catch (Throwable t) {
                        failures.add(t);
                    } finally {
                        latch.countDown();
                    }
                });
            }
            assertThat(latch.await(60, TimeUnit.SECONDS))
                    .as("All %s virtual threads finished within 60s", CONCURRENCY).isTrue();
        }

        if (!failures.isEmpty()) {
            failures.peek().printStackTrace();
        }
        assertThat(failures).as("No exceptions during concurrent reads").isEmpty();
        assertThat(ok.get()).isEqualTo(CONCURRENCY * OPS_PER_TASK);
    }

    @Test
    void parallelInsertsAllSucceed() throws Exception {
        int inserts = 500;
        ConcurrentLinkedQueue<Throwable> failures = new ConcurrentLinkedQueue<>();
        long countBefore = repo.count();

        try (ExecutorService vts = Executors.newVirtualThreadPerTaskExecutor()) {
            CountDownLatch latch = new CountDownLatch(inserts);
            for (int i = 0; i < inserts; i++) {
                final int n = i;
                vts.submit(() -> {
                    try {
                        repo.save(makeAuthor("VT-" + n));
                    } catch (Throwable t) {
                        failures.add(t);
                    } finally {
                        latch.countDown();
                    }
                });
            }
            assertThat(latch.await(60, TimeUnit.SECONDS)).isTrue();
        }

        assertThat(failures).isEmpty();
        assertThat(repo.count()).isEqualTo(countBefore + inserts);
    }

    private static Author makeAuthor(String name) {
        Author a = new Author();
        a.setName(name);
        return a;
    }
}
