package io.vidocq.mansart.transactions.jpmsit;

import io.vidocq.mansart.transactions.cdi.MansartTransactionsProducer;
import io.vidocq.mansart.transactions.cdi.TransactionalInterceptor;
import io.vidocq.mansart.transactions.cdi.TransactionalInterceptorRequiresNew;
import io.vidocq.vauban.core.container.VaubanContainer;
import jakarta.transaction.Status;
import jakarta.transaction.TransactionManager;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Runs on the MODULE PATH (this is a named module with a {@code module-info}). It boots a Vauban
 * container programmatically and obtains the {@code @Transactional} bean via {@link
 * VaubanContainer#select(Class)} — deliberately NOT through {@code @Inject} into the test instance,
 * so nothing reflects into the test class and the module needs no {@code opens}.
 *
 * <p>What this proves, that a class-path test cannot: the {@code @Transactional} interception fires
 * on a strict module path with a BUILD-TIME generated {@code $$Intercepted} subclass, where the
 * application bean ({@link TxService}, in <em>this</em> module) is instantiated and field-injected by
 * its generated {@code VaubanComponentProvider} with no {@code opens} at all.</p>
 *
 * <p><strong>Known residual:</strong> the {@code @Transactional} interceptor classes (in
 * mansart-transactions-cdi) are still instantiated reflectively — the Vauban APT does not yet emit
 * {@code @Interceptor} classes into {@code _VaubanComponents} — so that module keeps a single
 * qualified {@code opens … to io.vidocq.vauban.core}. This test passes through that residual; it
 * becomes a true end-to-end zero-opens proof once the APT emits interceptors as components.</p>
 */
class TxModulePathTest {

    @Test
    void intercepts_transactional_on_the_module_path_with_a_build_time_subclass() throws Exception {
        VaubanContainer container = VaubanContainer.builder()
                .addBeanClass(MansartTransactionsProducer.class)
                .addBeanClass(TransactionalInterceptor.class)
                .addBeanClass(TransactionalInterceptorRequiresNew.class)
                .addBeanClass(TxService.class)
                .build();
        try {
            // The $$Intercepted subclass is a BUILD-TIME class (generated by the APT, present in this
            // module's jar), not a subclass spun at runtime — it is loadable by name.
            assertNotNull(
                    Class.forName("io.vidocq.mansart.transactions.jpmsit.TxService$$Intercepted"),
                    "the APT must have generated TxService$$Intercepted at build time");

            TransactionManager tm = container.select(TransactionManager.class);
            TxService svc = container.select(TxService.class);

            // REQUIRED with no active TX: the interceptor must start a TX around the call and clear it after.
            assertEquals(Status.STATUS_NO_TRANSACTION, tm.getStatus());
            boolean[] sawActiveTx = {false};
            svc.required(() -> sawActiveTx[0] = tm.getStatus() == Status.STATUS_ACTIVE);
            assertTrue(sawActiveTx[0],
                    "the @Transactional(REQUIRED) interceptor must start a TX inside the method");
            assertEquals(Status.STATUS_NO_TRANSACTION, tm.getStatus(),
                    "the interceptor must commit/clear the TX after the method returns");

            // REQUIRES_NEW nested in an active TX: a distinct inner TX must run, then the outer resumes.
            tm.begin();
            int outer = System.identityHashCode(tm.getTransaction());
            int[] inner = {outer};
            svc.requiresNew(() -> inner[0] = System.identityHashCode(tm.getTransaction()));
            assertTrue(inner[0] != outer, "REQUIRES_NEW must suspend the outer TX and start a new one");
            assertEquals(outer, System.identityHashCode(tm.getTransaction()),
                    "the outer TX must be resumed after REQUIRES_NEW returns");
            tm.commit();
        } finally {
            container.close();
        }
    }
}
