/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
/**
 * The Mansart Jakarta Persistence 3.2 provider. It is published through {@link java.util.ServiceLoader}. Applications
 * only see the {@code jakarta.persistence} API, plus, when they compile with {@code mansart-jpa-processor}, the SPI that
 * the generated accesses implement ({@code io.vidocq.mansart.jpa.core.spi}); no {@code requires} needs to be
 * transitive. Nothing is opened: the entity packages are reached either through the accesses an application provides,
 * or, for classes compiled without the processor, because the application opens their packages to this module.
 */
// "module": the qualified exports name io.vidocq.mansart.jpa.processor, built after this module
@SuppressWarnings("module")
module io.vidocq.mansart.jpa.core {
    requires jakarta.persistence;
    requires static jakarta.validation;
    requires java.sql;
    requires java.xml;
    requires io.vidocq.mansart.jpa.dialect.spi;
    requires io.vidocq.mansart.pool.core;

    // the SPI that the accesses generated by mansart-jpa-processor implement and are handed over with
    exports io.vidocq.mansart.jpa.core.spi;
    uses io.vidocq.mansart.jpa.core.spi.ManagedAccessProvider;
    uses io.vidocq.mansart.jpa.dialect.DialectFactory;
    uses jakarta.validation.spi.ValidationProvider;

    // the processor plans the generated accesses with the same code as the bootstrap (AccessPlanner)
    exports io.vidocq.mansart.jpa.core.model to io.vidocq.mansart.jpa.processor;
    exports io.vidocq.mansart.jpa.core.model.source to io.vidocq.mansart.jpa.processor;
    exports io.vidocq.mansart.jpa.core.model.build to io.vidocq.mansart.jpa.processor;

    provides jakarta.persistence.spi.PersistenceProvider
        with io.vidocq.mansart.jpa.core.MansartPersistenceProvider;
}
