<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.vidocq.mansart</groupId>
    <artifactId>mansart-persistence-tck</artifactId>
    <version>0.3.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Mansart :: Persistence :: TCK</name>
    <description>OUT OF REACTOR - Official Jakarta Persistence 3.2 TCK runner for Mansart implementation.</description>
    <url>https://codefloe.com/Vidocq/mansart</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <jakarta.persistence.version>3.2.0</jakarta.persistence.version>
        <h2.version>2.3.232</h2.version>
        <tck.database>h2</tck.database>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.vidocq.mansart</groupId>
            <artifactId>mansart-persistence-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2.version}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <version>${jakarta.persistence.version}</version>
        </dependency>
    </dependencies>
</project>
