/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.jpa.core.context;

import io.vidocq.mansart.jpa.core.mapping.MappedEntity;

/**
 * An instance of a persistence context, and where it stands in its life cycle (§3.2): managed or removed, with or
 * without its row in the database yet. Owned by one persistence context, hence one thread at a time (§7.2).
 */
public final class ManagedEntity {

    /** The states of §3.2 an instance has while the context holds it; new and detached instances are outside. */
    public enum Status {
        MANAGED, REMOVED
    }

    private final Object instance;
    private final MappedEntity type;
    private final long sequence;
    private EntityKey key;
    private Status status;
    private boolean inserted;
    private Object[] snapshot;

    ManagedEntity(Object instance, MappedEntity type, long sequence, EntityKey key, Status status, boolean inserted,
            Object[] snapshot) {
        this.instance = instance;
        this.type = type;
        this.sequence = sequence;
        this.key = key;
        this.status = status;
        this.inserted = inserted;
        this.snapshot = snapshot;
    }

    public Object instance() {
        return instance;
    }

    public MappedEntity type() {
        return type;
    }

    /** The order in which the context met the instance: inserts follow it. */
    public long sequence() {
        return sequence;
    }

    /** The identity, or {@code null} while the identifier is generated by the insert. */
    public EntityKey key() {
        return key;
    }

    public Status status() {
        return status;
    }

    /** Whether the row exists: loaded, or inserted by a flush. */
    public boolean inserted() {
        return inserted;
    }

    /** The state at load or at the last flush, compared at the next flush; {@code null} before the insert. */
    public Object[] snapshot() {
        return snapshot;
    }

    void key(EntityKey key) {
        this.key = key;
    }

    void status(Status status) {
        this.status = status;
    }

    void inserted(boolean inserted) {
        this.inserted = inserted;
    }

    void snapshot(Object[] snapshot) {
        this.snapshot = snapshot;
    }
}
