/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.jpa.core.context;

import io.vidocq.mansart.jpa.core.mapping.MappedEntity;
import jakarta.persistence.EntityExistsException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * A persistence context (§3.3, §7.2): at most one managed instance per identity, and the state of each instance in
 * its life cycle. It knows nothing of the database: the entity operations (P4) and the flush engine drive it. Not
 * thread-safe, as an entity manager is not (§7.2): no lock, no {@code ThreadLocal}.
 */
public final class PersistenceContext {

    private final Map<EntityKey, ManagedEntity> byKey = new HashMap<>();
    /** By instance, compared by identity, in the order the context met them: the flush follows it without sorting. */
    private final Map<Instance, ManagedEntity> byInstance = new LinkedHashMap<>();
    private long sequence;

    /**
     * Makes {@code instance} managed (§3.2.2): a new instance awaits its insert, a removed one becomes managed again, a
     * managed one is left as it is. Another instance with the same identity is an {@link EntityExistsException}.
     */
    public ManagedEntity persist(Object instance, MappedEntity type) {
        ManagedEntity known = byInstance.get(new Instance(instance));
        if (known != null) {
            known.status(ManagedEntity.Status.MANAGED);
            return known;
        }
        EntityKey key = key(type, type.id(instance));
        if (key != null && byKey.containsKey(key)) {
            throw new EntityExistsException("Another instance of " + type.model().entityName() + " with the identifier "
                + key.id() + " is already managed by this persistence context");
        }
        return register(new ManagedEntity(instance, type, sequence++, key, ManagedEntity.Status.MANAGED, false, null));
    }

    /**
     * Makes a row read from the database managed, with its state as snapshot; if the context already manages its
     * identity, the managed instance stays and is returned (§3.2.8: one managed instance per identity).
     */
    public ManagedEntity loaded(Object instance, MappedEntity type, Object[] state) {
        EntityKey key = key(type, type.id(instance));
        if (key == null) {
            throw new IllegalArgumentException("A loaded instance of " + type.model().entityName() + " has no identifier");
        }
        ManagedEntity known = byKey.get(key);
        if (known != null) {
            return known;
        }
        return register(new ManagedEntity(instance, type, sequence++, key, ManagedEntity.Status.MANAGED, true, state.clone()));
    }

    /** Records the insert of {@code entry}: its identity, generated by the insert or not, and its state as snapshot. */
    public void inserted(ManagedEntity entry, Object id, Object[] state) {
        if (entry.key() == null) {
            EntityKey key = key(entry.type(), id);
            if (byKey.putIfAbsent(key, entry) != null) {
                throw new EntityExistsException("The database generated the identifier " + id + " of "
                    + entry.type().model().entityName() + " for two instances");
            }
            entry.key(key);
        }
        entry.inserted(true);
        entry.snapshot(state.clone());
    }

    /** Records an update: the state written becomes the snapshot. */
    public void updated(ManagedEntity entry, Object[] state) {
        entry.snapshot(state.clone());
    }

    /** Forgets an instance whose row was deleted, or that was removed before it was inserted. */
    public void deleted(ManagedEntity entry) {
        forget(entry);
    }

    /**
     * Makes a managed instance removed (§3.2.3); a removed one stays removed. {@code false} if the context does not hold
     * the instance: it is new or detached, which the entity operations tell apart.
     */
    public boolean remove(Object instance) {
        ManagedEntity known = byInstance.get(new Instance(instance));
        if (known == null) {
            return false;
        }
        known.status(ManagedEntity.Status.REMOVED);
        return true;
    }

    /** §3.2.8: whether {@code instance} is managed; a removed instance is not. */
    public boolean contains(Object instance) {
        ManagedEntity known = byInstance.get(new Instance(instance));
        return known != null && known.status() == ManagedEntity.Status.MANAGED;
    }

    /** The entry of {@code instance}, managed or removed. */
    public Optional<ManagedEntity> entry(Object instance) {
        return Optional.ofNullable(byInstance.get(new Instance(instance)));
    }

    /** The entry with this identity, managed or removed. */
    public Optional<ManagedEntity> find(EntityKey key) {
        return Optional.ofNullable(byKey.get(key));
    }

    /** §3.2.7: detaches one instance; changes not flushed are lost. */
    public void detach(Object instance) {
        ManagedEntity known = byInstance.get(new Instance(instance));
        if (known != null) {
            forget(known);
        }
    }

    /** §3.2.7: detaches every instance. */
    public void clear() {
        byKey.clear();
        byInstance.clear();
    }

    /** The entries, in the order the context met their instances. */
    public List<ManagedEntity> entries() {
        return new ArrayList<>(byInstance.values());
    }

    /** How many instances the context holds. */
    public int size() {
        return byInstance.size();
    }

    private ManagedEntity register(ManagedEntity entry) {
        byInstance.put(new Instance(entry.instance()), entry);
        if (entry.key() != null) {
            byKey.put(entry.key(), entry);
        }
        return entry;
    }

    private void forget(ManagedEntity entry) {
        byInstance.remove(new Instance(entry.instance()));
        if (entry.key() != null) {
            byKey.remove(entry.key(), entry);
        }
    }

    /** An instance as a map key: entities may define equals and hashCode, a persistence context compares identities. */
    private record Instance(Object instance) {
        @Override
        public boolean equals(Object other) {
            return other instanceof Instance that && that.instance == instance;
        }

        @Override
        public int hashCode() {
            return System.identityHashCode(instance);
        }
    }

    private static EntityKey key(MappedEntity type, Object id) {
        return id == null ? null : new EntityKey(type.root(), id);
    }
}
