#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SPEC="${1:-}"
if [[ ! "$SPEC" =~ ^[A-Z]{3}$ ]]; then
    echo "usage: scripts/opencode-harness/update-status.sh <SPEC>" >&2
    exit 2
fi

TASKROOT="$ROOT/tasks/$SPEC"
STATUS="$TASKROOT/STATUS.md"
if [[ ! -d "$TASKROOT" ]]; then
    echo "task directory not found: tasks/$SPEC" >&2
    exit 3
fi

total=$(find "$TASKROOT" -mindepth 2 -type f -name "$SPEC-M*-T*.md" -print | wc -l | tr -d ' ')
done_count=0
while read -r card; do
    [[ -z "$card" ]] && continue
    status=$(awk -F: '/^status:/ {gsub(/[[:space:]]/, "", $2); print toupper($2); exit}' "$card")
    if [[ "$status" == "DONE" ]]; then ((done_count+=1)); fi
done < <(find "$TASKROOT" -mindepth 2 -type f -name "$SPEC-M*-T*.md" -print | sort)

percent() {
    local n="$1" d="$2"
    if (( d == 0 )); then printf '0'; else awk -v n="$n" -v d="$d" 'BEGIN { printf "%.0f", (n*100)/d }'; fi
}

{
    printf '# %s implementation status\n\n' "$SPEC"
    printf '> Generated by `scripts/opencode-harness/update-status.sh %s`. Edit card `status:` fields, then regenerate.\n\n' "$SPEC"
    printf '**Global progress: %s%% (%d/%d tasks done)**\n\n' "$(percent "$done_count" "$total")" "$done_count" "$total"
    printf '| Milestone | Done | Total | Progress |\n|---|---:|---:|---:|\n'
    find "$TASKROOT" -mindepth 1 -maxdepth 1 -type d -name 'M[0-9]*' -print | sort | while read -r milestone; do
        ms_total=$(find "$milestone" -maxdepth 1 -type f -name "$SPEC-$(basename "$milestone")-T*.md" -print | wc -l | tr -d ' ')
        ms_done=0
        while read -r card; do
            [[ -z "$card" ]] && continue
            status=$(awk -F: '/^status:/ {gsub(/[[:space:]]/, "", $2); print toupper($2); exit}' "$card")
            if [[ "$status" == "DONE" ]]; then ((ms_done+=1)); fi
        done < <(find "$milestone" -maxdepth 1 -type f -name "$SPEC-$(basename "$milestone")-T*.md" -print)
        printf '| %s | %d | %d | %s%% |\n' "$(basename "$milestone")" "$ms_done" "$ms_total" "$(percent "$ms_done" "$ms_total")"
    done
    printf '\n## Task ledger\n\n| ID | Status | Card |\n|---|---|---|\n'
    while read -r card; do
        [[ -z "$card" ]] && continue
        id=$(awk -F: '/^id:/ {gsub(/[[:space:]]/, "", $2); print $2; exit}' "$card")
        status=$(awk -F: '/^status:/ {gsub(/[[:space:]]/, "", $2); print toupper($2); exit}' "$card")
        printf '| %s | %s | [%s](%s) |\n' "$id" "$status" "$(basename "$card")" "${card#$TASKROOT/}"
    done < <(find "$TASKROOT" -mindepth 2 -type f -name "$SPEC-M*-T*.md" -print | sort)
} > "$STATUS"
printf 'generated: %s\n' "${STATUS#$ROOT/}"
