/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.jpa.processor;

import io.vidocq.mansart.jpa.core.model.AccessKind;
import io.vidocq.mansart.jpa.core.model.build.AccessPlanner.Member;
import io.vidocq.mansart.jpa.core.model.source.ClassInfo;
import io.vidocq.mansart.jpa.core.model.source.FieldInfo;
import io.vidocq.mansart.jpa.core.model.source.MethodInfo;
import java.lang.classfile.ClassFile;
import java.lang.constant.ClassDesc;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.SortedSet;
import java.util.TreeSet;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.ElementFilter;
import javax.lang.model.util.Elements;

/**
 * Writes the source of the access of one managed class: a {@code ManagedAccess} in the package of the class, which
 * reaches each member directly when the language lets it (public members, non-private members of the same package),
 * and through a method handle otherwise. The handles come from the generated class's own lookup, through
 * {@code privateLookupIn} on a class of the same module, so the package need not be opened; they are {@code static
 * final}, constants for the JIT.
 */
final class AccessWriter {

    /** Why a class gets no generated access; the bootstrap then generates it. */
    static final class Unsupported extends Exception {
        Unsupported(String message) {
            super(message, null, false, false);
        }
    }

    private final Elements elements;
    private final ElementInfos infos;

    AccessWriter(Elements elements, ElementInfos infos) {
        this.elements = elements;
        this.infos = infos;
    }

    /** One persistent member and how the generated code reaches it. */
    private record Slot(Member member, String type, boolean directGet, boolean directSet, String getter, String setter, int depth) {
    }

    /**
     * The source of the access of {@code type}.
     *
     * @param className the simple name of the generated class
     * @param record whether {@code type} is a record, built through its canonical constructor
     */
    String write(TypeElement type, String className, List<Member> members, boolean record) throws Unsupported {
        String pkg = packageOf(type);
        String self = qualified(type);
        if (!referenceable(type, pkg)) {
            throw new Unsupported(self + " cannot be named from its own package");
        }
        List<Slot> slots = new ArrayList<>();
        for (Member member : members) {
            slots.add(slot(type, member, pkg, record));
        }
        StringBuilder out = new StringBuilder();
        out.append("// Generated by mansart-jpa-processor from ").append(self).append(": do not edit.\n");
        out.append("package ").append(pkg).append(";\n\n");
        out.append("@SuppressWarnings({\"unchecked\", \"rawtypes\"})\n");
        out.append("final class ").append(className).append(" extends io.vidocq.mansart.jpa.core.spi.ManagedAccess {\n\n");
        handles(out, type, slots, record);
        out.append("    ").append(className).append("() {\n");
        out.append("        super(").append(self).append(".class, java.util.List.of(");
        for (int i = 0; i < slots.size(); i++) {
            Member member = slots.get(i).member();
            out.append(i == 0 ? "" : ", ").append('"').append(member.name()).append(':').append(member.access()).append('"');
        }
        out.append("));\n    }\n");
        if (record) {
            construct(out, self, slots);
        } else {
            instantiate(out, type, self, pkg);
        }
        get(out, self, slots);
        if (!record) {
            set(out, self, slots);
        }
        out.append("}\n");
        return out.toString();
    }

    private Slot slot(TypeElement type, Member member, String pkg, boolean record) throws Unsupported {
        ClassInfo owner = member.owner();
        String ownerPackage = owner.name().contains(".") ? owner.name().substring(0, owner.name().lastIndexOf('.')) : "";
        boolean samePackage = ownerPackage.equals(pkg);
        String typeName = sourceName(member.type(), pkg);
        int depth = depth(type, owner);
        TypeElement ownerElement = infos.element(owner.name());
        boolean sameModule = elements.getModuleOf(ownerElement).equals(elements.getModuleOf(type));
        if (record) {
            // record components: their accessor is public, and the record cannot be written
            return new Slot(member, typeName, true, true, member.name(), null, depth);
        }
        if (member.access() == AccessKind.FIELD) {
            FieldInfo field = (FieldInfo) member.element();
            boolean direct = visible(field.flags(), samePackage);
            if (!direct && !sameModule) {
                throw new Unsupported("the field " + member.name() + " of " + owner.name() + " belongs to another module");
            }
            return new Slot(member, typeName, direct, direct, member.name(), member.name(), depth);
        }
        MethodInfo getter = (MethodInfo) member.element();
        MethodInfo setter = setter(owner, getter, member.name())
            .orElseThrow(() -> new Unsupported("the property " + member.name() + " of " + owner.name() + " has no setter"));
        boolean directGet = visible(getter.flags(), samePackage);
        boolean directSet = visible(setter.flags(), samePackage);
        if ((!directGet || !directSet) && !sameModule) {
            throw new Unsupported("the property " + member.name() + " of " + owner.name() + " belongs to another module");
        }
        return new Slot(member, typeName, directGet, directSet, getter.name(), setter.name(), depth);
    }

    /** Reachable by the language from a class of the package of the managed class. */
    private static boolean visible(int flags, boolean samePackage) {
        return (flags & ClassFile.ACC_PUBLIC) != 0 || (samePackage && (flags & ClassFile.ACC_PRIVATE) == 0);
    }

    private static Optional<MethodInfo> setter(ClassInfo owner, MethodInfo getter, String property) {
        String setter = "set" + Character.toUpperCase(property.charAt(0)) + property.substring(1);
        String alternative = "set" + property;
        ClassDesc type = getter.type().returnType();
        return owner.methods().stream().filter(m -> (m.name().equals(setter) || m.name().equals(alternative)) && !m.isStatic()
            && m.type().parameterCount() == 1 && m.type().parameterType(0).equals(type)).findFirst();
    }

    /** How many {@code getSuperclass()} lead from {@code type} to {@code owner}. */
    private int depth(TypeElement type, ClassInfo owner) throws Unsupported {
        String current = elements.getBinaryName(type).toString();
        int depth = 0;
        while (!current.equals(owner.name())) {
            ClassInfo info = infos.read(current).orElseThrow(() -> new Unsupported("the superclass chain of " + type + " cannot be read"));
            current = info.superclassName();
            depth++;
            if (current == null) {
                throw new Unsupported(owner.name() + " is not a superclass of " + type);
            }
        }
        return depth;
    }

    // ---- members ------------------------------------------------------------------------------------------

    private static String classOf(String self, int depth) {
        return self + ".class" + ".getSuperclass()".repeat(depth);
    }

    private void handles(StringBuilder out, TypeElement type, List<Slot> slots, boolean record) {
        boolean constructor = !record && privateConstructor(type);
        boolean any = !record && (slots.stream().anyMatch(s -> !s.directGet() || !s.directSet()) || constructor);
        if (!any) {
            return;
        }
        String self = qualified(type);
        for (int i = 0; i < slots.size(); i++) {
            Slot slot = slots.get(i);
            if (!slot.directGet()) {
                out.append("    private static final java.lang.invoke.MethodHandle GET_").append(i).append(";\n");
            }
            if (!slot.directSet()) {
                out.append("    private static final java.lang.invoke.MethodHandle SET_").append(i).append(";\n");
            }
        }
        if (constructor) {
            out.append("    private static final java.lang.invoke.MethodHandle NEW;\n");
        }
        out.append("\n    static {\n");
        out.append("        java.lang.invoke.MethodHandles.Lookup own = java.lang.invoke.MethodHandles.lookup();\n");
        out.append("        java.lang.invoke.MethodType getter = java.lang.invoke.MethodType.methodType(Object.class, Object.class);\n");
        out.append("        java.lang.invoke.MethodType setter = java.lang.invoke.MethodType.methodType(void.class, Object.class, Object.class);\n");
        out.append("        try {\n");
        SortedSet<Integer> depths = new TreeSet<>();
        for (Slot slot : slots) {
            if (!slot.directGet() || !slot.directSet()) {
                depths.add(slot.depth());
            }
        }
        if (constructor) {
            depths.add(0);
        }
        for (int depth : depths) {
            out.append("            java.lang.invoke.MethodHandles.Lookup in").append(depth)
                .append(" = java.lang.invoke.MethodHandles.privateLookupIn(").append(classOf(self, depth)).append(", own);\n");
        }
        for (int i = 0; i < slots.size(); i++) {
            Slot slot = slots.get(i);
            if (slot.directGet() && slot.directSet()) {
                continue;
            }
            String owner = classOf(self, slot.depth());
            String lookup = "in" + slot.depth();
            String typeClass = erasedClassLiteral(slot.member().type());
            boolean field = slot.member().access() == AccessKind.FIELD;
            if (!slot.directGet()) {
                out.append("            GET_").append(i).append(" = ").append(lookup).append(field
                    ? ".findGetter(" + owner + ", \"" + slot.getter() + "\", " + typeClass + ")"
                    : ".findVirtual(" + owner + ", \"" + slot.getter() + "\", java.lang.invoke.MethodType.methodType(" + typeClass + "))")
                    .append(".asType(getter);\n");
            }
            if (!slot.directSet()) {
                out.append("            SET_").append(i).append(" = ").append(lookup).append(field
                    ? ".findSetter(" + owner + ", \"" + slot.setter() + "\", " + typeClass + ")"
                    : ".findVirtual(" + owner + ", \"" + slot.setter() + "\", java.lang.invoke.MethodType.methodType(void.class, "
                        + typeClass + "))")
                    .append(".asType(setter);\n");
            }
        }
        if (constructor) {
            out.append("            NEW = in0.findConstructor(").append(self).append(".class, java.lang.invoke.MethodType.methodType(void.class))")
                .append(".asType(java.lang.invoke.MethodType.methodType(Object.class));\n");
        }
        out.append("        } catch (ReflectiveOperationException failure) {\n");
        out.append("            throw new ExceptionInInitializerError(failure);\n");
        out.append("        }\n    }\n\n");
    }

    private void instantiate(StringBuilder out, TypeElement type, String self, String pkg) {
        if (type.getModifiers().contains(Modifier.ABSTRACT) || !constructorVisible(type) && !privateConstructor(type)) {
            return;
        }
        out.append("\n    @Override\n    public Object instantiate() {\n");
        if (constructorVisible(type)) {
            out.append("        return new ").append(self).append("();\n");
        } else {
            out.append("        try {\n            return NEW.invokeExact();\n        } catch (Throwable failure) {\n")
                .append("            throw rethrow(failure);\n        }\n");
        }
        out.append("    }\n");
    }

    /** A no-arg constructor that {@code new} can call from the package: any but a private one. */
    private boolean constructorVisible(TypeElement type) {
        return ElementFilter.constructorsIn(type.getEnclosedElements()).stream()
            .anyMatch(c -> c.getParameters().isEmpty() && !c.getModifiers().contains(Modifier.PRIVATE));
    }

    /** A private no-arg constructor, reached through a handle, of a concrete class. */
    private static boolean privateConstructor(TypeElement type) {
        return !type.getModifiers().contains(Modifier.ABSTRACT) && ElementFilter.constructorsIn(type.getEnclosedElements()).stream()
            .anyMatch(c -> c.getParameters().isEmpty() && c.getModifiers().contains(Modifier.PRIVATE));
    }

    private static void construct(StringBuilder out, String self, List<Slot> slots) {
        out.append("\n    @Override\n    public Object construct(Object... components) {\n");
        out.append("        return new ").append(self).append('(');
        for (int i = 0; i < slots.size(); i++) {
            out.append(i == 0 ? "" : ", ").append('(').append(slots.get(i).type()).append(") components[").append(i).append(']');
        }
        out.append(");\n    }\n");
    }

    private static void get(StringBuilder out, String self, List<Slot> slots) {
        out.append("\n    @Override\n    public Object get(Object instance, int attribute) {\n");
        out.append("        ").append(self).append(" entity = (").append(self).append(") instance;\n");
        out.append("        try {\n            return switch (attribute) {\n");
        for (int i = 0; i < slots.size(); i++) {
            Slot slot = slots.get(i);
            out.append("                case ").append(i).append(" -> ");
            if (!slot.directGet()) {
                out.append("GET_").append(i).append(".invokeExact(instance);\n");
            } else if (slot.member().access() == AccessKind.FIELD && slot.setter() != null) {
                out.append("entity.").append(slot.getter()).append(";\n");
            } else {
                out.append("entity.").append(slot.getter()).append("();\n");
            }
        }
        out.append("                default -> throw new IndexOutOfBoundsException(attribute);\n");
        out.append("            };\n        } catch (Throwable failure) {\n            throw rethrow(failure);\n        }\n    }\n");
    }

    private static void set(StringBuilder out, String self, List<Slot> slots) {
        out.append("\n    @Override\n    public void set(Object instance, int attribute, Object value) {\n");
        out.append("        ").append(self).append(" entity = (").append(self).append(") instance;\n");
        out.append("        try {\n            switch (attribute) {\n");
        for (int i = 0; i < slots.size(); i++) {
            Slot slot = slots.get(i);
            out.append("                case ").append(i).append(" -> ");
            if (!slot.directSet()) {
                out.append("SET_").append(i).append(".invokeExact(instance, value);\n");
            } else if (slot.member().access() == AccessKind.FIELD) {
                out.append("entity.").append(slot.setter()).append(" = (").append(slot.type()).append(") value;\n");
            } else {
                out.append("entity.").append(slot.setter()).append("((").append(slot.type()).append(") value);\n");
            }
        }
        out.append("                default -> throw new IndexOutOfBoundsException(attribute);\n");
        out.append("            }\n        } catch (Throwable failure) {\n            throw rethrow(failure);\n        }\n    }\n");
    }

    // ---- names --------------------------------------------------------------------------------------------

    static String packageOf(TypeElement type) {
        Element enclosing = type;
        while (!(enclosing instanceof PackageElement)) {
            enclosing = enclosing.getEnclosingElement();
        }
        return ((PackageElement) enclosing).getQualifiedName().toString();
    }

    private static String qualified(TypeElement type) {
        return type.getQualifiedName().toString();
    }

    /** The source name of the erasure of a member type, for a cast; a primitive is cast through its wrapper. */
    private String sourceName(ClassDesc desc, String pkg) throws Unsupported {
        if (desc.isPrimitive()) {
            return switch (desc.descriptorString()) {
                case "Z" -> "java.lang.Boolean";
                case "B" -> "java.lang.Byte";
                case "S" -> "java.lang.Short";
                case "C" -> "java.lang.Character";
                case "I" -> "java.lang.Integer";
                case "J" -> "java.lang.Long";
                case "F" -> "java.lang.Float";
                default -> "java.lang.Double";
            };
        }
        if (desc.isArray()) {
            ClassDesc component = desc.componentType();
            return (component.isPrimitive() ? primitive(component) : sourceName(component, pkg)) + "[]";
        }
        TypeElement element = infos.element(binaryName(desc));
        if (element == null || !referenceable(element, pkg)) {
            throw new Unsupported("the type " + desc.displayName() + " cannot be named from " + pkg);
        }
        return qualified(element);
    }

    /** {@code T.class} for the erasure of a member type, as {@code findGetter} wants it. */
    private String erasedClassLiteral(ClassDesc desc) {
        if (desc.isPrimitive()) {
            return primitive(desc) + ".class";
        }
        if (desc.isArray()) {
            return erasedClassLiteral(desc.componentType()).replace(".class", "[].class");
        }
        return qualified(infos.element(binaryName(desc))) + ".class";
    }

    private static String primitive(ClassDesc desc) {
        return switch (desc.descriptorString()) {
            case "Z" -> "boolean";
            case "B" -> "byte";
            case "S" -> "short";
            case "C" -> "char";
            case "I" -> "int";
            case "J" -> "long";
            case "F" -> "float";
            default -> "double";
        };
    }

    private static String binaryName(ClassDesc desc) {
        String descriptor = desc.descriptorString();
        return descriptor.substring(1, descriptor.length() - 1).replace('/', '.');
    }

    /** Whether a class of package {@code pkg} can name {@code type}: every enclosing class public, or package-visible. */
    private static boolean referenceable(TypeElement type, String pkg) {
        boolean samePackage = packageOf(type).equals(pkg);
        for (Element current = type; current instanceof TypeElement; current = current.getEnclosingElement()) {
            if (current.getModifiers().contains(Modifier.PRIVATE)) {
                return false;
            }
            if (!samePackage && !current.getModifiers().contains(Modifier.PUBLIC)) {
                return false;
            }
        }
        return true;
    }

    static boolean isRecord(TypeElement type) {
        return type.getKind() == ElementKind.RECORD;
    }
}
