/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.jpa.processor;

import io.vidocq.mansart.jpa.core.model.build.AccessPlanner;
import io.vidocq.mansart.jpa.core.model.source.MethodInfo;
import java.io.IOException;
import java.io.Writer;
import java.util.*;
import javax.annotation.processing.*;
import javax.lang.model.element.*;
import javax.lang.model.type.*;
import javax.lang.model.util.*;
import javax.tools.Diagnostic;

/** §6.2.1.1 canonical classes, planned by AccessPlanner and emitted one round after entity accesses. */
final class MetamodelWriter {
    private record Field(String name,String kind,List<String> arguments) {}
    private record Plan(TypeElement type,List<AccessPlanner.Member> members,String superclass) {}
    private final ProcessingEnvironment environment;
    private final Elements elements;
    private final Types types;
    private final Map<String,Plan> plans=new LinkedHashMap<>();
    private final Map<String,List<Field>> fields=new LinkedHashMap<>();
    private static final String MARKER = "MANSART_JPA_GENERATED";
    MetamodelWriter(ProcessingEnvironment environment) {
        this.environment=environment; elements=environment.getElementUtils(); types=environment.getTypeUtils();
    }
    void plan(TypeElement type,List<AccessPlanner.Member> members,String superclass) {
        plans.putIfAbsent(type.getQualifiedName().toString(),new Plan(type,List.copyOf(members),superclass));
    }
    void emit() {
        for (var plan:plans.values()) {
            String entity=plan.type.getQualifiedName().toString();
            if (fields.containsKey(entity)) continue;
            List<Field> declared=plan.members.stream().filter(m -> m.owner().name().equals(elements.getBinaryName(plan.type).toString()))
                .map(this::field).toList();
            String canonical=canonical(plan.type);
            TypeElement existing=elements.getTypeElement(canonical);
            boolean own=existing==null || ElementFilter.fieldsIn(existing.getEnclosedElements()).stream()
                .anyMatch(f -> f.getSimpleName().contentEquals(MARKER) && Boolean.TRUE.equals(f.getConstantValue()));
            if (!own) {
                List<Field> usable=new ArrayList<>();
                for (VariableElement field:ElementFilter.fieldsIn(existing.getEnclosedElements())) {
                    if (!(field.asType() instanceof DeclaredType d)) continue;
                    String name=((TypeElement) d.asElement()).getQualifiedName().toString();
                    if (!name.startsWith("jakarta.persistence.metamodel.")) continue;
                    var attribute=plan.members.stream().filter(m -> m.name().contentEquals(field.getSimpleName())).findFirst();
                    if (attribute.isEmpty()) continue;
                    Field expected=field(attribute.get());
                    if (!name.endsWith("."+expected.kind)) {
                        environment.getMessager().printMessage(Diagnostic.Kind.WARNING,
                            "Existing canonical metamodel "+canonical+"."+field.getSimpleName()+" was emitted with "+name
                            +" instead of "+expected.kind+"; its producing processor owns that class and must be reconciled "
                            +"before this attribute can be populated. Mansart JPA does not overwrite it.",plan.type);
                        continue;
                    }
                    usable.add(expected);
                }
                fields.put(entity,usable);
                writeHelper(plan,canonical,false);
                continue;
            }
            String pkg=elements.getPackageOf(plan.type).getQualifiedName().toString();
            String simple=canonical.substring(pkg.isEmpty()?0:pkg.length()+1);
            StringBuilder text=new StringBuilder();
            if (!pkg.isEmpty()) text.append("package ").append(pkg).append(";\n\n");
            text.append("// Generated by mansart-jpa-processor: do not edit.\n")
                .append("@java.lang.SuppressWarnings(\"rawtypes\")\n")
                .append("@jakarta.persistence.metamodel.StaticMetamodel(").append(entity).append(".class)\n")
                .append("public abstract class ").append(simple);
            if (plan.superclass!=null) text.append(" extends ").append(canonical(elements.getTypeElement(plan.superclass)));
            text.append(" {\n");
            text.append("    public static final boolean ").append(MARKER).append(" = true;\n");
            for (var f:declared) text.append("    public static volatile jakarta.persistence.metamodel.").append(f.kind)
                .append("<").append(entity).append(", ").append(String.join(", ",f.arguments)).append("> ").append(f.name).append(";\n");
            text.append("    public static volatile jakarta.persistence.metamodel.").append(managedKind(plan.type))
                .append("<").append(entity).append("> class_;\n");
            for (var f:declared) text.append("    public static final String ").append(constant(f.name)).append(" = \"").append(f.name).append("\";\n");
            text.append("}\n");
            try (Writer out=environment.getFiler().createSourceFile(canonical,plan.type).openWriter()) { out.write(text.toString()); }
            catch (IOException failure) {
                environment.getMessager().printMessage(Diagnostic.Kind.ERROR,"Cannot generate "+canonical+": "+failure.getMessage(),plan.type);
            }
            fields.put(entity,declared);
            writeHelper(plan,canonical,true);
        }
    }
    Set<String> helpers() {
        Set<String> result=new LinkedHashSet<>();
        fields.keySet().forEach(entity -> result.add(canonical(plans.get(entity).type)+"$$MansartMetamodel"));
        return result;
    }
    String initializer(Collection<String> helpers) {
        StringBuilder source=new StringBuilder("""

            @java.lang.Override
            public java.util.Set<java.lang.Class<?>> populateMetamodel(jakarta.persistence.metamodel.Metamodel metamodel) {
                java.util.Set<java.lang.Class<?>> initialized = new java.util.LinkedHashSet<>();
            """);
        for (String helper:helpers) source.append("        initialized.addAll(").append(helper).append(".populate(metamodel));\n");
        return source.append("        return initialized;\n    }\n").toString();
    }
    private void writeHelper(Plan plan,String canonical,boolean own) {
        String entity=plan.type.getQualifiedName().toString();
        String pkg=elements.getPackageOf(plan.type).getQualifiedName().toString();
        String helper=canonical+"$$MansartMetamodel";
        StringBuilder source=new StringBuilder(pkg.isEmpty()?"":"package "+pkg+";\n");
        source.append("public final class ").append(helper.substring(pkg.isEmpty()?0:pkg.length()+1)).append(" {\n");
        source.append(initialization(entity,canonical,own)).append("}\n");
        try (Writer out=environment.getFiler().createSourceFile(helper,plan.type).openWriter()) { out.write(source.toString()); }
        catch (IOException failure) {
            environment.getMessager().printMessage(Diagnostic.Kind.ERROR,"Cannot generate "+helper+": "+failure.getMessage(),plan.type);
        }
    }
    private String initialization(String entity,String canonical,boolean own) {
        StringBuilder source=new StringBuilder("""

            @java.lang.SuppressWarnings({"unchecked", "rawtypes"})
            public static java.util.Set<java.lang.Class<?>> populate(jakarta.persistence.metamodel.Metamodel metamodel) {
                java.util.Set<java.lang.Class<?>> initialized = new java.util.LinkedHashSet<>();
            """);
            TypeElement existing=elements.getTypeElement(canonical);
            source.append("        if (metamodel.getManagedTypes().stream().anyMatch(t -> t.getJavaType() == ").append(entity).append(".class)) {\n");
            for (var field:fields.get(entity)) {
                String type="jakarta.persistence.metamodel."+field.kind+"<"+entity+", "+String.join(", ",field.arguments)+">";
                source.append("            ").append(canonical).append(".").append(field.name).append(" = ");
                if (own) {
                    source.append("metamodel.managedType(").append(entity).append(".class).getDeclared")
                        .append(field.kind.replace("Attribute",""));
                    if (field.kind.equals("SingularAttribute")) source.append("Attribute");
                    source.append("(\"").append(field.name).append("\"");
                    for (String argument:field.arguments) source.append(", ").append(argument).append(".class");
                    source.append(");\n");
                } else {
                    // A pre-existing producer may flatten inherited attributes; ownership stays in the runtime model.
                    source.append("(").append(type).append(") (jakarta.persistence.metamodel.Attribute<?, ?>) metamodel.managedType(")
                        .append(entity).append(".class).getAttribute(\"").append(field.name).append("\");\n");
                }
            }
            if (own || existing!=null && ElementFilter.fieldsIn(existing.getEnclosedElements()).stream()
                    .anyMatch(f -> f.getSimpleName().contentEquals("class_"))) {
                source.append("            ").append(canonical).append(".class_ = ");
                if (managedKind(plans.get(entity).type).equals("MappedSuperclassType"))
                    source.append("(jakarta.persistence.metamodel.MappedSuperclassType<").append(entity).append(">) ");
                source.append("metamodel.")
                    .append(managedKind(plans.get(entity).type).equals("EntityType")?"entity":managedKind(plans.get(entity).type).equals("EmbeddableType")
                        ?"embeddable":"managedType").append("(").append(entity).append(".class);\n");
            }
            source.append("            initialized.add(").append(entity).append(".class);\n        }\n");
        return source.append("        return initialized;\n    }\n").toString();
    }
    private Field field(AccessPlanner.Member member) {
        TypeElement owner=elements.getTypeElement(member.owner().name().replace('$','.'));
        String name=member.element() instanceof MethodInfo method?method.name():member.name();
        Element element=owner.getEnclosedElements().stream().filter(e -> e.getSimpleName().contentEquals(name)).findFirst().orElseThrow();
        TypeMirror type=element instanceof ExecutableElement method?method.getReturnType():element.asType();
        String erased=types.erasure(type).toString();
        List<? extends TypeMirror> arguments=type instanceof DeclaredType declared?declared.getTypeArguments():List.of();
        String kind=switch (erased) {
            case "java.util.Map" -> "MapAttribute";
            case "java.util.List" -> "ListAttribute";
            case "java.util.Set" -> "SetAttribute";
            case "java.util.Collection" -> "CollectionAttribute";
            default -> "SingularAttribute";
        };
        List<String> values;
        if (kind.equals("SingularAttribute")) values=List.of(box(type));
        else if (!arguments.isEmpty()) values=arguments.stream().map(this::box).toList();
        else {
            String target=explicitType(element,"jakarta.persistence.ElementCollection","targetClass");
            if (target==null) target=explicitType(element,"jakarta.persistence.OneToMany","targetEntity");
            if (target==null) target=explicitType(element,"jakarta.persistence.ManyToMany","targetEntity");
            if (target==null) target="java.lang.Object";
            String key=explicitType(element,"jakarta.persistence.MapKeyClass","value");
            values=kind.equals("MapAttribute")?List.of(key==null?"java.lang.Object":key,target):List.of(target);
        }
        return new Field(member.name(),kind,values);
    }
    private String explicitType(Element element,String annotation,String name) {
        for (AnnotationMirror mirror:element.getAnnotationMirrors()) {
            if (!mirror.getAnnotationType().toString().equals(annotation)) continue;
            for (var value:elements.getElementValuesWithDefaults(mirror).entrySet())
                if (value.getKey().getSimpleName().contentEquals(name) && value.getValue().getValue() instanceof TypeMirror target
                        && !target.toString().equals("void")) return box(target);
        }
        return null;
    }
    private String canonical(TypeElement type) {
        return elements.getBinaryName(type).toString()+"_";
    }
    private String box(TypeMirror type) {
        return type.getKind().isPrimitive()?types.boxedClass((PrimitiveType) type).getQualifiedName().toString():types.erasure(type).toString();
    }
    private String managedKind(TypeElement type) {
        return type.getAnnotationMirrors().stream().anyMatch(a -> a.getAnnotationType().toString().equals("jakarta.persistence.Entity"))
            ?"EntityType":type.getAnnotationMirrors().stream().anyMatch(a -> a.getAnnotationType().toString().equals("jakarta.persistence.Embeddable"))
            ?"EmbeddableType":"MappedSuperclassType";
    }
    private String constant(String name) { return name.replaceAll("([a-z0-9])([A-Z])","$1_$2").toUpperCase(Locale.ROOT); }
}
