/*
 * Copyright (c) ${year} Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */

package io.vidocq.mansart.it;

import io.vidocq.mansart.data.core.MansartData;
import io.vidocq.mansart.data.core.RepositoryRuntime;
import io.vidocq.mansart.data.dialect.EntityModel;
import io.vidocq.mansart.it.lib.Gadget;
import io.vidocq.mansart.it.lib.GadgetRepository;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import javax.sql.DataSource;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.Optional;
import java.util.Properties;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Proves the ahead-of-time path: {@code mansart-data-maven-plugin} generated a {@code @Singleton}
 * implementation (and metamodel) for {@link GadgetRepository} — which lives in a pre-compiled
 * dependency jar with no APT — into the application-owned package {@code it.gen}. The generated
 * implementation is a real compiled class with an {@code (RepositoryRuntime)} constructor, so no
 * runtime bytecode generation or reflective proxy is involved.
 */
class ExternalRepositoryCodegenTest {

    // Names are deterministic: targetPackage (it.gen) + mangled source FQN. See ExternalRepositoryCodegen.
    private static final String IMPL_FQN =
            "it.gen.io_vidocq_mansart_it_lib_GadgetRepositoryImpl";
    private static final String METAMODEL_FQN =
            "it.gen._io_vidocq_mansart_it_lib_Gadget";

    private static DataSource dataSource;
    private static RepositoryRuntime runtime;

    @BeforeAll
    static void initStack() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:mansart-external-it;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        dataSource = ds;
        runtime = MansartData.builder().dataSource(ds).build().runtime();
        // Schema is provided by the test (ensureTable is a best-effort bootstrap that does not emit
        // IDENTITY) — same approach as the APT integration tests.
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS \"gadgets\"");
            s.execute("CREATE TABLE \"gadgets\" ("
                    + "  \"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  \"name\" VARCHAR(200) NOT NULL"
                    + ")");
        }
    }

    @Test
    void pluginWroteTheExternalIndex() throws Exception {
        try (InputStream in = Thread.currentThread().getContextClassLoader()
                .getResourceAsStream("META-INF/mansart-repositories-external.list")) {
            assertThat(in).as("external index resource").isNotNull();
            Properties p = new Properties();
            p.load(in);
            assertThat(p.getProperty(GadgetRepository.class.getName()))
                    .as("interface -> impl mapping")
                    .isEqualTo(IMPL_FQN);
        }
    }

    @Test
    void generatedImplementationIsACompiledAotClass() throws Exception {
        Class<?> impl = Class.forName(IMPL_FQN);
        assertThat(GadgetRepository.class).isAssignableFrom(impl);
        // The compile-time contract: a public (RepositoryRuntime) constructor wired by the BCE.
        assertThat(impl.getConstructor(RepositoryRuntime.class)).isNotNull();
    }

    @Test
    void crudThroughTheGeneratedImplementation() throws Exception {
        // Touch the relocated metamodel so its static initializer (private-field MethodHandles) is
        // exercised as part of the AOT path.
        EntityModel<?> model = (EntityModel<?>)
                Class.forName(METAMODEL_FQN).getField("$MODEL").get(null);
        assertThat(model.entityClass()).isEqualTo(Gadget.class);

        GadgetRepository repo = (GadgetRepository) Class.forName(IMPL_FQN)
                .getConstructor(RepositoryRuntime.class)
                .newInstance(runtime);

        Gadget widget = new Gadget();
        widget.setName("widget");
        Gadget saved = repo.save(widget);
        assertThat(saved.getId()).isNotNull().isPositive();

        Optional<Gadget> found = repo.findById(saved.getId());
        assertThat(found).isPresent();
        assertThat(found.orElseThrow().getName()).isEqualTo("widget");

        Gadget another = new Gadget();
        another.setName("gizmo");
        repo.save(another);

        List<Gadget> byName = repo.findByName("widget");
        assertThat(byName).extracting(Gadget::getName).containsExactly("widget");

        List<Gadget> all = repo.findAll().toList();
        assertThat(all).extracting(Gadget::getName).containsExactlyInAnyOrder("widget", "gizmo");
    }
}
