/*
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.persistence.spi;

/**
 * Marker interface for generated lazy-loading proxy classes.
 * Implemented by proxy subclasses generated by the Maven plugin or APT.
 */
public interface LazyEntityProxy {
    
    /**
     * Returns true if the underlying entity has been loaded from the database.
     *
     * @return true if loaded
     */
    boolean isLoaded();
    
    /**
     * Sets the lazy initializer that will trigger the database load.
     *
     * @param initializer the lazy initializer
     */
    void setLazyInitializer(LazyInitializer initializer);
}
