/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.persistence.spi;

import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.util.Objects;

/**
 * Metadata for an entity's primary key (identifier) attribute.
 *
 * <p>This class captures information about the primary key of an entity,
 * including the field/property name, type, and generation strategy for
 * auto-generated identifiers.
 *
 * <p> Instances are created during bootstrap time by the APT processor
 * based on {@link Id} and {@link jakarta.persistence.GeneratedValue}
 * annotations.
 *
 * @see EntityMetadata
 */
public final class PrimaryKeyMetadata {

    private final String attributeName;
    private final Class<?> attributeType;
    private final GenerationType generationType;
    private final String generatorName;

    /**
     * Creates a new PrimaryKeyMetadata instance.
     *
     * @param attributeName     the name of the identifier attribute, must not be {@code null}
     * @param attributeType     the type of the identifier attribute, must not be {@code null}
     * @param generationType    the generation strategy, must not be {@code null}
     * @param generatorName     the name of the generator for SEQUENCE/TABLE strategies, may be {@code null}
     */
    public PrimaryKeyMetadata(String attributeName, Class<?> attributeType, GenerationType generationType, String generatorName) {
        this.attributeName = Objects.requireNonNull(attributeName, "attributeName must not be null");
        this.attributeType = Objects.requireNonNull(attributeType, "attributeType must not be null");
        this.generationType = generationType; // null means application-assigned identifier
        this.generatorName = generatorName;
    }

    /**
     * Returns the name of the identifier attribute.
     *
     * @return the attribute name, never {@code null}
     */
    public String getAttributeName() {
        return attributeName;
    }

    /**
     * Returns the type of the identifier attribute.
     *
     * @return the attribute type, never {@code null}
     */
    public Class<?> getAttributeType() {
        return attributeType;
    }

    /**
     * Returns the generation strategy for the identifier.
     *
     * @return the generation strategy, never {@code null}
     */
    public GenerationType getGenerationType() {
        return generationType;
    }

    /**
     * Returns the name of the generator for SEQUENCE/TABLE strategies.
     *
     * @return the generator name, or {@code null} if not using SEQUENCE/TABLE
     */
    public String getGeneratorName() {
        return generatorName;
    }

    /**
     * Returns whether this primary key uses auto-generation.
     *
     * @return {@code true} if generation type is AUTO, IDENTITY, SEQUENCE, or TABLE
     */
    public boolean isAutoGenerated() {
        return generationType != null && 
               (generationType == GenerationType.AUTO ||
                generationType == GenerationType.IDENTITY ||
                generationType == GenerationType.SEQUENCE ||
                generationType == GenerationType.TABLE);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PrimaryKeyMetadata that = (PrimaryKeyMetadata) o;
        return Objects.equals(attributeName, that.attributeName) &&
               Objects.equals(attributeType, that.attributeType) &&
               generationType == that.generationType &&
               Objects.equals(generatorName, that.generatorName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(attributeName, attributeType, generationType, generatorName);
    }

    @Override
    public String toString() {
        return "PrimaryKeyMetadata{" +
               "attributeName='" + attributeName + '\'' +
               ", attributeType=" + attributeType +
               ", generationType=" + generationType +
               ", generatorName='" + generatorName + '\'' +
               '}';
    }
}
