/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-1.2
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.data.core;

import io.vidocq.mansart.data.dialect.EntityModel;

/**
 * M7-25 — single dispatch entry point used by classes generated by {@link RuntimeRepositoryClassGenerator}.
 *
 * <p>Generated classes hold one instance of this callback. Every method of the implemented
 * repository interface boils down to {@code callback.dispatch(methodIndex, args)} — the
 * generator emits the {@code Object[]} argument packing and the return-value unboxing. This
 * keeps the per-method bytecode tiny (no per-method case statement, no inner closures) and
 * lets {@link RuntimeRepositoryProxy}'s existing {@code Dispatcher} logic stay untouched.
 */
public final class MansartCallback {

    @FunctionalInterface
    interface Dispatcher {
        Object invoke(RepositoryRuntime runtime, EntityModel<?> model, Object[] args);
    }

    private final Dispatcher[] dispatchers;
    private final EntityModel<?>[] models;
    private final RepositoryRuntime runtime;

    public MansartCallback(Dispatcher[] dispatchers, EntityModel<?>[] models, RepositoryRuntime runtime) {
        this.dispatchers = dispatchers;
        this.models = models;
        this.runtime = runtime;
    }

    public Object dispatch(int methodIndex, Object[] args) {
        return dispatchers[methodIndex].invoke(runtime, models[methodIndex], args == null ? new Object[0] : args);
    }
}
