package io.vidocq.mansart.data.core;

import io.vidocq.mansart.data.dialect.EntityModel;

/**
 * M7-25 — single dispatch entry point used by classes generated by {@link RuntimeRepositoryClassGenerator}.
 *
 * <p>Generated classes hold one instance of this callback. Every method of the implemented
 * repository interface boils down to {@code callback.dispatch(methodIndex, args)} — the
 * generator emits the {@code Object[]} argument packing and the return-value unboxing. This
 * keeps the per-method bytecode tiny (no per-method case statement, no inner closures) and
 * lets {@link RuntimeRepositoryProxy}'s existing {@code Dispatcher} logic stay untouched.
 */
public final class MansartCallback {

    @FunctionalInterface
    interface Dispatcher {
        Object invoke(RepositoryRuntime runtime, EntityModel<?> model, Object[] args);
    }

    private final Dispatcher[] dispatchers;
    private final EntityModel<?>[] models;
    private final RepositoryRuntime runtime;

    public MansartCallback(Dispatcher[] dispatchers, EntityModel<?>[] models, RepositoryRuntime runtime) {
        this.dispatchers = dispatchers;
        this.models = models;
        this.runtime = runtime;
    }

    public Object dispatch(int methodIndex, Object[] args) {
        return dispatchers[methodIndex].invoke(runtime, models[methodIndex], args == null ? new Object[0] : args);
    }
}
