/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.transactions.moduleit;

import io.vidocq.mansart.transactions.cdi.MansartTransactionsProducer;
import io.vidocq.mansart.transactions.cdi.TransactionalInterceptor;
import io.vidocq.mansart.transactions.cdi.TransactionalInterceptorRequiresNew;
import io.vidocq.vauban.core.container.VaubanContainer;
import jakarta.transaction.Status;
import jakarta.transaction.TransactionManager;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Runs on the MODULE PATH (this is a named module with a {@code module-info}). It boots a Vauban
 * container programmatically and obtains the {@code @Transactional} bean via {@link
 * VaubanContainer#select(Class)} — deliberately NOT through {@code @Inject} into the test instance,
 * so nothing reflects into the test class and the module needs no {@code opens}.
 *
 * <p>What this proves, that a class-path test cannot: the {@code @Transactional} interception fires
 * on a strict module path with a BUILD-TIME generated {@code $$Intercepted} subclass, with
 * <strong>zero {@code opens} anywhere</strong>. The application bean ({@link TxService}, in this
 * module) AND the {@code @Transactional} interceptors (in mansart-transactions-cdi) are all
 * instantiated and field-injected in-module by their generated {@code VaubanComponentProvider}s; the
 * interceptors' public {@code @AroundInvoke} methods are reachable without opens. (This became a full
 * zero-opens proof once the APT emitted {@code @Interceptor} classes into {@code _VaubanComponents} —
 * VAU-INT-004.)</p>
 */
class TxModulePathTest {

    @Test
    void intercepts_transactional_on_the_module_path_with_a_build_time_subclass() throws Exception {
        VaubanContainer container = VaubanContainer.builder()
                .addBeanClass(MansartTransactionsProducer.class)
                .addBeanClass(TransactionalInterceptor.class)
                .addBeanClass(TransactionalInterceptorRequiresNew.class)
                .addBeanClass(TxService.class)
                .build();
        try {
            // The $$Intercepted subclass is a BUILD-TIME class (generated by the APT, present in this
            // module's jar), not a subclass spun at runtime — it is loadable by name.
            assertNotNull(
                    Class.forName("io.vidocq.mansart.transactions.moduleit.TxService$$Intercepted"),
                    "the APT must have generated TxService$$Intercepted at build time");

            TransactionManager tm = container.select(TransactionManager.class);
            TxService svc = container.select(TxService.class);

            // REQUIRED with no active TX: the interceptor must start a TX around the call and clear it after.
            assertEquals(Status.STATUS_NO_TRANSACTION, tm.getStatus());
            boolean[] sawActiveTx = {false};
            svc.required(() -> sawActiveTx[0] = tm.getStatus() == Status.STATUS_ACTIVE);
            assertTrue(sawActiveTx[0],
                    "the @Transactional(REQUIRED) interceptor must start a TX inside the method");
            assertEquals(Status.STATUS_NO_TRANSACTION, tm.getStatus(),
                    "the interceptor must commit/clear the TX after the method returns");

            // REQUIRES_NEW nested in an active TX: a distinct inner TX must run, then the outer resumes.
            tm.begin();
            int outer = System.identityHashCode(tm.getTransaction());
            int[] inner = {outer};
            svc.requiresNew(() -> inner[0] = System.identityHashCode(tm.getTransaction()));
            assertTrue(inner[0] != outer, "REQUIRES_NEW must suspend the outer TX and start a new one");
            assertEquals(outer, System.identityHashCode(tm.getTransaction()),
                    "the outer TX must be resumed after REQUIRES_NEW returns");
            tm.commit();
        } finally {
            container.close();
        }
    }

    /**
     * MANSART-006 — the {@code @TransactionScoped} context registered by the BCE
     * ({@code MetaAnnotations.addContext}) must be installed on the strict module path: two
     * client-proxy calls inside the same transaction must reach the SAME contextual instance.
     * Before the fix, Vauban could not instantiate {@code TransactionScopedContext} in-module
     * (no {@code opens}, context class absent from {@code _VaubanComponents}) and silently fell
     * back to per-call {@code @Dependent} instances — state written through the proxy vanished
     * on the next call.
     */
    @Test
    void transaction_scoped_context_works_on_the_module_path() throws Exception {
        VaubanContainer container = VaubanContainer.builder()
                .addBeanClass(io.vidocq.mansart.transactions.cdi.MansartTransactionsExtension.class)
                .addBeanClass(MansartTransactionsProducer.class)
                .addBeanClass(TransactionalInterceptor.class)
                .addBeanClass(TxScopedCounter.class)
                .build();
        try {
            TransactionManager tm = container.select(TransactionManager.class);
            TxScopedCounter counter = container.select(TxScopedCounter.class);

            tm.begin();
            try {
                counter.increment();
                counter.increment();
                assertEquals(2, counter.value(),
                        "@TransactionScoped state must survive across proxy calls within one TX");
            } finally {
                tm.commit();
            }
        } finally {
            container.close();
        }
    }
}
