/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.jpa.core.flush;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.vidocq.mansart.jpa.core.context.ManagedEntity;
import io.vidocq.mansart.jpa.core.context.PersistenceContext;
import io.vidocq.mansart.jpa.core.mapping.MappedEntity;
import io.vidocq.mansart.jpa.core.mapping.MappedUnit;
import io.vidocq.mansart.jpa.core.model.build.fixtures.Author;
import io.vidocq.mansart.jpa.core.model.build.fixtures.Book;
import io.vidocq.mansart.jpa.core.model.build.fixtures.Customer;
import io.vidocq.mansart.jpa.core.model.build.fixtures.Level;
import io.vidocq.mansart.jpa.core.model.build.fixtures.Note;
import io.vidocq.mansart.jpa.dialect.Dialect;
import jakarta.persistence.EntityExistsException;
import jakarta.persistence.OptimisticLockException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.List;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/** §3.2.4: the synchronisation of a persistence context to the database, on H2. */
class FlushEngineTest {

    private static final MappedUnit UNIT = MappedUnit.of(List.of(Customer.class.getName(), Note.class.getName(),
        Author.class.getName(), Book.class.getName()), FlushEngineTest.class.getClassLoader());

    private Connection database;
    private final JdbcRecorder recorder = new JdbcRecorder();
    private Connection connection;
    private FlushEngine engine;
    private final PersistenceContext context = new PersistenceContext();

    @BeforeEach
    void schema() throws SQLException {
        database = DriverManager.getConnection("jdbc:h2:mem:");
        try (Statement ddl = database.createStatement()) {
            ddl.execute("create table Customer (id bigint primary key, name varchar(50), E_MAIL varchar(120), visits int, "
                + "balance decimal(19,2), credit decimal(12,2), since date, legacy timestamp, birthDate date, token uuid, level int, "
                + "preferredLevel varchar(10), grade varchar(5), notes varchar(1000), picture varbinary(100), version int, "
                + "biography varchar(1000))");
            ddl.execute("create table Note (id bigint generated by default as identity primary key, CREATED timestamp(9), "
                + "text varchar(100))");
        }
        database.setAutoCommit(false);
        connection = recorder.wrap(database);
        Dialect dialect = Dialects.resolve(database, null, FlushEngineTest.class.getClassLoader());
        engine = new FlushEngine(dialect, 50);
    }

    @AfterEach
    void close() throws SQLException {
        database.close();
    }

    private static MappedEntity type(Class<?> entity) {
        return UNIT.entity(entity).orElseThrow();
    }

    private static int index(MappedEntity type, String attribute) {
        return type.model().attributes().indexOf(type.model().attribute(attribute).orElseThrow());
    }

    private static Object customer(long id, String name) {
        MappedEntity type = type(Customer.class);
        Object customer = type.access().instantiate();
        type.access().set(customer, index(type, "id"), id);
        type.access().set(customer, index(type, "name"), name);
        type.access().set(customer, index(type, "level"), Level.SILVER);
        return customer;
    }

    private Object column(String sql) throws SQLException {
        try (Statement query = database.createStatement(); ResultSet row = query.executeQuery(sql)) {
            return row.next() ? row.getObject(1) : null;
        }
    }

    @Test
    void aPersistedInstanceIsInsertedWithItsVersionInitialised() throws SQLException {
        Object customer = customer(1, "Vidocq");
        ManagedEntity entry = context.persist(customer, type(Customer.class));
        engine.flush(context, connection);
        assertThat(column("select name from Customer where id = 1")).isEqualTo("Vidocq");
        assertThat(column("select level from Customer where id = 1")).isEqualTo(1); // ORDINAL
        assertThat(column("select version from Customer where id = 1")).isEqualTo(0);
        assertThat(entry.inserted()).isTrue();
        assertThat(entry.snapshot()).isNotNull();
    }

    @Test
    void aChangedInstanceIsUpdatedAndItsVersionIncremented() throws SQLException { // §3.4.2
        Object customer = customer(1, "Vidocq");
        context.persist(customer, type(Customer.class));
        engine.flush(context, connection);
        type(Customer.class).access().set(customer, index(type(Customer.class), "name"), "Eugène");
        engine.flush(context, connection);
        assertThat(column("select name from Customer where id = 1")).isEqualTo("Eugène");
        assertThat(column("select version from Customer where id = 1")).isEqualTo(1);
        assertThat(type(Customer.class).access().get(customer, index(type(Customer.class), "version"))).isEqualTo(1);
    }

    @Test
    void anUnchangedInstanceIsNotUpdated() throws SQLException {
        context.persist(customer(1, "Vidocq"), type(Customer.class));
        engine.flush(context, connection);
        recorder.calls.clear();
        engine.flush(context, connection);
        assertThat(recorder.calls).isEmpty();
        assertThat(column("select version from Customer where id = 1")).isEqualTo(0);
    }

    @Test
    void aRemovedInstanceIsDeletedAndForgotten() throws SQLException { // §3.2.3
        Object customer = customer(1, "Vidocq");
        context.persist(customer, type(Customer.class));
        engine.flush(context, connection);
        context.remove(customer);
        engine.flush(context, connection);
        assertThat(column("select count(*) from Customer")).isEqualTo(0L);
        assertThat(context.entry(customer)).isEmpty();
    }

    @Test
    void rowsDeletedTogetherAreDeletedReferencingFirstWithoutClearingNotNullForeignKeys() throws SQLException { // §3.2.4
        try (Statement ddl = database.createStatement()) {
            ddl.execute("create table Author (id bigint primary key)");
            ddl.execute("create table Author_aliases (Author_id bigint, aliases varchar(50))");
            ddl.execute("create table Book (id bigint primary key, author_id bigint not null references Author(id))");
        }
        MappedEntity authors = type(Author.class);
        MappedEntity books = type(Book.class);
        Object author = authors.access().instantiate();
        authors.access().set(author, index(authors, "id"), 1L);
        Object book = books.access().instantiate();
        books.access().set(book, index(books, "id"), 2L);
        books.access().set(book, index(books, "author"), author);
        context.persist(author, authors);
        context.persist(book, books);
        engine.flush(context, connection);
        context.remove(author); // the referenced row is removed first: the delete order, not NULL, satisfies the key
        context.remove(book);
        recorder.calls.clear();
        engine.flush(context, connection);
        assertThat(column("select count(*) from Book")).isEqualTo(0L);
        assertThat(column("select count(*) from Author")).isEqualTo(0L);
        assertThat(recorder.calls).noneMatch(call -> call.startsWith("prepare UPDATE"));
    }

    @Test
    void anInstanceRemovedBeforeItsInsertNeverReachesTheDatabase() {
        Object customer = customer(1, "Vidocq");
        context.persist(customer, type(Customer.class));
        context.remove(customer);
        engine.flush(context, connection);
        assertThat(recorder.calls).isEmpty();
        assertThat(context.size()).isZero();
    }

    @Test
    void anIdentityIdentifierIsReadBackAndBecomesTheIdentity() throws SQLException {
        MappedEntity note = type(Note.class);
        Object first = note.access().instantiate();
        note.access().set(first, index(note, "createdAt"), Instant.parse("2026-10-08T10:00:00Z"));
        Object second = note.access().instantiate();
        ManagedEntity firstEntry = context.persist(first, note);
        context.persist(second, note);
        engine.flush(context, connection);
        long id = (Long) note.access().get(first, index(note, "id"));
        assertThat(id).isPositive();
        assertThat((Long) note.access().get(second, index(note, "id"))).isEqualTo(id + 1);
        assertThat(firstEntry.key().id()).isEqualTo(id);
        assertThat(column("select count(*) from Note")).isEqualTo(2L);
    }

    @Test
    void insertsOfAnEntityAreBatched() {
        for (long id = 1; id <= 3; id++) {
            context.persist(customer(id, "c" + id), type(Customer.class));
        }
        engine.flush(context, connection);
        assertThat(recorder.prepared()).hasSize(1);
        assertThat(recorder.count("addBatch")).isEqualTo(3);
        assertThat(recorder.count("executeBatch")).isEqualTo(1);
    }

    @Test
    void aRowChangedByAnotherTransactionFailsTheUpdate() throws SQLException { // §3.4.2
        Object customer = customer(1, "Vidocq");
        context.persist(customer, type(Customer.class));
        engine.flush(context, connection);
        try (Statement other = database.createStatement()) {
            other.executeUpdate("update Customer set version = 5 where id = 1");
        }
        type(Customer.class).access().set(customer, index(type(Customer.class), "name"), "Eugène");
        assertThatThrownBy(() -> engine.flush(context, connection)).isInstanceOf(OptimisticLockException.class)
            .satisfies(e -> assertThat(((OptimisticLockException) e).getEntity()).isSameAs(customer));
    }

    @Test
    void aRowChangedByAnotherTransactionFailsTheDelete() throws SQLException {
        Object customer = customer(1, "Vidocq");
        context.persist(customer, type(Customer.class));
        engine.flush(context, connection);
        try (Statement other = database.createStatement()) {
            other.executeUpdate("update Customer set version = 5 where id = 1");
        }
        context.remove(customer);
        assertThatThrownBy(() -> engine.flush(context, connection)).isInstanceOf(OptimisticLockException.class);
    }

    @Test
    void anIdentityAlreadyInTheDatabaseFailsTheInsert() throws SQLException { // §3.2.2
        try (Statement other = database.createStatement()) {
            other.executeUpdate("insert into Customer (id, name) values (1, 'already')");
        }
        context.persist(customer(1, "Vidocq"), type(Customer.class));
        assertThatThrownBy(() -> engine.flush(context, connection)).isInstanceOf(EntityExistsException.class);
    }

    @Test
    void entitiesAreInsertedAfterTheEntitiesTheyReference() { // foreign keys: Book -> Author
        assertThat(type(Author.class).rank()).isLessThan(type(Book.class).rank());
    }
}
