<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.vidocq.mansart</groupId>
        <artifactId>mansart-jakarta-persistence</artifactId>
        <version>0.3.0-SNAPSHOT</version>
    </parent>

    <artifactId>mansart-persistence-core</artifactId>
    <name>Mansart :: Persistence :: Core</name>
    <description>Core runtime implementation of Jakarta Persistence 3.2.</description>

    <dependencies>
        <dependency>
            <groupId>io.vidocq.mansart</groupId>
            <artifactId>mansart-persistence-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.mansart</groupId>
            <artifactId>mansart-persistence-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.transaction</groupId>
            <artifactId>jakarta.transaction-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.mansart</groupId>
            <artifactId>mansart-data-dialect-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.mansart</groupId>
            <artifactId>mansart-data-dialect-h2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.mansart</groupId>
            <artifactId>mansart-data-dialect-postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>io.vidocq.mansart</groupId>
            <artifactId>mansart-transactions-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        --add-opens io.vidocq.mansart.persistence.core/io.vidocq.mansart.persistence.core.jpql=ALL-UNNAMED
                        --add-opens io.vidocq.mansart.persistence.core/io.vidocq.mansart.persistence.core.runtime=ALL-UNNAMED
                        --add-opens io.vidocq.mansart.persistence.core/io.vidocq.mansart.persistence.core.cache=ALL-UNNAMED
                        --add-opens io.vidocq.mansart.persistence.core/io.vidocq.mansart.persistence.core.mapping=ALL-UNNAMED
                        --add-opens io.vidocq.mansart.persistence.core/io.vidocq.mansart.persistence.core.bootstrap=ALL-UNNAMED
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>