/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.jpa.core.mapping;

import static org.assertj.core.api.Assertions.assertThat;

import io.vidocq.mansart.jpa.core.model.AttributeModel;
import io.vidocq.mansart.jpa.core.model.BasicAttribute;
import io.vidocq.mansart.jpa.core.model.EmbeddableModel;
import io.vidocq.mansart.jpa.core.model.EmbeddedAttribute;
import io.vidocq.mansart.jpa.core.model.EntityModel;
import io.vidocq.mansart.jpa.core.model.build.fixtures.Customer;
import io.vidocq.mansart.jpa.core.model.build.fixtures.Invoice;
import io.vidocq.mansart.jpa.core.model.build.fixtures.Lowercase;
import io.vidocq.mansart.jpa.core.model.build.fixtures.MoneyConverter;
import io.vidocq.mansart.jpa.core.model.build.fixtures.Shop;
import io.vidocq.mansart.jpa.core.spi.ManagedAccess;
import io.vidocq.mansart.jpa.core.spi.ManagedAccessProvider;
import java.util.List;
import org.junit.jupiter.api.Test;

class MappedUnitTest {

    private static MappedUnit unit(Class<?>... classes) {
        return MappedUnit.of(List.of(classes).stream().map(Class::getName).toList(), MappedUnitTest.class.getClassLoader());
    }

    @Test
    void everyEntityHasItsAccess() {
        MappedUnit unit = unit(Customer.class, Shop.class);
        for (EntityModel entity : unit.model().entities()) {
            assertThat(unit.access(entity).type()).isEqualTo(entity.javaType());
        }
    }

    @Test
    void everyEmbeddableOfEveryEntityHasItsAccessNestedOnesIncluded() {
        MappedUnit unit = unit(Shop.class);
        EntityModel shop = unit.model().entity(Shop.class).orElseThrow();
        EmbeddableModel address = ((EmbeddedAttribute) shop.attribute("address").orElseThrow()).embeddable();
        EmbeddableModel geo = ((EmbeddedAttribute) address.attribute("geo").orElseThrow()).embeddable();
        assertThat(unit.access(address).type()).isEqualTo(address.javaType());
        assertThat(unit.access(geo).type()).isEqualTo(geo.javaType());
    }

    @Test
    void everyBasicAttributeHasItsBinderEmbeddedOnesIncluded() {
        MappedUnit unit = unit(Customer.class, Shop.class, Invoice.class, MoneyConverter.class);
        for (EntityModel entity : unit.model().entities()) {
            assertBinders(unit, entity.attributes());
        }
    }

    /** Stands for an access generated by mansart-jpa-processor for {@link Lowercase} (property access). */
    private static final class LowercaseAccess extends ManagedAccess {
        LowercaseAccess(List<String> attributes) {
            super(Lowercase.class, attributes);
        }

        @Override
        public Object instantiate() {
            return new Lowercase();
        }

        @Override
        public Object get(Object instance, int attribute) {
            Lowercase entity = (Lowercase) instance;
            return switch (attribute) {
                case 0 -> entity.getId();
                case 1 -> entity.getdescription();
                default -> throw new IndexOutOfBoundsException(attribute);
            };
        }

        @Override
        public void set(Object instance, int attribute, Object value) {
            Lowercase entity = (Lowercase) instance;
            switch (attribute) {
                case 0 -> entity.setId((Integer) value);
                case 1 -> entity.setdescription((String) value);
                default -> throw new IndexOutOfBoundsException(attribute);
            }
        }
    }

    private static MappedUnit unit(List<ManagedAccessProvider> providers, Class<?>... classes) {
        return MappedUnit.of(List.of(classes).stream().map(Class::getName).toList(), MappedUnitTest.class.getClassLoader(),
            new io.vidocq.mansart.jpa.core.model.source.ClassFileSource(MappedUnitTest.class.getClassLoader()), providers);
    }

    @Test
    void anAccessGeneratedAtBuildTimeIsPreferredToAHiddenClass() {
        ManagedAccess generated = new LowercaseAccess(List.of("id:PROPERTY", "description:PROPERTY"));
        MappedUnit unit = unit(List.of(() -> List.of(generated)), Lowercase.class);
        EntityModel lowercase = unit.model().entity(Lowercase.class).orElseThrow();
        assertThat(unit.access(lowercase)).isSameAs(generated);
    }

    @Test
    void anAccessThatDoesNotListTheAttributesOfTheModelIsNotUsed() { // a class changed since it was generated
        ManagedAccess stale = new LowercaseAccess(List.of("description:PROPERTY", "id:PROPERTY"));
        MappedUnit unit = unit(List.of(() -> List.of(stale)), Lowercase.class);
        ManagedAccess access = unit.access(unit.model().entity(Lowercase.class).orElseThrow());
        assertThat(access).isNotSameAs(stale);
        assertThat(access.getClass().isHidden()).isTrue();
    }

    @Test
    void accessesOfClassesOutsideTheUnitAreIgnored() {
        ManagedAccess generated = new LowercaseAccess(List.of("id:PROPERTY", "description:PROPERTY"));
        MappedUnit unit = unit(List.of(() -> List.of(generated)), Customer.class);
        assertThat(unit.access(unit.model().entity(Customer.class).orElseThrow()).getClass().isHidden()).isTrue();
    }

    private static void assertBinders(MappedUnit unit, List<AttributeModel> attributes) {
        for (AttributeModel attribute : attributes) {
            switch (attribute) {
                case BasicAttribute basic -> assertThat(unit.binder(basic)).as(basic.name()).isNotNull();
                case EmbeddedAttribute embedded -> assertBinders(unit, embedded.embeddable().attributes());
                default -> {
                }
            }
        }
    }
}
