package io.vidocq.mansart.jpa.core;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PersistenceConfiguration;
import jakarta.persistence.PersistenceException;
import jakarta.persistence.Table;
import java.io.StringReader;
import java.io.StringWriter;
import java.sql.DriverManager;
import java.util.Map;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;

/** Jakarta Persistence 3.2 §9.4 and §7.12: schema operations use the mapped unit, not entity reflection. */
class SchemaGenerationTest {
    @Entity @Table(name = "p9_record")
    public static class Record {
        @Id @GeneratedValue(strategy = GenerationType.IDENTITY) public long id;
        @Column(name = "description", length = 42, nullable = false) public String text;
        public Record() {}
    }

    @Entity @jakarta.persistence.DiscriminatorColumn(name = "kind")
    public static class Parent {
        @Id public int id;
        @Column(name = "year_value") public java.time.Year year;
        public Parent() {}
    }
    @Entity public static class Child extends Parent {
        public String label;
        public Child() {}
    }

    @Test
    void inheritanceDiscriminatorsAndYearAreSchemaColumns() { // §2.14 and §2.8
        try (var factory = new PersistenceConfiguration("p9-inheritance").managedClass(Parent.class).managedClass(Child.class)
                .property("jakarta.persistence.jdbc.url", "jdbc:h2:mem:p9-inheritance")
                .property("jakarta.persistence.schema-generation.database.action", "create").createEntityManagerFactory()) {
            Child child = new Child();
            child.id = 1;
            child.year = java.time.Year.of(2026);
            child.label = "child";
            factory.runInTransaction(em -> em.persist(child));
            Parent found = factory.callInTransaction(em -> em.find(Parent.class, 1));
            assertThat(found).isInstanceOf(Child.class);
            assertThat(found.year).isEqualTo(child.year);
        }
    }

    private PersistenceConfiguration configuration(String database) {
        return new PersistenceConfiguration("schema-" + database).managedClass(Record.class)
            .property("jakarta.persistence.jdbc.url", "jdbc:h2:mem:" + database + ";DB_CLOSE_DELAY=-1");
    }

    @Test
    void databaseActionCreatesMappedColumnsAndIdentity() throws Exception { // §9.4.1
        try (var factory = configuration("p9-create")
                .property("jakarta.persistence.schema-generation.database.action", "drop-and-create")
                .createEntityManagerFactory()) {
            Record record = new Record();
            record.text = "created";
            factory.runInTransaction(em -> em.persist(record));
            assertThat(record.id).isPositive();
            factory.getSchemaManager().validate();
            factory.getSchemaManager().truncate();
            Record missing = factory.callInTransaction(em -> em.find(Record.class, record.id));
            assertThat(missing).isNull();
            factory.getSchemaManager().drop(true);
            assertThatThrownBy(() -> factory.getSchemaManager().validate()).isInstanceOf(jakarta.persistence.SchemaValidationException.class);
            factory.getSchemaManager().create(true);
            factory.getSchemaManager().validate();
        }
    }

    @Test
    void scriptsUseCallerWritersWithoutClosingThem() { // §9.4.2
        var create = new StringWriter();
        var drop = new StringWriter();
        try (var factory = configuration("p9-writer")
                .property("jakarta.persistence.schema-generation.database.action", "none")
                .property("jakarta.persistence.schema-generation.scripts.action", "drop-and-create")
                .property("jakarta.persistence.schema-generation.scripts.create-target", create)
                .property("jakarta.persistence.schema-generation.scripts.drop-target", drop)
                .createEntityManagerFactory()) {
            assertThat(create.toString()).containsIgnoringCase("CREATE TABLE p9_record")
                .contains("VARCHAR(42)").contains("GENERATED BY DEFAULT AS IDENTITY");
            assertThat(drop.toString()).containsIgnoringCase("DROP TABLE");
        }
        create.write("-- still usable");
    }

    @Test
    void metadataAndScriptOrderingAndLoadAreHonored() throws Exception { // §9.4.1
        try (var factory = configuration("p9-order")
                .property("jakarta.persistence.schema-generation.database.action", "create")
                .property("jakarta.persistence.schema-generation.create-source", "metadata-then-script")
                .property("jakarta.persistence.schema-generation.create-script-source",
                    new StringReader("INSERT INTO p9_record(description) VALUES ('a; b'); -- comment\n"))
                .property("jakarta.persistence.sql-load-script-source",
                    new StringReader("INSERT INTO p9_record(description) VALUES ('loaded');"))
                .createEntityManagerFactory();
             var connection = DriverManager.getConnection("jdbc:h2:mem:p9-order");
             var statement = connection.createStatement();
             var result = statement.executeQuery("SELECT COUNT(*) FROM p9_record")) {
            assertThat(result.next()).isTrue();
            assertThat(result.getInt(1)).isEqualTo(2);
            factory.getSchemaManager().truncate();
            try (var reloaded = statement.executeQuery("SELECT description FROM p9_record")) {
                assertThat(reloaded.next()).isTrue();
                assertThat(reloaded.getString(1)).isEqualTo("loaded");
                assertThat(reloaded.next()).isFalse();
            }
        }
    }

    @Test
    void generateSchemaReturnsFalseForAnUnknownUnit() {
        assertThat(new MansartPersistenceProvider().generateSchema("not-a-unit", Map.of())).isFalse();
    }

    @Test
    void invalidActionsAndMissingTargetsAreRejectedBeforeExecutingDdl() {
        assertThatThrownBy(() -> configuration("p9-invalid")
            .property("jakarta.persistence.schema-generation.database.action", "invalid")
            .createEntityManagerFactory()).isInstanceOf(PersistenceException.class);
        assertThatThrownBy(() -> configuration("p9-invalid")
            .property("jakarta.persistence.schema-generation.scripts.action", "create")
            .createEntityManagerFactory()).isInstanceOf(PersistenceException.class);
    }
}
