/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * It is also made available under the European Union Public Licence v. 1.2,
 * which is available at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.jpa.dialect;

import io.vidocq.mansart.jpa.dialect.sql.Delete;
import io.vidocq.mansart.jpa.dialect.sql.DeleteQuery;
import io.vidocq.mansart.jpa.dialect.sql.Expression;
import io.vidocq.mansart.jpa.dialect.sql.Identifier;
import io.vidocq.mansart.jpa.dialect.sql.Increment;
import io.vidocq.mansart.jpa.dialect.sql.Insert;
import io.vidocq.mansart.jpa.dialect.sql.NextValue;
import io.vidocq.mansart.jpa.dialect.sql.Query;
import io.vidocq.mansart.jpa.dialect.sql.Select;
import io.vidocq.mansart.jpa.dialect.sql.SelectStatement;
import io.vidocq.mansart.jpa.dialect.sql.SetQuery;
import io.vidocq.mansart.jpa.dialect.sql.Statement;
import io.vidocq.mansart.jpa.dialect.sql.Table;
import io.vidocq.mansart.jpa.dialect.sql.Update;
import io.vidocq.mansart.jpa.dialect.sql.UpdateQuery;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * The ANSI SQL rendering that dialects extend, overriding only what their database does differently. Quoted names are
 * delimited with double quotes, embedded quotes doubled.
 */
public abstract class StandardDialect implements Dialect {

    protected StandardDialect() {
    }

    @Override
    public String render(Statement statement) {
        return switch (statement) {
            case Insert insert -> insert(insert);
            case Update update -> update(update);
            case Delete delete -> "DELETE FROM " + table(delete.table()) + where(delete.conditions());
            case Select select -> "SELECT " + list(select.columns()) + " FROM " + table(select.table()) + where(select.conditions())
                + lock(select);
            case NextValue next -> nextValue(next);
            case Increment increment -> "UPDATE " + table(increment.table()) + " SET " + name(increment.value()) + " = "
                + name(increment.value()) + " + ? WHERE " + name(increment.key()) + " = ?";
            case SelectStatement query -> renderQuery(query).sql();
            case UpdateQuery update -> renderQuery(update).sql();
            case DeleteQuery delete -> renderQuery(delete).sql();
            case io.vidocq.mansart.jpa.dialect.sql.SchemaStatement schema -> schema(schema);
            case io.vidocq.mansart.jpa.dialect.sql.TruncateTables truncate -> truncate(truncate);
            case io.vidocq.mansart.jpa.dialect.sql.ForeignKeyStatement key -> "ALTER TABLE " + (key.drop() ? "IF EXISTS " : "") + table(key.table())
                + (key.drop() ? " DROP CONSTRAINT IF EXISTS " + name(key.name()) : " ADD CONSTRAINT " + name(key.name()) + " "
                    + (key.definition() != null && !key.definition().isBlank() ? key.definition()
                        : "FOREIGN KEY (" + list(key.columns()) + ") REFERENCES " + table(key.referencedTable())
                            + " (" + list(key.referencedColumns()) + ")"));
        };
    }

    protected String schema(io.vidocq.mansart.jpa.dialect.sql.SchemaStatement schema) {
        return switch (schema.operation()) {
            case CREATE_TABLE -> {
                List<String> definitions = new ArrayList<>();
                for (var column : schema.columns()) {
                    String type = column.definition() != null && !column.definition().isBlank()
                        ? column.definition() : schemaType(column);
                    definitions.add(name(column.name()) + " " + type
                        + (column.identity() ? " GENERATED BY DEFAULT AS IDENTITY" : "")
                        + (!column.nullable() ? " NOT NULL" : "") + (column.unique() ? " UNIQUE" : ""));
                }
                if (!schema.primaryKey().isEmpty()) {
                    definitions.add("PRIMARY KEY (" + list(schema.primaryKey()) + ")");
                }
                yield "CREATE TABLE " + table(schema.table()) + " (" + String.join(", ", definitions) + ")";
            }
            case DROP_TABLE -> "DROP TABLE IF EXISTS " + table(schema.table()) + " CASCADE";
            case CREATE_SEQUENCE -> "CREATE SEQUENCE " + table(schema.table()) + " START WITH " + schema.initialValue()
                + " INCREMENT BY " + schema.increment();
            case DROP_SEQUENCE -> "DROP SEQUENCE IF EXISTS " + table(schema.table());
            case CREATE_SCHEMA -> "CREATE SCHEMA IF NOT EXISTS " + name(schema.table().name());
            case DROP_SCHEMA -> "DROP SCHEMA IF EXISTS " + name(schema.table().name());
            case CREATE_INDEX -> "CREATE " + (schema.unique() ? "UNIQUE " : "") + "INDEX " + name(schema.objectName())
                + " ON " + table(schema.table()) + " (" + String.join(", ", schema.indexColumns().stream().map(c -> {
                    String[] parts = c.strip().split("\\s+");
                    String suffix = parts.length > 1 && parts[1].equalsIgnoreCase("DESC") ? " DESC" : "";
                    return name(identifier(parts[0])) + suffix;
                }).toList()) + ")";
            case TRUNCATE -> "TRUNCATE TABLE " + table(schema.table());
        };
    }

    protected String schemaType(io.vidocq.mansart.jpa.dialect.sql.SchemaStatement.Column column) {
        return switch (column.type()) {
            case VARCHAR, CHAR -> column.type().getName() + "(" + column.length() + ")";
            case VARBINARY, BINARY -> column.type().getName() + "(" + column.length() + ")";
            case DECIMAL, NUMERIC -> "NUMERIC(" + (column.precision() > 0 ? column.precision() : 38) + "," + column.scale() + ")";
            case TIME_WITH_TIMEZONE -> "TIME WITH TIME ZONE";
            case TIMESTAMP_WITH_TIMEZONE -> "TIMESTAMP WITH TIME ZONE";
            default -> column.type().getName();
        };
    }

    private static Identifier identifier(String value) {
        return value.startsWith("\"") && value.endsWith("\"")
            ? Identifier.quoted(value.substring(1, value.length() - 1)) : Identifier.of(value);
    }

    protected String truncate(io.vidocq.mansart.jpa.dialect.sql.TruncateTables truncate) {
        return String.join("; ", truncate.tables().stream().map(t -> "DELETE FROM " + table(t)).toList());
    }

    // ---- queries ------------------------------------------------------------------------------------------

    /**
     * Each parameter is first written as a marker, unique to it; once the SQL is whole, the markers are read in the
     * order of the text and replaced by {@code ?}: a dialect may move or repeat the arguments of a function freely.
     */
    private static final char MARK = '\u0001';
    private static final char END_MARK = '\u0002';

    @Override
    public Rendered renderQuery(Statement statement) {
        List<Expression.Parameter> marked = new ArrayList<>();
        String text = switch (statement) {
            case SelectStatement query -> selectStatement(query, marked);
            case UpdateQuery update -> bulkUpdate(update, marked);
            case DeleteQuery delete -> "DELETE FROM " + table(delete.table()) + " AS " + delete.alias()
                + (delete.where() == null ? "" : " WHERE " + expression(delete.where(), 0, marked));
            default -> render(statement);
        };
        StringBuilder sql = new StringBuilder(text.length());
        List<Expression.Parameter> parameters = new ArrayList<>();
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            if (c == MARK) {
                int end = text.indexOf(END_MARK, i);
                parameters.add(marked.get(Integer.parseInt(text.substring(i + 1, end))));
                sql.append('?');
                i = end;
            } else {
                sql.append(c);
            }
        }
        return new Rendered(sql.toString(), parameters);
    }

    private String selectStatement(SelectStatement statement, List<Expression.Parameter> parameters) {
        return switch (statement) {
            case Query query -> query(query, parameters);
            case SetQuery setQuery -> setQuery(setQuery, parameters);
        };
    }

    private String setQuery(SetQuery query, List<Expression.Parameter> parameters) {
        StringBuilder sql = new StringBuilder();
        for (int i = 0; i < query.operands().size(); i++) {
            if (i > 0) {
                SetQuery.Operation operation = query.operations().get(i - 1);
                sql.append(' ').append(operation.operator()).append(operation.all() ? " ALL " : " ");
            }
            sql.append('(').append(this.query(query.operands().get(i), parameters)).append(')');
        }
        if (!query.orderBy().isEmpty()) {
            sql.append(" ORDER BY ");
            for (int i = 0; i < query.orderBy().size(); i++) {
                SetQuery.Order order = query.orderBy().get(i);
                sql.append(i == 0 ? "" : ", ").append(order.position()).append(order.descending() ? " DESC" : "");
                if (order.nullsFirst() != null) {
                    sql.append(order.nullsFirst() ? " NULLS FIRST" : " NULLS LAST");
                }
            }
        }
        if (query.offset() != null && query.offset() > 0) {
            sql.append(" OFFSET ").append(query.offset()).append(" ROWS");
        }
        if (query.limit() != null) {
            sql.append(" FETCH FIRST ").append(query.limit()).append(" ROWS ONLY");
        }
        return sql.toString();
    }

    /** {@code UPDATE table AS alias SET column = value, … [WHERE …]}: the assigned columns unqualified, as SQL wants them. */
    private String bulkUpdate(UpdateQuery update, List<Expression.Parameter> parameters) {
        StringBuilder sql = new StringBuilder("UPDATE ").append(table(update.table())).append(" AS ").append(update.alias()).append(" SET ");
        for (int i = 0; i < update.assignments().size(); i++) {
            UpdateQuery.Assignment assignment = update.assignments().get(i);
            sql.append(i == 0 ? "" : ", ").append(name(assignment.column())).append(" = ").append(expression(assignment.value(), 0, parameters));
        }
        if (update.where() != null) {
            sql.append(" WHERE ").append(expression(update.where(), 0, parameters));
        }
        return sql.toString();
    }

    /** A query, its parameters written as markers registered in {@code parameters}. */
    private String query(Query query, List<Expression.Parameter> parameters) {
        StringBuilder sql = new StringBuilder("SELECT ");
        if (query.distinct()) {
            sql.append("DISTINCT ");
        }
        sql.append(expressions(query.select(), parameters));
        sql.append(" FROM ");
        for (int f = 0; f < query.from().size(); f++) {
            Query.From from = query.from().get(f);
            sql.append(f == 0 ? "" : ", ").append(table(from.table())).append(' ').append(from.alias());
            for (Query.Join join : from.joins()) {
                sql.append(join.kind() == Query.Join.Kind.LEFT ? " LEFT JOIN " : " INNER JOIN ").append(table(join.table())).append(' ')
                    .append(join.alias()).append(" ON ").append(expression(join.on(), 0, parameters));
            }
        }
        if (query.where() != null) {
            sql.append(" WHERE ").append(expression(query.where(), 0, parameters));
        }
        if (!query.groupBy().isEmpty()) {
            sql.append(" GROUP BY ").append(expressions(query.groupBy(), parameters));
        }
        if (query.having() != null) {
            sql.append(" HAVING ").append(expression(query.having(), 0, parameters));
        }
        if (!query.orderBy().isEmpty()) {
            sql.append(" ORDER BY ");
            for (int o = 0; o < query.orderBy().size(); o++) {
                Query.Order order = query.orderBy().get(o);
                sql.append(o == 0 ? "" : ", ").append(expression(order.expression(), 0, parameters))
                    .append(order.descending() ? " DESC" : "");
                if (order.nullsFirst() != null) {
                    sql.append(order.nullsFirst() ? " NULLS FIRST" : " NULLS LAST");
                }
            }
        }
        return sql.append(paging(query)).append(lock(query.lock(), query.noWait())).toString();
    }

    /** SQL:2008 paging, which H2 and PostgreSQL understand: {@code OFFSET n ROWS FETCH FIRST m ROWS ONLY}. */
    protected String paging(Query query) {
        String paging = query.offset() == null || query.offset() == 0 ? "" : " OFFSET " + query.offset() + " ROWS";
        return query.limit() == null ? paging : paging + " FETCH FIRST " + query.limit() + " ROWS ONLY";
    }

    private String expressions(List<Expression> expressions, List<Expression.Parameter> parameters) {
        StringBuilder sql = new StringBuilder();
        for (int i = 0; i < expressions.size(); i++) {
            sql.append(i == 0 ? "" : ", ").append(expression(expressions.get(i), 0, parameters));
        }
        return sql.toString();
    }

    /** The precedence of an expression: how tightly it binds (see {@link Expression.Operator#precedence()}). */
    private static int precedence(Expression expression) {
        return switch (expression) {
            case Expression.Binary binary -> binary.operator().precedence();
            case Expression.Not _ -> 3;
            case Expression.IsNull _, Expression.Between _, Expression.Like _, Expression.In _, Expression.InQuery _,
                 Expression.Exists _ -> 4;
            case Expression.Function function when function.name().equals("CONCAT") -> 5;
            default -> 9;
        };
    }

    /** {@code expression}, parenthesised when it binds more loosely than {@code context}. */
    private String expression(Expression expression, int context, List<Expression.Parameter> parameters) {
        String sql = switch (expression) {
            case Expression.Column column -> column.alias() + '.' + name(column.name());
            case Expression.Parameter parameter -> {
                parameters.add(parameter);
                yield MARK + Integer.toString(parameters.size() - 1) + END_MARK;
            }
            case Expression.Literal literal -> literal(literal.value());
            case Expression.Binary binary -> {
                int precedence = binary.operator().precedence();
                // a right operand of the same precedence is grouped as written, a - (b - c), but AND and OR associate
                boolean associative = binary.right() instanceof Expression.Binary right && right.operator() == binary.operator()
                    && (binary.operator() == Expression.Operator.AND || binary.operator() == Expression.Operator.OR);
                yield expression(binary.left(), precedence, parameters) + ' ' + binary.operator().symbol() + ' '
                    + expression(binary.right(), associative ? precedence : precedence + 1, parameters);
            }
            case Expression.Cast cast -> "CAST(" + expression(cast.expression(), 0, parameters) + " AS "
                + castType(cast.type()) + ')';
            case Expression.Not not -> "NOT " + expression(not.operand(), 4, parameters);
            case Expression.IsNull isNull -> expression(isNull.operand(), 5, parameters) + (isNull.negated() ? " IS NOT NULL" : " IS NULL");
            case Expression.Between between -> expression(between.operand(), 5, parameters) + (between.negated() ? " NOT" : "")
                + " BETWEEN " + expression(between.low(), 5, parameters) + " AND " + expression(between.high(), 5, parameters);
            case Expression.Like like -> expression(like.operand(), 5, parameters) + (like.negated() ? " NOT" : "") + " LIKE "
                + expression(like.pattern(), 5, parameters)
                + (like.escape() == null ? "" : " ESCAPE " + expression(like.escape(), 5, parameters));
            case Expression.In in -> expression(in.operand(), 5, parameters) + (in.negated() ? " NOT" : "") + " IN ("
                + expressions(in.values(), parameters) + ")";
            case Expression.Aggregate aggregate -> aggregate.function() + '(' + (aggregate.distinct() ? "DISTINCT " : "")
                + (aggregate.argument() == null ? "*" : expression(aggregate.argument(), 0, parameters)) + ')';
            case Expression.Function function -> {
                List<String> arguments = new ArrayList<>();
                for (Expression argument : function.arguments()) {
                    arguments.add(argument instanceof Expression.Literal literal && function.keywords().contains(arguments.size())
                        ? String.valueOf(literal.value()) : expression(argument, function.name().equals("CONCAT") ? 6 : 0, parameters));
                }
                yield function(function.name(), arguments);
            }
            case Expression.Case kase -> {
                StringBuilder text = new StringBuilder("CASE");
                if (kase.operand() != null) {
                    text.append(' ').append(expression(kase.operand(), 0, parameters));
                }
                for (Expression.When when : kase.whens()) {
                    text.append(" WHEN ").append(expression(when.when(), 0, parameters)).append(" THEN ")
                        .append(expression(when.then(), 0, parameters));
                }
                if (kase.otherwise() != null) {
                    text.append(" ELSE ").append(expression(kase.otherwise(), 0, parameters));
                }
                yield text.append(" END").toString();
            }
            case Expression.Subquery subquery -> '(' + selectStatement(subquery.query(), parameters) + ')';
            case Expression.Exists exists -> (exists.negated() ? "NOT EXISTS (" : "EXISTS (")
                + selectStatement(exists.query(), parameters) + ')';
            case Expression.InQuery in -> expression(in.operand(), 5, parameters) + (in.negated() ? " NOT" : "") + " IN ("
                + selectStatement(in.query(), parameters) + ')';
            case Expression.Quantified quantified -> quantified.quantifier() + " ("
                + selectStatement(quantified.query(), parameters) + ')';
        };
        return precedence(expression) < context ? '(' + sql + ')' : sql;
    }

    private static String castType(Expression.Cast.Type type) {
        return switch (type) {
            case VARCHAR -> "VARCHAR";
            case INTEGER -> "INTEGER";
            case BIGINT -> "BIGINT";
            case REAL -> "REAL";
            case DOUBLE_PRECISION -> "DOUBLE PRECISION";
            case DECIMAL -> "DECIMAL";
            case DATE -> "DATE";
            case TIME -> "TIME";
        };
    }

    /**
     * A function of the query language (§4.6.17.2), its arguments already rendered (a keyword argument as the word):
     * the SQL:2016 syntax H2 and PostgreSQL share, which a dialect overrides where its database differs.
     */
    protected String function(String name, List<String> arguments) {
        return switch (name) {
            case "CONCAT" -> String.join(" || ", arguments);
            case "SUBSTRING" -> "SUBSTRING(" + arguments.get(0) + " FROM " + arguments.get(1)
                + (arguments.size() > 2 ? " FOR " + arguments.get(2) : "") + ')';
            case "TRIM" -> "TRIM(" + arguments.get(0) + (arguments.get(1).equals("NULL") ? "" : ' ' + arguments.get(1)) + " FROM "
                + arguments.get(2) + ')';
            case "LENGTH" -> "CHAR_LENGTH(" + arguments.getFirst() + ')';
            case "LOCATE" -> arguments.size() == 2 ? "POSITION(" + arguments.get(0) + " IN " + arguments.get(1) + ')'
                : "LOCATE(" + String.join(", ", arguments) + ')';
            case "EXTRACT" -> "EXTRACT(" + arguments.get(0) + " FROM " + arguments.get(1) + ')';
            case "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP" -> name;
            case "LOCAL_DATE" -> "CURRENT_DATE";
            case "LOCAL_TIME" -> "LOCALTIME";
            case "LOCAL_DATETIME" -> "LOCALTIMESTAMP";
            default -> name + '(' + String.join(", ", arguments) + ')';
        };
    }

    /** A literal: {@code NULL}, {@code TRUE} / {@code FALSE}, a number as written, a string quoted. */
    protected String literal(Object value) {
        return switch (value) {
            case null -> "NULL";
            case Boolean b -> b ? "TRUE" : "FALSE";
            case Number number -> number.toString();
            case String string -> '\'' + string.replace("'", "''") + '\'';
            default -> throw new IllegalArgumentException("Not a literal: " + value);
        };
    }

    /** The row lock of a select: {@code FOR UPDATE}, {@code FOR SHARE}, and {@code NOWAIT} when it must not wait. */
    protected String lock(Select select) {
        return lock(select.lock(), select.noWait());
    }

    /** {@code FOR UPDATE}, {@code FOR SHARE}, and {@code NOWAIT} when the lock must not wait; nothing without a lock. */
    protected String lock(Select.Lock lock, boolean noWait) {
        String clause = switch (lock) {
            case NONE -> "";
            case SHARED -> " FOR SHARE";
            case EXCLUSIVE -> " FOR UPDATE";
        };
        return clause.isEmpty() || !noWait ? clause : clause + " NOWAIT";
    }

    /** SQL:2003 {@code NEXT VALUE FOR}, as a one-row query. */
    protected String nextValue(NextValue next) {
        return "VALUES NEXT VALUE FOR " + table(next.table());
    }

    protected String insert(Insert insert) {
        if (insert.columns().isEmpty()) {
            return "INSERT INTO " + table(insert.table()) + " DEFAULT VALUES";
        }
        return "INSERT INTO " + table(insert.table()) + " (" + list(insert.columns()) + ") VALUES ("
            + String.join(", ", Collections.nCopies(insert.columns().size(), "?")) + ")";
    }

    protected String update(Update update) {
        StringBuilder sql = new StringBuilder("UPDATE ").append(table(update.table())).append(" SET ");
        for (int i = 0; i < update.assignments().size(); i++) {
            sql.append(i == 0 ? "" : ", ").append(name(update.assignments().get(i))).append(" = ?");
        }
        return sql.append(where(update.conditions())).toString();
    }

    protected String where(List<Identifier> conditions) {
        StringBuilder sql = new StringBuilder(" WHERE ");
        for (int i = 0; i < conditions.size(); i++) {
            sql.append(i == 0 ? "" : " AND ").append(name(conditions.get(i))).append(" = ?");
        }
        return sql.toString();
    }

    protected String table(Table table) {
        StringBuilder sql = new StringBuilder();
        if (table.catalog() != null) {
            sql.append(name(table.catalog())).append('.');
        }
        if (table.schema() != null) {
            sql.append(name(table.schema())).append('.');
        }
        return sql.append(name(table.name())).toString();
    }

    protected String list(List<Identifier> columns) {
        StringBuilder sql = new StringBuilder();
        for (int i = 0; i < columns.size(); i++) {
            sql.append(i == 0 ? "" : ", ").append(name(columns.get(i)));
        }
        return sql.toString();
    }

    /** A name, delimited when quoted. */
    protected String name(Identifier identifier) {
        return identifier.quoted() ? '"' + identifier.name().replace("\"", "\"\"") + '"' : identifier.name();
    }
}
