/*
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.persistence.tests;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;

import jakarta.persistence.PersistenceException;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import io.vidocq.mansart.data.dialect.h2.H2Dialect;
import io.vidocq.mansart.persistence.core.runtime.MansartCallback;
import io.vidocq.mansart.persistence.core.dialect.EntityMapper;
import io.vidocq.mansart.persistence.core.dialect.DialectEntityModelAdapter;
import io.vidocq.mansart.persistence.tests.model.GeneratedIdEntity;
import io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity;
import io.vidocq.mansart.persistence.tests.model.VersionedEntity;

/**
 * TDD test for EntityMapper: maps entity instances to SQL INSERT/UPDATE/DELETE via dialect SPI.
 */
class EntityMapperTest {

    private Connection connection;
    private MansartCallback callback;
    private DialectEntityModelAdapter adapter;
    private EntityMapper mapper;

    @BeforeEach
    void beforeEach() throws SQLException {
        // In-memory H2 database
        this.connection = DriverManager.getConnection("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1", "", "");
        this.callback = new MansartCallback(List.of(GeneratedIdEntity.class, SimpleAssignedIdEntity.class, VersionedEntity.class));
        this.adapter = new DialectEntityModelAdapter();
        this.mapper = new EntityMapper(new H2Dialect(), callback, adapter);

        // Create tables for test entities
        try (var st = connection.createStatement()) {
            st.execute(
                "CREATE TABLE IF NOT EXISTS \"generated_id_entities\" ( "
                    + "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "\"name\" VARCHAR(255), "
                    + "\"value\" INTEGER, "
                    + "\"active\" BOOLEAN "
                    + ")");
            st.execute(
                "CREATE TABLE IF NOT EXISTS \"simple_assigned_id_entities\" ( "
                    + "\"id\" BIGINT PRIMARY KEY, "
                    + "\"name\" VARCHAR(255), "
                    + "\"value\" INTEGER "
                    + ")");
            st.execute(
                "CREATE TABLE IF NOT EXISTS \"versioned_entities\" ( "
                    + "\"id\" BIGINT PRIMARY KEY, "
                    + "\"name\" VARCHAR(255), "
                    + "\"version\" INTEGER DEFAULT 0)");
        }
    }

    @AfterEach
    void afterEach() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.createStatement().execute("DROP ALL OBJECTS DELETE FILES");
            connection.close();
        }
    }

    @Test
    void insertGeneratedId() throws SQLException {
        GeneratedIdEntity entity = new GeneratedIdEntity();
        entity.setName("Alice");
        entity.setValue(42);
        entity.setActive(true);

        Object generatedKey = mapper.insert(connection, entity);

        assertThat(generatedKey).isNotNull();
        assertThat(entity.getId()).isNotNull();

        try (var rs = connection.createStatement().executeQuery("SELECT \"id\", \"name\", \"value\", \"active\" FROM \"generated_id_entities\" WHERE \"id\" = " + entity.getId())) {
            assertThat(rs.next()).isTrue();
            assertThat(rs.getLong("id")).isEqualTo(entity.getId());
            assertThat(rs.getString("name")).isEqualTo("Alice");
            assertThat(rs.getInt("value")).isEqualTo(42);
            assertThat(rs.getBoolean("active")).isTrue();
        }
    }

    @Test
    void insertAssignedId() throws SQLException {
        SimpleAssignedIdEntity entity = new SimpleAssignedIdEntity();
        entity.setId(123L);
        entity.setName("Bob");
        entity.setValue(99);

        Object result = mapper.insert(connection, entity);

        // For assigned ID, insert returns the id value
        assertThat(result).isEqualTo(123L);

        try (var rs = connection.createStatement().executeQuery("SELECT \"id\", \"name\", \"value\" FROM \"simple_assigned_id_entities\" WHERE \"id\" = 123")) {
            assertThat(rs.next()).isTrue();
            assertThat(rs.getLong("id")).isEqualTo(123L);
            assertThat(rs.getString("name")).isEqualTo("Bob");
            assertThat(rs.getInt("value")).isEqualTo(99);
        }
    }

    @Test
    void selectGeneratedId() throws SQLException {
        // Insert a row manually to select
        connection.createStatement().executeUpdate(
            "INSERT INTO \"generated_id_entities\" (\"name\", \"value\", \"active\") VALUES ('Charlie', 7, true)");
        Long id;
        try (var rs = connection.createStatement().executeQuery("SELECT \"id\" FROM \"generated_id_entities\" WHERE \"name\"='Charlie'")) {
            assertThat(rs.next()).isTrue();
            id = rs.getLong(1);
        }

        GeneratedIdEntity entity = mapper.select(connection, GeneratedIdEntity.class, id);

        assertThat(entity).isNotNull();
        assertThat(entity.getId()).isEqualTo(id);
        assertThat(entity.getName()).isEqualTo("Charlie");
        assertThat(entity.getValue()).isEqualTo(7);
        assertThat(entity.isActive()).isTrue();
    }

    @Test
    void selectAssignedId() throws SQLException {
        connection.createStatement().executeUpdate(
            "INSERT INTO \"simple_assigned_id_entities\" (\"id\", \"name\", \"value\") VALUES (456, 'Dana', 12)");

        SimpleAssignedIdEntity entity = mapper.select(connection, SimpleAssignedIdEntity.class, 456L);

        assertThat(entity).isNotNull();
        assertThat(entity.getId()).isEqualTo(456L);
        assertThat(entity.getName()).isEqualTo("Dana");
        assertThat(entity.getValue()).isEqualTo(12);
    }

    @Test
    void selectNonExistent() throws SQLException {
        GeneratedIdEntity entity = mapper.select(connection, GeneratedIdEntity.class, 9999L);
        assertThat(entity).isNull();
    }

    @Test
    void updateGeneratedId() throws SQLException {
        // Insert a row
        connection.createStatement().executeUpdate(
            "INSERT INTO \"generated_id_entities\" (\"name\", \"value\", \"active\") VALUES ('Eve', 1, false)");
        
        // Insert a row for delete test
        connection.createStatement().executeUpdate(
            "INSERT INTO \"generated_id_entities\" (\"name\", \"value\", \"active\") VALUES ('Grace', 5, true)");
        Long id;
        try (var rs = connection.createStatement().executeQuery("SELECT \"id\" FROM \"generated_id_entities\" WHERE \"name\"='Eve'")) {
            assertThat(rs.next()).isTrue();
            id = rs.getLong(1);
        }

        GeneratedIdEntity entity = mapper.select(connection, GeneratedIdEntity.class, id);
        entity.setName("Eve Updated");
        entity.setValue(100);
        entity.setActive(true);

        int updated = mapper.update(connection, entity);

        assertThat(updated).isEqualTo(1);

        try (var rs = connection.createStatement().executeQuery(
                "SELECT \"name\", \"value\", \"active\" FROM \"generated_id_entities\" WHERE \"id\" = " + id)) {
            assertThat(rs.next()).isTrue();
            assertThat(rs.getString("name")).isEqualTo("Eve Updated");
            assertThat(rs.getInt("value")).isEqualTo(100);
            assertThat(rs.getBoolean("active")).isTrue();
        }
    }

    @Test
    void updateAssignedId() throws SQLException {
        connection.createStatement().executeUpdate(
            "INSERT INTO \"simple_assigned_id_entities\" (\"id\", \"name\", \"value\") VALUES (789, 'Frank', 3)");

        SimpleAssignedIdEntity entity = mapper.select(connection, SimpleAssignedIdEntity.class, 789L);
        entity.setName("Frank Updated");
        entity.setValue(30);

        int updated = mapper.update(connection, entity);

        assertThat(updated).isEqualTo(1);

        try (var rs = connection.createStatement().executeQuery(
                "SELECT \"name\", \"value\" FROM \"simple_assigned_id_entities\" WHERE \"id\" = 789")) {
            assertThat(rs.next()).isTrue();
            assertThat(rs.getString("name")).isEqualTo("Frank Updated");
            assertThat(rs.getInt("value")).isEqualTo(30);
        }
    }

    @Test
    void deleteGeneratedId() throws SQLException {
        connection.createStatement().executeUpdate(
            "INSERT INTO \"generated_id_entities\" (\"name\", \"value\", \"active\") VALUES ('Grace', 5, true)");
        Long id;
        try (var rs = connection.createStatement().executeQuery("SELECT \"id\" FROM \"generated_id_entities\" WHERE \"name\"='Grace'")) {
            assertThat(rs.next()).isTrue();
            id = rs.getLong(1);
        }

        int deleted = mapper.delete(connection, GeneratedIdEntity.class, id);

        assertThat(deleted).isEqualTo(1);

        try (var rs = connection.createStatement().executeQuery("SELECT 1 FROM \"generated_id_entities\" WHERE \"id\" = " + id)) {
            assertThat(rs.next()).isFalse();
        }
    }

    @Test
    void deleteAssignedId() throws SQLException {
        connection.createStatement().executeUpdate(
            "INSERT INTO \"simple_assigned_id_entities\" (\"id\", \"name\", \"value\") VALUES (999, 'Heidi', 7)");

        int deleted = mapper.delete(connection, SimpleAssignedIdEntity.class, 999L);

        assertThat(deleted).isEqualTo(1);

        try (var rs = connection.createStatement().executeQuery("SELECT 1 FROM \"simple_assigned_id_entities\" WHERE \"id\" = 999")) {
            assertThat(rs.next()).isFalse();
        }
    }

    @Test
    void insertWithPersistenceException() throws SQLException {
        try (var conn = DriverManager.getConnection("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1", "", "")) {
            conn.close();
            GeneratedIdEntity entity = new GeneratedIdEntity();
            assertThatThrownBy(() -> mapper.insert(conn, entity))
                .isInstanceOf(PersistenceException.class);
        }
    }

    @Test
    void updateWithPersistenceException() throws SQLException {
        try (var conn = DriverManager.getConnection("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1", "", "")) {
            conn.close();
            GeneratedIdEntity entity = new GeneratedIdEntity();
            entity.setId(1L);
            assertThatThrownBy(() -> mapper.update(conn, entity))
                .isInstanceOf(PersistenceException.class);
        }
    }

    @Test
    void deleteWithPersistenceException() {
        try (var conn = DriverManager.getConnection("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1", "", "")) {
            conn.close();
            assertThatThrownBy(() -> mapper.delete(conn, GeneratedIdEntity.class, 1L))
                .isInstanceOf(PersistenceException.class);
        } catch (SQLException e) {
            throw new PersistenceException(e);
        }
    }

    @Test
    void selectWithPersistenceException() {
        try (var conn = DriverManager.getConnection("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1", "", "")) {
            conn.close();
            assertThatThrownBy(() -> mapper.select(conn, GeneratedIdEntity.class, 1L))
                .isInstanceOf(PersistenceException.class);
        } catch (SQLException e) {
            throw new PersistenceException(e);
        }
    }

    @Test
    void adaptNullThrows() {
        assertThatThrownBy(() -> adapter.adapt(null))
            .isInstanceOf(IllegalArgumentException.class)
            .hasMessageContaining("spiModel must not be null");
    }

    @Test
    void insertAndSelectVersionedEntity() {
        VersionedEntity entity = new VersionedEntity();
        entity.setId(1L);
        entity.setName("Versioned");

        Object result = mapper.insert(connection, entity);
        assertThat(result).isEqualTo(1L);

        VersionedEntity selected = mapper.select(connection, VersionedEntity.class, 1L);
        assertThat(selected).isNotNull();
        assertThat(selected.getName()).isEqualTo("Versioned");
    }

    @Test
    void adaptProducesValidEntityModel() {
        var spiModel = callback.getEntityModel(GeneratedIdEntity.class);
        var dialectModel = adapter.adapt(spiModel);
        assertThat(dialectModel).isNotNull();
        assertThat(dialectModel.tableName()).isEqualTo("generated_id_entities");
        assertThat(dialectModel.attributes()).isNotEmpty();
    }
}
