/*
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.persistence.tests;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.EntityTransaction;
import jakarta.persistence.Persistence;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for M5 work (EntityMapper CRUD, ID generation, column/table mapping)
 * against a real H2 in-memory database.
 */
class H2IntegrationTest {

    private static final String DB_URL = "jdbc:h2:mem:m5jp33;DB_CLOSE_DELAY=-1";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    private EntityManagerFactory emf;
    private EntityManager em;

    @BeforeEach
    void setUp() throws SQLException {
        // Create H2 DataSource
        org.h2.jdbcx.JdbcDataSource dataSource = new org.h2.jdbcx.JdbcDataSource();
        dataSource.setURL(DB_URL);
        dataSource.setUser(USER);
        dataSource.setPassword(PASSWORD);

        // Create EMF with the DataSource property
        emf = Persistence.createEntityManagerFactory(
                "test-pu",
                Map.of("jakarta.persistence.jtaDataSource", dataSource)
        );

        em = emf.createEntityManager();

        // Create schema tables
        createSchemaTables();
    }

    @AfterEach
    void tearDown() {
        if (em != null && em.isOpen()) {
            em.close();
        }
        if (emf != null && emf.isOpen()) {
            emf.close();
        }
    }

    private void createSchemaTables() throws SQLException {
        try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASSWORD);
             Statement stmt = conn.createStatement()) {

            // All table and column names are quoted to match the H2 dialect's
            // quoted-identifier SQL generation. H2 treats quoted identifiers as
            // case-sensitive, so DDL must use the exact case the entity models declare.

            // SimpleAssignedIdEntity table
            stmt.execute("CREATE TABLE IF NOT EXISTS \"simple_assigned_id_entities\" (\"id\" BIGINT PRIMARY KEY, \"name\" VARCHAR(255), \"value\" INTEGER, \"active\" BOOLEAN)");

            // GeneratedIdEntity table (IDENTITY strategy)
            stmt.execute("CREATE TABLE IF NOT EXISTS \"generated_id_entities\" (\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"name\" VARCHAR(255), \"value\" INTEGER, \"active\" BOOLEAN)");

            // SequenceIdEntity table (SEQUENCE strategy)
            stmt.execute("CREATE TABLE IF NOT EXISTS \"sequence_id_entities\" (\"id\" BIGINT PRIMARY KEY, \"name\" VARCHAR(255))");
            stmt.execute("CREATE SEQUENCE IF NOT EXISTS SEQ_ID_SEQ START WITH 1 INCREMENT BY 1");

            // TableIdEntity table (TABLE strategy)
            stmt.execute("CREATE TABLE IF NOT EXISTS \"table_id_entities\" (\"id\" BIGINT PRIMARY KEY, \"name\" VARCHAR(255))");
            stmt.execute("CREATE TABLE IF NOT EXISTS \"id_gen\" (\"GEN_NAME\" VARCHAR(255) PRIMARY KEY, \"GEN_VAL\" BIGINT)");
            // Seed initial values using MERGE to avoid PK violation on repeated test runs
            stmt.execute("MERGE INTO \"id_gen\" (\"GEN_NAME\", \"GEN_VAL\") KEY(\"GEN_NAME\") VALUES ('tblGen', 0)");
            stmt.execute("MERGE INTO \"id_gen\" (\"GEN_NAME\", \"GEN_VAL\") KEY(\"GEN_NAME\") VALUES ('SequenceIdEntity', 0)");
            stmt.execute("MERGE INTO \"id_gen\" (\"GEN_NAME\", \"GEN_VAL\") KEY(\"GEN_NAME\") VALUES ('TableIdEntity', 0)");

            // AutoIdEntity table (AUTO strategy)
            stmt.execute("CREATE TABLE IF NOT EXISTS \"auto_id_entities\" (\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"name\" VARCHAR(255))");

            // ColumnTestEntity table
            stmt.execute("CREATE TABLE IF NOT EXISTS \"column_test_entities\" (\"id\" BIGINT PRIMARY KEY, \"full_name\" VARCHAR(100) NOT NULL, \"description\" VARCHAR(500), \"amount\" DECIMAL(12,2), \"code\" VARCHAR(20), \"label\" VARCHAR(50), \"plain\" VARCHAR(255))");

            // TableTestEntity table
            stmt.execute("CREATE SCHEMA IF NOT EXISTS \"app\"");
            stmt.execute("CREATE TABLE IF NOT EXISTS \"app\".\"custom_entities\" (\"id\" BIGINT PRIMARY KEY, \"name\" VARCHAR(255))");

            // VersionedEntity table
            stmt.execute("CREATE TABLE IF NOT EXISTS \"versioned_entities\" (\"id\" BIGINT PRIMARY KEY, \"name\" VARCHAR(255), \"version\" INTEGER DEFAULT 0)");
        }
    }

    @Test
    void persistAndFindAssignedIdEntity() {
        // Given
        io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity entity = 
                new io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity();
        entity.setId(100L);
        entity.setName("Test Assigned");
        entity.setValue(42);

        EntityTransaction tx = em.getTransaction();
        tx.begin();
        
        // When
        em.persist(entity);
        em.flush();
        tx.commit();

        // Then
        EntityTransaction tx2 = em.getTransaction();
        tx2.begin();
        io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity found = 
                em.find(io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity.class, 100L);
        tx2.commit();

        assertThat(found).isNotNull();
        assertThat(found.getId()).isEqualTo(100L);
        assertThat(found.getName()).isEqualTo("Test Assigned");
        assertThat(found.getValue()).isEqualTo(42);
    }

    @Test
    void persistAndFindIdentityGeneratedIdEntity() {
        // Given
        io.vidocq.mansart.persistence.tests.model.GeneratedIdEntity entity = 
                new io.vidocq.mansart.persistence.tests.model.GeneratedIdEntity();
        entity.setName("Test Identity");
        entity.setValue(123);
        entity.setActive(false);

        EntityTransaction tx = em.getTransaction();
        tx.begin();
        
        // When
        em.persist(entity);
        em.flush();
        tx.commit();

        // Then - ID should be generated
        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getId()).isPositive();

        // And we should be able to find it
        EntityTransaction tx2 = em.getTransaction();
        tx2.begin();
        io.vidocq.mansart.persistence.tests.model.GeneratedIdEntity found = 
                em.find(io.vidocq.mansart.persistence.tests.model.GeneratedIdEntity.class, entity.getId());
        tx2.commit();

        assertThat(found).isNotNull();
        assertThat(found.getId()).isEqualTo(entity.getId());
        assertThat(found.getName()).isEqualTo("Test Identity");
        assertThat(found.getValue()).isEqualTo(123);
    }

    @Test
    void persistAndFindSequenceGeneratedIdEntity() {
        // Given
        io.vidocq.mansart.persistence.tests.model.SequenceIdEntity entity = 
                new io.vidocq.mansart.persistence.tests.model.SequenceIdEntity();
        entity.setName("Test Sequence");

        EntityTransaction tx = em.getTransaction();
        tx.begin();
        
        // When
        em.persist(entity);
        em.flush();
        tx.commit();

        // Then - ID should be generated
        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getId()).isPositive();

        // And we should be able to find it
        EntityTransaction tx2 = em.getTransaction();
        tx2.begin();
        io.vidocq.mansart.persistence.tests.model.SequenceIdEntity found = 
                em.find(io.vidocq.mansart.persistence.tests.model.SequenceIdEntity.class, entity.getId());
        tx2.commit();

        assertThat(found).isNotNull();
        assertThat(found.getId()).isEqualTo(entity.getId());
        assertThat(found.getName()).isEqualTo("Test Sequence");
    }

    @Test
    void persistAndFindTableGeneratedIdEntity() {
        // Given
        io.vidocq.mansart.persistence.tests.model.TableIdEntity entity = 
                new io.vidocq.mansart.persistence.tests.model.TableIdEntity();
        entity.setName("Test Table");

        EntityTransaction tx = em.getTransaction();
        tx.begin();
        
        // When
        em.persist(entity);
        em.flush();
        tx.commit();

        // Then - ID should be generated
        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getId()).isPositive();

        // And we should be able to find it
        EntityTransaction tx2 = em.getTransaction();
        tx2.begin();
        io.vidocq.mansart.persistence.tests.model.TableIdEntity found = 
                em.find(io.vidocq.mansart.persistence.tests.model.TableIdEntity.class, entity.getId());
        tx2.commit();

        assertThat(found).isNotNull();
        assertThat(found.getId()).isEqualTo(entity.getId());
        assertThat(found.getName()).isEqualTo("Test Table");
    }

    @Test
    void persistAndFindAutoGeneratedIdEntity() {
        // Given
        io.vidocq.mansart.persistence.tests.model.AutoIdEntity entity = 
                new io.vidocq.mansart.persistence.tests.model.AutoIdEntity();
        entity.setName("Test Auto");

        EntityTransaction tx = em.getTransaction();
        tx.begin();
        
        // When
        em.persist(entity);
        em.flush();
        tx.commit();

        // Then - ID should be generated
        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getId()).isPositive();

        // And we should be able to find it
        EntityTransaction tx2 = em.getTransaction();
        tx2.begin();
        io.vidocq.mansart.persistence.tests.model.AutoIdEntity found = 
                em.find(io.vidocq.mansart.persistence.tests.model.AutoIdEntity.class, entity.getId());
        tx2.commit();

        assertThat(found).isNotNull();
        assertThat(found.getId()).isEqualTo(entity.getId());
        assertThat(found.getName()).isEqualTo("Test Auto");
    }

    @Test
    void persistAndFindColumnMappedEntity() {
        // Given
        io.vidocq.mansart.persistence.tests.model.ColumnTestEntity entity = 
                new io.vidocq.mansart.persistence.tests.model.ColumnTestEntity();
        entity.setId(50L);
        entity.setName("John Doe");
        entity.setDescription("A test person");
        entity.setAmount(new java.math.BigDecimal("1234.56"));
        entity.setCode("TEST123");
        entity.setLabel("Label Value");
        entity.setPlain("Plain field");

        EntityTransaction tx = em.getTransaction();
        tx.begin();
        
        // When
        em.persist(entity);
        em.flush();
        tx.commit();

        // Then
        EntityTransaction tx2 = em.getTransaction();
        tx2.begin();
        io.vidocq.mansart.persistence.tests.model.ColumnTestEntity found = 
                em.find(io.vidocq.mansart.persistence.tests.model.ColumnTestEntity.class, 50L);
        tx2.commit();

        assertThat(found).isNotNull();
        assertThat(found.getId()).isEqualTo(50L);
        assertThat(found.getName()).isEqualTo("John Doe");
        assertThat(found.getDescription()).isEqualTo("A test person");
        assertThat(found.getAmount()).isEqualTo(new java.math.BigDecimal("1234.56"));
        assertThat(found.getCode()).isEqualTo("TEST123");
        assertThat(found.getLabel()).isEqualTo("Label Value");
        assertThat(found.getPlain()).isEqualTo("Plain field");
    }

    @Test
    void persistAndFindTableMappedEntity() {
        // Given
        io.vidocq.mansart.persistence.tests.model.TableTestEntity entity = 
                new io.vidocq.mansart.persistence.tests.model.TableTestEntity();
        entity.setId(75L);
        entity.setName("Table Mapped Entity");

        EntityTransaction tx = em.getTransaction();
        tx.begin();
        
        // When
        em.persist(entity);
        em.flush();
        tx.commit();

        // Then
        EntityTransaction tx2 = em.getTransaction();
        tx2.begin();
        io.vidocq.mansart.persistence.tests.model.TableTestEntity found = 
                em.find(io.vidocq.mansart.persistence.tests.model.TableTestEntity.class, 75L);
        tx2.commit();

        assertThat(found).isNotNull();
        assertThat(found.getId()).isEqualTo(75L);
        assertThat(found.getName()).isEqualTo("Table Mapped Entity");
    }

    @Test
    void mergeUpdatesEntity() {
        // Given
        io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity entity = 
                new io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity();
        entity.setId(200L);
        entity.setName("Original Name");
        entity.setValue(Integer.valueOf(1));

        EntityTransaction tx = em.getTransaction();
        tx.begin();
        em.persist(entity);
        em.flush();
        tx.commit();

        // When - detach and change
        em.detach(entity);
        entity.setName("Updated Name");
        entity.setValue(Integer.valueOf(999));

        tx = em.getTransaction();
        tx.begin();
        em.merge(entity);
        em.flush();
        tx.commit();

        // Then
        EntityTransaction tx2 = em.getTransaction();
        tx2.begin();
        io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity found = 
                em.find(io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity.class, 200L);
        tx2.commit();

        assertThat(found).isNotNull();
        assertThat(found.getName()).isEqualTo("Updated Name");
        assertThat(found.getValue()).isEqualTo(999);
    }

    @Test
    void removeDeletesEntity() {
        // Given
        io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity entity = 
                new io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity();
        entity.setId(300L);
        entity.setName("To Be Removed");
        entity.setValue(42);

        EntityTransaction tx = em.getTransaction();
        tx.begin();
        em.persist(entity);
        em.flush();
        tx.commit();

        // When
        tx = em.getTransaction();
        tx.begin();
        em.remove(entity);
        em.flush();
        tx.commit();

        // Then
        EntityTransaction tx2 = em.getTransaction();
        tx2.begin();
        io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity found = 
                em.find(io.vidocq.mansart.persistence.tests.model.SimpleAssignedIdEntity.class, 300L);
        tx2.commit();

        assertThat(found).isNull();
    }

    @Test
    void versionedEntityIncrementsVersionOnUpdate() {
        // Given
        io.vidocq.mansart.persistence.tests.model.VersionedEntity entity = 
                new io.vidocq.mansart.persistence.tests.model.VersionedEntity();
        entity.setId(400L);
        entity.setName("Version 0");

        EntityTransaction tx = em.getTransaction();
        tx.begin();
        em.persist(entity);
        em.flush();
        tx.commit();

        int initialVersion = entity.getVersion();
        assertThat(initialVersion).isZero();

        // When - update
        entity.setName("Version 1");
        tx = em.getTransaction();
        tx.begin();
        em.merge(entity);
        em.flush();
        tx.commit();

        // Then
        EntityTransaction tx2 = em.getTransaction();
        tx2.begin();
        io.vidocq.mansart.persistence.tests.model.VersionedEntity found = 
                em.find(io.vidocq.mansart.persistence.tests.model.VersionedEntity.class, 400L);
        tx2.commit();

        assertThat(found).isNotNull();
        assertThat(found.getVersion()).isEqualTo(initialVersion + 1);
        assertThat(found.getName()).isEqualTo("Version 1");
    }
}
