package io.vidocq.mansart.persistence.tests;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import io.vidocq.mansart.data.dialect.h2.H2Dialect;
import io.vidocq.mansart.persistence.core.runtime.MansartCallback;
import io.vidocq.mansart.persistence.core.dialect.EntityMapper;
import io.vidocq.mansart.persistence.core.dialect.DialectEntityModelAdapter;
import io.vidocq.mansart.persistence.tests.model.AutoIdEntity;
import io.vidocq.mansart.persistence.tests.model.SequenceIdEntity;
import io.vidocq.mansart.persistence.tests.model.TableIdEntity;

class IdGenerationTest {

    private Connection connection;
    private EntityMapper mapper;
    private MansartCallback callback;

    @BeforeEach
    void beforeEach() throws SQLException {
        this.connection = DriverManager.getConnection("jdbc:h2:mem:idtest;DB_CLOSE_DELAY=-1", "", "");
        this.callback = new MansartCallback(List.of(SequenceIdEntity.class, TableIdEntity.class, AutoIdEntity.class));
        this.mapper = new EntityMapper(new H2Dialect(), callback, new DialectEntityModelAdapter());

        try (var st = connection.createStatement()) {
            // Table for SEQUENCE entity
            st.execute("CREATE TABLE IF NOT EXISTS \"sequence_id_entities\" ("
                + "\"id\" BIGINT PRIMARY KEY, "
                + "\"name\" VARCHAR(255))")
            ;
            // Sequence for SEQUENCE strategy
            st.execute("CREATE SEQUENCE IF NOT EXISTS \"SEQ_ID_SEQ\" START WITH 1 INCREMENT BY 1");

            // Table for TABLE strategy entity
            st.execute("CREATE TABLE IF NOT EXISTS \"table_id_entities\" ("
                + "\"id\" BIGINT PRIMARY KEY, "
                + "\"name\" VARCHAR(255))")
            ;
            // Generator table for TABLE strategy
            st.execute("CREATE TABLE IF NOT EXISTS \"id_gen\" ("
                + "\"GEN_NAME\" VARCHAR(50) PRIMARY KEY, "
                + "\"GEN_VAL\" BIGINT)");
            st.execute("INSERT INTO \"id_gen\" (\"GEN_NAME\", \"GEN_VAL\") VALUES ('tblGen', 0)");

            // Table for AUTO entity (behaves like IDENTITY)
            st.execute("CREATE TABLE IF NOT EXISTS \"auto_id_entities\" ("
                + "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "\"name\" VARCHAR(255))")
            ;
        }
    }

    @AfterEach
    void afterEach() throws SQLException {
        if (connection != null && !connection.isClosed()) {
            connection.createStatement().execute("DROP ALL OBJECTS DELETE FILES");
            connection.close();
        }
    }

    @Test
    void insertWithSequenceStrategy() {
        SequenceIdEntity entity = new SequenceIdEntity();
        entity.setName("seq-test");

        Object id = mapper.insert(connection, entity);

        assertThat(id).isNotNull();
        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getId()).isEqualTo(1L);

        // Insert second entity to verify sequence increments
        SequenceIdEntity entity2 = new SequenceIdEntity();
        entity2.setName("seq-test-2");
        Object id2 = mapper.insert(connection, entity2);

        assertThat(id2).isEqualTo(2L);
        assertThat(entity2.getId()).isEqualTo(2L);
    }

    @Test
    void insertWithTableStrategy() {
        TableIdEntity entity = new TableIdEntity();
        entity.setName("table-test");

        Object id = mapper.insert(connection, entity);

        assertThat(id).isNotNull();
        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getId()).isEqualTo(1L);

        // Insert second entity to verify table generator increments
        TableIdEntity entity2 = new TableIdEntity();
        entity2.setName("table-test-2");
        Object id2 = mapper.insert(connection, entity2);

        assertThat(id2).isEqualTo(2L);
        assertThat(entity2.getId()).isEqualTo(2L);
    }

    @Test
    void insertWithAutoStrategy() {
        AutoIdEntity entity = new AutoIdEntity();
        entity.setName("auto-test");

        Object id = mapper.insert(connection, entity);

        assertThat(id).isNotNull();
        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getId()).isGreaterThan(0L);
    }
}
