/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.persistence.tests;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies that the Mansart persistence annotation processor generates
 * the JPA static metamodel class ({@code ClassName_}) for an {@code @Entity}.
 *
 * <p>The test entity {@code TestEntity} is compiled by Maven with the
 * processor on {@code annotationProcessorPaths}. This test reads the
 * generated {@code TestEntity_.java} from
 * {@code target/generated-sources/annotations/} and checks its content.</p>
 *
 * @see io.vidocq.mansart.persistence.processor.MansartPersistenceProcessor
 */
class MansartPersistenceProcessorTest {

    /**
     * Reads the generated static metamodel class and verifies its content.
     *
     * <p>The processor runs during Maven's compile phase. By the time
     * this test executes (test phase), the generated file should exist
     * at {@code target/generated-sources/annotations/TestEntity_.java}.</p>
     */
    @Test
    void processorGeneratesStaticMetamodel() throws IOException {
        String basedir = System.getProperty("user.dir");
        Path generatedFile = Path.of(basedir, "target", "generated-sources",
                "annotations", "io.vidocq.mansart.persistence.tests.TestEntity_.java");

        // The processor runs at compile time. If it works, the file exists.
        assertThat(generatedFile)
                .as("JPA static metamodel TestEntity_.java should be generated by the APT")
                .exists()
                .isReadable();

        String content = Files.readString(generatedFile);

        // Verify the generated class has the expected structure:
        // 1. Class name: TestEntity_
        // 2. @StaticMetamodel annotation
        // 3. SingularAttribute fields for each persistent attribute
        // 4. String constants for each attribute
        assertThat(content).contains("public abstract class TestEntity_");
        assertThat(content).contains("@StaticMetamodel(TestEntity.class)");
        assertThat(content).contains("SingularAttribute<TestEntity, java.lang.Long> id");
        assertThat(content).contains("SingularAttribute<TestEntity, java.lang.String> name");
        assertThat(content).contains("SingularAttribute<TestEntity, java.lang.Integer> age");
        assertThat(content).contains("SingularAttribute<TestEntity, java.lang.Integer> version");
        assertThat(content).contains("public static final String ID = \"id\"");
        assertThat(content).contains("public static final String NAME = \"name\"");
        assertThat(content).contains("public static final String AGE = \"age\"");
        assertThat(content).contains("public static final String VERSION = \"version\"");
    }

    /**
     * Verifies that the APT processor generates static metamodel for
     * {@code @Embeddable} types, including plural attributes for
     * {@code @ElementCollection} fields.
     */
    @Test
    void processorGeneratesEmbeddableMetamodel() throws IOException {
        String basedir = System.getProperty("user.dir");
        Path generatedFile = Path.of(basedir, "target", "generated-sources",
                "annotations", "io.vidocq.mansart.persistence.tests.TestEmbeddable_.java");

        assertThat(generatedFile)
                .as("JPA static metamodel TestEmbeddable_ should be generated")
                .exists()
                .isReadable();

        String content = Files.readString(generatedFile);

        assertThat(content).contains("public abstract class TestEmbeddable_");
        assertThat(content).contains("@StaticMetamodel(TestEmbeddable.class)");
        // Singular attributes for basic fields
        assertThat(content).contains("SingularAttribute<TestEmbeddable, java.lang.String> street");
        assertThat(content).contains("SingularAttribute<TestEmbeddable, java.lang.String> city");
        assertThat(content).contains("SingularAttribute<TestEmbeddable, java.lang.String> state");
        // Plural attributes for @ElementCollection fields (fully qualified names)
        assertThat(content).contains("SetAttribute<TestEmbeddable");
        assertThat(content).contains("sZipcode");
        assertThat(content).contains("ListAttribute<TestEmbeddable");
        assertThat(content).contains("lZipcode");
        assertThat(content).contains("MapAttribute<TestEmbeddable");
        assertThat(content).contains("mZipcode");
    }

    /**
     * Verifies that the APT processor generates static metamodel for
     * nested {@code @Embeddable} types.
     */
    @Test
    void processorGeneratesNestedEmbeddableMetamodel() throws IOException {
        String basedir = System.getProperty("user.dir");
        Path generatedFile = Path.of(basedir, "target", "generated-sources",
                "annotations", "io.vidocq.mansart.persistence.tests.TestZipCode_.java");

        assertThat(generatedFile)
                .as("JPA static metamodel TestZipCode_ should be generated")
                .exists()
                .isReadable();

        String content = Files.readString(generatedFile);

        assertThat(content).contains("public abstract class TestZipCode_");
        assertThat(content).contains("@StaticMetamodel(TestZipCode.class)");
        assertThat(content).contains("SingularAttribute<TestZipCode, java.lang.String> zip");
        assertThat(content).contains("SingularAttribute<TestZipCode, java.lang.String> plusFour");
    }

    /**
     * Verifies that the APT processor generates static metamodel for
     * {@code @MappedSuperclass} types.
     */
    @Test
    void processorGeneratesMappedSuperclassMetamodel() throws IOException {
        String basedir = System.getProperty("user.dir");
        Path generatedFile = Path.of(basedir, "target", "generated-sources",
                "annotations", "io.vidocq.mansart.persistence.tests.TestMappedSuperclass_.java");

        assertThat(generatedFile)
                .as("JPA static metamodel TestMappedSuperclass_ should be generated")
                .exists()
                .isReadable();

        String content = Files.readString(generatedFile);

        assertThat(content).contains("public abstract class TestMappedSuperclass_");
        assertThat(content).contains("@StaticMetamodel(TestMappedSuperclass.class)");
        assertThat(content).contains("SingularAttribute<TestMappedSuperclass, java.lang.String> createdAt");
    }

    /**
     * Verifies that the APT processor generates plural attribute fields for
     * {@code @OneToMany} and {@code @ManyToMany} relationships.
     */
    @Test
    void processorGeneratesRelationshipPluralAttributes() throws IOException {
        String basedir = System.getProperty("user.dir");
        Path generatedFile = Path.of(basedir, "target", "generated-sources",
                "annotations", "io.vidocq.mansart.persistence.tests.TestRelationshipEntity_.java");

        assertThat(generatedFile)
                .as("JPA static metamodel TestRelationshipEntity_ should be generated")
                .exists()
                .isReadable();

        String content = Files.readString(generatedFile);

        assertThat(content).contains("public abstract class TestRelationshipEntity_");
        assertThat(content).contains("@StaticMetamodel(TestRelationshipEntity.class)");
        // Singular attributes
        assertThat(content).contains("SingularAttribute<TestRelationshipEntity, java.lang.Long> id");
        assertThat(content).contains("SingularAttribute<TestRelationshipEntity, java.lang.String> name");
        // Plural attributes: @OneToMany(Set) → SetAttribute, @OneToMany(List) → ListAttribute
        assertThat(content).contains("SetAttribute<TestRelationshipEntity");
        assertThat(content).contains("items");
        assertThat(content).contains("ListAttribute<TestRelationshipEntity");
        assertThat(content).contains("orderedItems");
        // @ManyToMany(Set) → SetAttribute
        assertThat(content).contains("tags");
    }

    /**
     * Verifies that the APT processor generates {@code SingularAttribute} fields
     * for each composite key attribute when an entity uses {@code @IdClass}.
     *
     * <p>The entity {@code TestCompositeKeyEmployee} has two {@code @Id} fields
     * ({@code firstName}, {@code lastName}) and is annotated with
     * {@code @IdClass(CompositeKeyEmployeeId.class)}. The generated metamodel
     * must include a {@code SingularAttribute} for each key field.</p>
     */
    @Test
    void processorGeneratesIdClassKeyAttributes() throws IOException {
        String basedir = System.getProperty("user.dir");
        Path generatedFile = Path.of(basedir, "target", "generated-sources",
                "annotations", "io.vidocq.mansart.persistence.tests.TestCompositeKeyEmployee_.java");

        assertThat(generatedFile)
                .as("JPA static metamodel TestCompositeKeyEmployee_ should be generated")
                .exists()
                .isReadable();

        String content = Files.readString(generatedFile);

        assertThat(content).contains("public abstract class TestCompositeKeyEmployee_");
        assertThat(content).contains("@StaticMetamodel(TestCompositeKeyEmployee.class)");
        // Both @Id fields must appear as SingularAttribute in the generated metamodel
        assertThat(content).contains("SingularAttribute<TestCompositeKeyEmployee, java.lang.String> firstName");
        assertThat(content).contains("SingularAttribute<TestCompositeKeyEmployee, java.lang.String> lastName");
        // The non-key attribute should also be present
        assertThat(content).contains("SingularAttribute<TestCompositeKeyEmployee, java.lang.Integer> empNo");
    }
}
