/*
 * Copyright (c) 2026 Yann Blazart, Antoine Sabot-Durand and the Vidocq contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License, v. 2.0 are satisfied: GNU General Public License, version 2
 * or any later version, which is available at
 * https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR EUPL-1.2 OR GPL-2.0-or-later
 */
package io.vidocq.mansart.persistence.tests;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies that the Mansart persistence annotation processor generates
 * the JPA static metamodel class ({@code ClassName_}) for an {@code @Entity}.
 *
 * <p>The test entity {@code TestEntity} is compiled by Maven with the
 * processor on {@code annotationProcessorPaths}. This test reads the
 * generated {@code TestEntity_.java} from
 * {@code target/generated-sources/annotations/} and checks its content.</p>
 *
 * @see io.vidocq.mansart.persistence.processor.MansartPersistenceProcessor
 */
class MansartPersistenceProcessorTest {

    /**
     * Reads the generated static metamodel class and verifies its content.
     *
     * <p>The processor runs during Maven's compile phase. By the time
     * this test executes (test phase), the generated file should exist
     * at {@code target/generated-sources/annotations/TestEntity_.java}.</p>
     */
    @Test
    void processorGeneratesStaticMetamodel() throws IOException {
        String basedir = System.getProperty("user.dir");
        Path generatedFile = Path.of(basedir, "target", "generated-sources",
                "annotations", "io.vidocq.mansart.persistence.tests.TestEntity_.java");

        // The processor runs at compile time. If it works, the file exists.
        assertThat(generatedFile)
                .as("JPA static metamodel TestEntity_.java should be generated by the APT")
                .exists()
                .isReadable();

        String content = Files.readString(generatedFile);

        // Verify the generated class has the expected structure:
        // 1. Class name: TestEntity_
        // 2. @StaticMetamodel annotation
        // 3. SingularAttribute fields for each persistent attribute
        // 4. String constants for each attribute
        assertThat(content).contains("public abstract class TestEntity_");
        assertThat(content).contains("@StaticMetamodel(TestEntity.class)");
        assertThat(content).contains("SingularAttribute<TestEntity, java.lang.Long> id");
        assertThat(content).contains("SingularAttribute<TestEntity, java.lang.String> name");
        assertThat(content).contains("SingularAttribute<TestEntity, java.lang.Integer> age");
        assertThat(content).contains("SingularAttribute<TestEntity, java.lang.Integer> version");
        assertThat(content).contains("public static final String ID = \"id\"");
        assertThat(content).contains("public static final String NAME = \"name\"");
        assertThat(content).contains("public static final String AGE = \"age\"");
        assertThat(content).contains("public static final String VERSION = \"version\"");
    }
}
